examples/demo-react-native/android/app/src/main/AndroidManifest.xml, examples/demo-react-native/android/app/src/main/java/com/example/MainActivity.java, examples/demo-react-native/android/app/src/main/java/com/example/MainApplication.java, examples/demo-react-native/index.android.js
Tiny PR to bring the Android part of the demo-react-native example on par with iOS.
I am aware that Android is not yet supported. I plan to to work on that and send more PRs.
=> Fixed demo-react-native for Android.

CONTRIBUTING.md
After a fresh clone of the repo, `lerna run build` didn't work for me until I installed with `lerna install`. So I added it to the instructions for other clueless people :) 
Also some typos/English clarification thrown in for free.
=> Clarify setup instructions

detox/.gitignore, detox/android/detox/build.gradle, detox/android/detox/src/main/java/com/wix/detox/Delegator.java, detox/android/detox/src/main/java/com/wix/detox/Detox.java, detox/android/detox/src/main/java/com/wix/detox/DetoxManager.java, detox/android/detox/src/main/java/com/wix/detox/ReactInstanceEventListenerProxy.java, detox/android/detox/src/main/java/com/wix/detox/ReactNativeSupport.java, detox/android/detox/src/main/java/com/wix/detox/TestRunner.java, detox/android/detox/src/main/java/com/wix/detox/WebSocketClient.java, detox/android/detox/src/main/java/com/wix/detox/espresso/ReactBridgeIdlingResource.java, detox/android/detox/src/main/java/com/wix/detox/espresso/ReactNativeTimersIdlingResource.java, detox/android/detox/src/main/java/org/joor/Reflect.java, detox/android/detox/src/main/java/org/joor/ReflectException.java, detox/scripts/build.sh, detox/test/android/app/build.gradle, detox/test/android/app/src/androidTest/java/com/example/DetoxTest.java, detox/test/android/app/src/main/AndroidManifest.xml, detox/test/android/app/src/main/java/com/example/MainActivity.java, detox/test/android/app/src/main/java/com/example/MainApplication.java, detox/test/android/detox/build.gradle, detox/test/android/settings.gradle, detox/test/index.android.js, detox/test/package.json, detox/test/scripts/test_android.sh
Android support Phase I. (https://github.com/wix/detox/issues/96)
I tried to limit the scope to make a small PR. I failed in that. :)
Goals/achievements of this PR:
- Hook into React Native and monitor the internals.
-- JS timers
-- JS bridge
-- UI thread
-- UI BG thread
-- Native Modules thread
-- JS thread
- Set up Espresso IdlingResources for them.
- Implement React Native fast reloading.
- To NOT include RN as a dependency. Everything is implemented with reflection.
- Come up with how to integrate detox by the end user. Easy, one-liner solution.
- Async test runner. (Based on Rotem's idea)
- Keep the architecture similar to detox iOS.
Non-goals of the PR:
- JS -> Java invocation
- Mapping the JS test API -> Espresso API
- Wrapping up ADB
- Integrating Android into detox configuration, …
=> Android support. Phase I.

detox/src/devices/Device.js, detox/src/devices/Device.test.js
using numbers with decimals for lat/long in setLocation results in an error, it has to be passed as string with a comma as decimal separator to `fbsimctl`
=> convert setLocation params to string with comma as decimal separator

detox/src/ios/earlgreyapi/GREYActions.js, generation/__tests__/__snapshots__/earl-grey.js.snap, generation/__tests__/earl-grey.js, generation/earl-grey/index.js
=> fix GREYDirection type mismatch

detox/src/devices/Device.js, detox/src/devices/Device.test.js, detox/src/devices/DeviceDriverBase.js, detox/src/devices/Fbsimctl.js, detox/src/devices/Fbsimctl.test.js, detox/src/devices/SimulatorDriver.js, detox/test/e2e/f-device.js, docs/APIRef.DeviceObjectAPI.md
I added a new method to device to cleanup the device (like "Simulator > Reset Content and Settings" menu-item does), because I want to test specific screens which are only shown when the permissions are not set yet (e.g. a screen for explaining why the specific permission is needed)
=> device: add `resetContentAndSettings`

detox/android/detox/src/main/java/com/wix/detox/DetoxManager.java, detox/android/detox/src/main/java/com/wix/detox/ReactNativeSupport.java, detox/android/detox/src/main/java/com/wix/detox/WebSocketClient.java, detox/android/detox/src/main/java/com/wix/detox/espresso/DetoxAction.java, detox/android/detox/src/main/java/com/wix/detox/espresso/LooperIdlingResource.java, detox/android/detox/src/main/java/com/wix/detox/espresso/ReactBridgeIdlingResource.java, detox/android/detox/src/main/java/com/wix/detox/espresso/ReactNativeTimersIdlingResource.java, detox/android/detox/src/main/java/com/wix/detox/espresso/ReactNativeUIModuleIdlingResource.java, detox/android/detox/src/main/java/com/wix/detox/espresso/ScrollHelper.java, detox/src/Detox.js, detox/src/client/Client.js, detox/src/client/Client.test.js, detox/src/client/actions/actions.js, detox/src/devices/EmulatorDriver.js
Main change that could affect iOS is that the cleanup command now sends a parameter `stopRunner`. iOS can simply ignore it.
PR to let Travis do its job.
=> Cleanup refactor

docs/Guide.Contributing.md, generation/README.md
The goal of this PR is to make it easier for new contributors to start developing on the code generation.
@rotemmiz @awitherow Can one of you take a look if this makes sense in general? Would you feel encouraged to start working on this topic? 
Thank you so much for your time 👍
=> Documentation around code generation

detox/src/ios/earlgreyapi/GREYActions.js, generation/__tests__/earl-grey.js, generation/earl-grey/index.js, generation/fixtures/example.h
We currently generate code that isn't supported by the detox client.
This causes confusion amongst developers adopting the generated code (see #228).
=> Only generate methods with supported types

docs/Guide.RunningOnCI.md
I use Detox for testing our React Native app and it's been great so far. When it was time to put it on CI, I struggled a little bit to get it working on Bitrise (as we have been using Bitrise for running unit tests so far).
Hence after spending hours trying to getting Detox to work on Bitrise, I finally figure it out and so I thought I should share the solution so others can benefit from it. 
I have update the docs to show how to setup Detox on Bitrise. Hope this helps. 
Let me know if I need to make any changes. Thanks.
=> Updated Guide.RunningOnCI to include Bitrise instructions

detox/src/ios/expect.js
A small move from our handwritten EarlGrey adaptation to the generated one
=> Scroll Amount Action: Move to generated code

docs/Introduction.GettingStarted.md
In case this helps others not familiar with `xcodebuild`
=> Note on configuring detox with Xcode workspaces

detox/src/ios/earlgreyapi/GREYMatchers+Detox.js, detox/src/ios/earlgreyapi/GREYMatchers.js, detox/src/ios/matchers.js, generation/__tests__/__snapshots__/earl-grey.js.snap, generation/__tests__/__snapshots__/helpers.js.snap, generation/__tests__/earl-grey.js, generation/__tests__/helpers.js, generation/earl-grey/index.js, generation/fixtures/example.h, generation/index.js, generation/package.json
This reduces the amount of hand written adapter code. The entire matchers file is moved to generated adapter classes, which should enable us to move forward quicker in the future.
=> Move matchers to generated code

docs/Introduction.Android.md, docs/README.md
This should enable other users to use android more
easily as the current status configuration can be
quite confusing.
Build with the help of @appsthatmatter
Relates to #96
=> Add documentation for the usage with Android

docs/Guide.Jest.md, docs/README.md
Heavily inspired by the solution of @AlanFoster and with the help of @levito
=> Docs: Jest usage

docs/Introduction.Android.md
Paired with the help of @appsthatmatter
=> Improve Android documentation

detox/src/android/expect.js
There was a typo in the name of the java method. It was 'matherForAtIndex' instead of 'mat**c**herForAtIndex'
=> Fix Android atIndex matcher by fixing typo

docs/Guide.Jest.md, docs/Introduction.GettingStarted.md
We should probably keep the same patterns with defining E2E test like unit in jest (talking about __tests__ pattern). Also setup can be in one file if we conditionally load `detox` object. How do you feel about this? :) @DanielMSchmidt
=> Improvements in setup of jest runner. Update GettingStarted documentation.

docs/Introduction.GettingStarted.md
Latest applesimutils require Xcode 8.3+ and is required by detox, so I think we should update this version here :)
=> Update README for required Xcode version

detox/src/android/__snapshots__/matcher.test.js.snap, detox/src/android/matcher.test.js, detox/src/ios/__snapshots__/matcher.test.js.snap, detox/src/ios/matcher.test.js
This enables us to refactor matchers more easily, e.g. move towards the generated code
=> Add snapshot tests for matchers

detox/local-cli/detox-test.js, docs/APIRef.DetoxCLI.md, docs/Guide.Jest.md
Scope of changes:
- Add `jest` to `detox --help` command
- Add missing flags for "test:e2e" script
=> Update Jest-related docs

detox/src/Detox.js, detox/src/devices/AndroidDriver.js, detox/src/devices/AttachedAndroidDriver.js, detox/src/devices/EmulatorDriver.js, docs/Introduction.Android.md, docs/More.AndroidSupportStatus.md
As discussed in #386 and in https://github.com/wix/detox/issues/96#issuecomment-343156488 , I've implemented AttachedAndroidDriver (really a cut version of EmulatorDriver) that is able to connect to Genymotion and other adb-attached devices.
Also updated doc. Not sure if a test required.
=> Implemented AttachedAndroidDriver device for connecting to Genymotion

detox-cli/package.json, detox-server/package.json, detox/.eslintrc, detox/package.json, detox/scripts/build.sh, detox/test/.flowconfig, detox/test/e2e/init.js, docs/Troubleshooting.RunningTests.md
Remove deprecated package and updated to latest suggest package per Babel docs.
I was noticing errors with a project that was not importing _babel-preset-latest_ as a dev dependency. Rather than importing deprecated code I went ahead and updated to current logic. 
_Example:_
```js
detox test
```
would return 
`Couldn't find preset "latest" relative to directory "/Users/arista/***/node_modules/detox"`
=> Stop transpiling detox and detox-server, use sources and require node >=7.6

docs/APIRef.MockingUserNotifications.md
=> Minor documentation fix

detox/android/detox/build.gradle, detox/android/detox/src/main/java/com/wix/invoke/MethodInvocation.java, detox/android/detox/src/main/java/com/wix/invoke/parser/JsonParser.java, detox/android/detox/src/main/java/com/wix/invoke/types/ClassTarget.java, detox/android/detox/src/main/java/com/wix/invoke/types/Invocation.java, detox/android/detox/src/main/java/com/wix/invoke/types/InvocationTarget.java, detox/android/detox/src/main/java/com/wix/invoke/types/ObjectInstanceTarget.java, detox/android/detox/src/main/java/com/wix/invoke/types/Target.java, detox/android/detox/src/test/java/com/wix/invoke/JsonParserTest.java, scripts/ci.android.sh
With this PR we get rid of the dependency towards `com.fasterxml.jackson`. The android unit tests work, unfortunately I can't compile to run the android unit E2E tests. I am a bit unsure if this is a problem with my local setup or a general problem.
=> Exchange com.fasterxml.jackson with org.json implementation

detox/package.json, detox/src/client/Client.js, detox/src/devices/AndroidDriver.js, detox/src/devices/EmulatorDriver.js, detox/src/devices/android/AAPT.js, detox/src/devices/android/ADB.js, detox/src/devices/android/Emulator.js, detox/src/devices/android/EmulatorTelnet.js, detox/src/utils/exec.js
1. Making sure all child proccesses are closed, fixing issues with Mocha 4 and Jest
2. Spawning a detached emulator process, gaining same behaviour as we have in iOS, which leaves simulator open when tests are done
3. Applying fix on broken emulator config.ini
4. Better sync through reading getprop dev.bootcomplete
=> Better Android emulator sync

detox/local-cli/detox-test.js, examples/demo-react-native/e2e/init.js
`detox test -c ios.sim.release --platform ios` will skip tests marked with `:android:` in their name
`detox test -c android.emu.release --platform android` will skip tests marked with `:ios:` in their name
=> Support for filtering platform specific tests in detox-cli 

detox/.eslintrc, detox/package.json
This is the first PR to help deliver https://github.com/wix/detox/issues/223 
This Pr adds support for prettier as part of detox's linting pipeline. In the future you can automagically fix errors with:
```shell
npm run lint -- --fix
```
In a separate PR I will add support for connecting this up to the CI pipeline, and husky for pre-push validations :+1:
=> Add prettier to detox folder

detox/src/android/espressoapi/DetoxAction.js, detox/src/ios/earlgreyapi/GREYActions.js, detox/src/ios/earlgreyapi/GREYMatchers+Detox.js, detox/src/ios/earlgreyapi/GREYMatchers.js, generation/__tests__/ios.js, generation/adapters/ios.js, generation/core/generator.js, generation/core/global-functions.js
As discussed in #425 this removes unused globals from the generated code
=> Generation: Remove unused helpers from generated code

detox/src/android/expect.js
As discussed in #425 this adds tap at location support (I thought there were more than this, this is why I split it up)
=> Add generation for tap at location

generation/.prettierrc, generation/package.json
This is part of the general effort to forget about code formatting altogether 👍  I would apply the formatting by running `cd generation/ && npm run format` after we merge this
=> Add prettier formatting for code generation

detox/src/devices/AppleSimUtils.js, detox/src/devices/AppleSimUtils.test.js
We rely on an external tools output here, so quoting
the place gives us a bit more information on why the
regex might fail in certain scenarios.
I am referring to failed builds like this one: https://travis-ci.org/wix/detox/jobs/325861194
=> Add quotes around xcode version output

detox/src/ios/earlgreyapi/GREYActions.js, detox/src/ios/earlgreyapi/GREYMatchers.js, generation/core/type-checks.js
The isArray check contained information about a certain place where it was used.
This made it impossible to reuse, therefore this part needed to change.
I am unsure, but it appears to me that we have unformatted code check in for the generated code, therefore the changeset is so big.
=> Fix error message to not state false information

detox/src/android/espressoapi/DetoxMatcher.js, detox/src/android/matcher.js, generation/index.js, generation/package.json
In this PR I only change some of the matchers (the ones without any args that could be easily exchanged). 
I kept this PR small to be easily reviewable, the next one will add the other matchers.
=> Generation: Add Android Matchers to generated code

detox/src/android/espressoapi/DetoxAction.js, detox/src/android/expect.js, generation/__tests__/__snapshots__/android.js.snap, generation/__tests__/__snapshots__/global-functions.js.snap, generation/__tests__/android.js, generation/__tests__/global-functions.js, generation/adapters/android.js, generation/adapters/ios.js, generation/core/generator.js, generation/core/global-functions.js
To do this I had to add some mechanisms to allow
sanitizers to work with function names and arguments
instead of only with types as before.
Also some more types were enabled.
=> Generation: Move DetoxAction invocations to generated code

detox/src/android/espressoapi/DetoxMatcher.js, detox/src/android/espressoapi/ViewActions.js, detox/src/android/expect.js, generation/adapters/android.js, generation/core/generator.js, generation/index.js, generation/package.json, generation/utils/__tests__/downloadEspresso.js, generation/utils/downloadEspresso.js
This PR allows us to get the source code of espressos APIs (which are not checked in to this project) and generate code from them. I used it for three actions, other ones will be quick wins (by adding the String type)
=> Generation: Add generation for external files

detox-server/package.json, detox/package.json
This fixes some broken links to the homepage.
I decided to link to the main readme from the `detox-server` `package.json`, let me know if you'd rather have it link to the specific `README.md`.
=> Fix homepage in detox & detox-server package.json

docs/APIRef.waitFor.md
Fixed the section link for the 'whileElement()' section link in the Manual Synchronization doc.
=> Fixed section link in doc

docs/Guide.Jest.md
Replace `jasmine.DEFAULT_TIMEOUT_INTERVAL` with `jest.setTimeout()` in Jest Guide.
Since jest@20 or so [jest.setTimeout](https://facebook.github.io/jest/docs/en/jest-object.html#jestsettimeouttimeout) is available, instead of jasmine-specific timeout constant. I think it's worth using official APIs when available.
=> Docs: Use jest.setTimeout instead of jasmine timeout

detox/src/devices/Device.js, detox/src/devices/Device.test.js, detox/test/e2e/o-location.js, docs/APIRef.DetoxObjectAPI.md
using comma instead of dot will cause fbsimctl to fail.
=> set location should not use comma

detox/scripts/build_framework.ios.sh
Hi!
When building `Detox.framework`, the `ios_src` folder, which contains a Detox.xcodeproj file, is not deleted. Because of this, running `react-native link` will link this project and all its dependencies to the react-native app leading to code signing issues.
The following error occurs when Xcode tries to build SocketRocket : 
```
2018-02-20T10:11:02.9468320Z === BUILD TARGET TestChat OF PROJECT SocketRocket WITH CONFIGURATION Release ===
2018-02-20T10:11:02.9477620Z 
2018-02-20T10:11:02.9494720Z Check dependencies
2018-02-20T10:11:02.9526730Z Code Signing Warning: "TestChat" isn't code signed but requires entitlements. It is not possible to add entitlements to a binary without signing it.
2018-02-20T10:11:02.9576440Z Code Signing Error: Code signing is required for product type …
```
=> Clean up after build_framework

detox/src/devices/AppleSimUtils.js, detox/src/devices/AppleSimUtils.test.js, docs/Guide.RunningOnCI.md, docs/Introduction.GettingStarted.md
Installing applesimutils seems to be required to have builds pass in Travis.
=> Update Example .travis.yml in CI Guide

detox/src/devices/android/APKPath.js, detox/src/devices/android/APKPath.test.js, detox/src/utils/string.js, detox/src/utils/string.test.js
I initially created issue #522 as I wasn't familiar with this codebase to PR a solution.
Since then PR #537 was created to fix it.
Unfortunately I still have the problem.  In my real life app example my input SDK path is
```
~/android/app/build/outputs/apk/pocPlayStore/debug/app-poc-playStore-debug.apk
```
and the detox build physically builds to 
```
~/android/app/build/outputs/apk/androidTest/pocPlayStore/debug/app-poc-playStore-debug-androidTest.apk
```
I built off #537 adding my real world example to the tests and updated required logic to generate the expected result. 
I introduced a new strings util file as I needed to do some string manipulation.  Mainly converting `['poc', 'playStore']` to `pocPlayStore`.
=> Support testApk path for gradle builds with multiple flavor matrix

detox/local-cli/detox-test.js
Agnostic approach to running a specific test file. 
former PR: https://github.com/wix/detox/pull/502
=> add -f option to run specific test file

detox/src/devices/AppleSimUtils.js, detox/src/devices/AppleSimUtils.test.js, detox/src/devices/SimulatorDriver.js
Ran into some issues getting detox to work on the first project I used it with. This allow apps with spaces in the name to run correctly.
=> Support spaces in iOS app name

docs/APIRef.DeviceObjectAPI.md
test filename was changed from `l-permissions.js` to `m-permissions.js`
=> docs: Fix broken link to detox permission tests

.travis.yml, detox/android/detox/src/main/java/com/wix/detox/DetoxManager.java, detox/android/detox/src/main/java/com/wix/detox/ReactNativeCompat.java, detox/android/detox/src/main/java/com/wix/detox/ReactNativeSupport.java, detox/android/detox/src/main/java/com/wix/detox/espresso/AnimatedModuleIdlingResource.java, detox/android/detox/src/minReactNative46/java/com/wix/detox/WebSocketClient.java, detox/src/android/expect.js, detox/src/client/Client.js, detox/test/package.json
This PR aims to:
1. Add support for changes made in [NativeAnimatedModule](https://github.com/facebook/react-native/commit/2b4ff6ea19dc674cf035ee419daa132cde8d1f5e#diff-a735317509988b7133cb51f6ea6cbd1f) 
2. Temp fix for `waitForReactNativeLoad` by adding Thread.sleep() on RN>=50, not ideal, but will enable usage of Detox on RN51 projects even before we find the true culprit of this sync defect.
=> Android: Support RN50-51 changes

detox/android/detox/src/main/java/com/wix/detox/DetoxManager.java
By the JavaDocs of Detox.java, "If not set, then Detox tests are no ops. So it's safe to mix it with other tests."
However, this is not true, since the code will throw a NullPointerException and crash the tests. A simple nullcheck will avoid it.
As a side recommendation, the usage of nullability annotations helps catching this issues. Please consider adding them to the project. I am happy to do so if deemed acceptable.
=> Avoid NPE when DetoxServerUrl and DetoxSessionId are not set

docs/Troubleshooting.RunningTests.md
Very minor tweak: in the `Troubleshooting#RunningTests` documentation, the title
> Enable **deugging** of synchronization issues
changed to 
> Enable **debugging** of synchronization issues
=> Change 'deugging' to 'debugging' in TroubleShooting#RunningTests docs

detox/src/invoke/Invoke.test.js, detox/src/ios/earlgreyapi/GREYActions.js, detox/src/ios/earlgreyapi/GREYCondition.js, detox/src/ios/earlgreyapi/GREYConditionDetox.js, detox/src/ios/earlgreyapi/GREYInteraction.js, detox/src/ios/earlgreyapi/GREYMatchers.js, detox/src/ios/expect.js, generation/__tests__/global-functions.js, generation/__tests__/ios.js, generation/adapters/ios.js, generation/core/generator.js, generation/core/global-functions.js, generation/core/type-checks.js, generation/fixtures/example.h, generation/index.js, generation/package.json
This PR moves most iOS calls over to generated code (`detox_selectElementWithMatcher` is the only missing one and it's a bit of a special case.
=> Add generation for GREYInteraction

docs/Guide.DebuggingInXcode.md
PR fixes a missing title in ToC, see **Guide.DebuggingInXcode** on the screenshot.
=> docs: fix missing article name in table of contents

detox/local-cli/detox-test.js, detox/src/devices/android/Emulator.js, docs/APIRef.DetoxCLI.md
=> Add no window option for running android emulator with no window

detox/src/ios/expect.js, detox/src/ios/expect.test.js, detox/test/e2e/c-actions.js, detox/test/src/Screens/ActionsScreen.js, docs/APIRef.ActionsOnElement.md
Related to #410. I also added the test case `Long Press Me 1.5s`.
=> Add duration of element.longPress for iOS

.prettierrc, detox/src/android/espressoapi/DetoxAction.js, detox/src/android/espressoapi/DetoxMatcher.js, detox/src/ios/earlgreyapi/GREYActions.js, detox/src/ios/earlgreyapi/GREYConditionDetox.js, detox/src/ios/earlgreyapi/GREYMatchers.js, generation/.prettierignore, generation/.prettierrc, generation/__tests__/android.js, generation/__tests__/global-functions.js, generation/__tests__/helpers.js, generation/__tests__/ios.js, generation/adapters/android.js, generation/adapters/ios.js, generation/check-for-git-changes.sh, generation/core/generator.js, generation/core/global-functions.js, generation/core/type-checks.js, generation/package.json, generation/utils/downloadEspresso.js
We had at times updates of the source for code generation not being reflected in the adapters as the code was not generated again. Let's add a check for this here 👍
=> Add check for ungenerated code

detox/src/devices/android/Emulator.js
Since Android SDK Tools 25.3.0 (March 2017) The Android Emulator was removed from the SDK Tools package and moved to a different SDK directory: [Android Emulator v15.3.0 release notes](https://developer.android.com/studio/releases/emulator#25-3)
Also, according to [this issue in the google issue tracker](https://issuetracker.google.com/issues/66886035) the new path is also the preferred way of invoking the emulator, and the old path will at some point be deprecated / removed.
For recent API versions (and depending on the OS architecture) running the old tools/emulator can cause errors because the different architecture versions of the emulator won't be found in the tools folder of the Android SDK. By example, I'm using the Android SDK v27 build tools and the latest versions of all the …
=> Update Android emulator path to support SDK Tools >=25.3.0

detox/.eslintrc, detox/android/detox/src/main/java/com/wix/detox/espresso/DetoxMatcher.java
=> Android: force matchers to ignore layouts with GONE visibility

docs/APIRef.ActionsOnElement.md
Small typo `keybaord` -> `keyboard`
=> Fix typo on ActionsOnElement docs

detox/src/android/matcher.js, generation/README.md, generation/utils/downloadFile.js
=> Move android matchers to generated code

detox/src/devices/android/Emulator.js
Android: on headless mode, default to high-perf software renderes `swiftshader_indirect` and `angle_indirect`
=> Android: on headless mode, default to high-perf software renderes `swiftshader_indirect` and `angle_indirect`

README.md
motivation: readme contains information about supported versions and it should be more explicit because: 
* Currently is says "React Native versions 0.44 and above are supported." and the readme wasn't updated in 5 months, so it certainly wasn't correct in the time when 0.50 wasn't working on android. 
* It also isn't "future-proof" because whenever a new RN version is released, the sentence automatically makes user think the new version is supported which may not be true
For people like me who occasionally come to the repo to check if their RN version is supported, this will be a big help that will save time digging through issues.
I based the table contents on this [comment](https://github.com/wix/detox/issues/608#issuecomment-388679980), not sure what the supported versions really are.
=> be explicit about supported RN versions

detox/src/artifacts/templates/artifact/Artifact.js
Since Detox has a very relaxed Lodash version requirement (`^4.14.1` in [package.json](https://github.com/wix/detox/blob/master/detox/package.json#L47)), one of our users (@tachtevrenidis) had an issue (https://github.com/wix/detox/issues/805) when the older `_.isFunction` could not recognize `async function`.
Although, the issue itself was addressed quite a long time ago, in https://github.com/lodash/lodash/commit/95bc54a3ddc7a25f5e134f5b376a0d1d96118f49 , nevertheless I suggest this patch to prevent the further occurrences of this bug. This patch is too hard to locate and too expensive to debug (1+ hour of remote debug session in a video call).
@rotemmiz , can we get it merged soon? Many thanks in advance!!!!
=> Closes #805 - and prevents further bugs with older _.isFunction

detox/local-cli/detox-test.js, detox/src/Detox.test.js
A couple quick fixes for `detox test --platform` and detox self unit tests running on windows.
=> Follow-up windows changes

detox/src/index.js, detox/src/index.test.js
Since there is an issue with Jest that prints the exception that happened inside `beforeAll` inside regular tests, it is problematic to track where the actual issue took its place.
The pull request makes the following changes:
0) `validateConfig()` is merged inside `initializeDetox()` since it is quite small and used only once
1) `detox.init` wraps `initializeDetox` in try-catch statements, so that:
2) errors get logged
3) just in case, if there was something created in the middle, the `cleanup` method is called
4) errors are rethrown again
5) detox variable is set to `null` to prevent erroneous calls to `beforeEach`, `afterEach`, `cleanup`
=> Make detox.init() stricter - should log error as soon as it happens

detox/src/devices/AndroidDriver.js, detox/src/devices/android/ADB.js, detox/src/devices/android/ADB.test.js, detox/src/utils/regexEscape.js, detox/src/utils/regexEscape.test.js
Changes `ADB.pidof()` helper method implementation to the most backward-compatible way: `ps | grep`.
Tested on API 19, 21, 28.
=> Resolves #831

detox/scripts/postinstall.js
We found that we where not able to install `detox` if the project is
installed on a path with spaces on parent directories.
For example, if we clone the project on `~/My Projects/my-project`,
running `npm install` will fail to locate the `detox/scripts/build_framework.ios.sh`.
```
/bin/sh: /Users/me/My: No such file or directory
child_process.js:615
throw err;
^
Error: Command failed: /Users/me/My Projects/my-project/node_modules/detox/scripts/build_framework.ios.sh
at checkExecSyncError (child_process.js:575:11)
```
This is related to [node's child_process](https://github.com/nodejs/node/issues/6803) handling of
filepaths on `exec`.
Instead of locating the file as `~/My Projects/my-project/node_modules/detox/scripts/build_framework.ios.sh`, it passes the argument as `~/My` and fails to …
=> Allow execution of post-install scripts on paths with space

detox/local-cli/detox-test.js
For Node.js debugging purposes it is nice to be able to copy&paste `jest` test command that `detox test` produces as-is and prepend there `node --inspect-brk`.
Currently the printed command lacks a critical piece - environment variables configuration.
The improvement is going to look the following way:
```
x@y:~/Projects/detox/detox/test$ npm run e2e:android
> detox-test@0.0.1 e2e:android /home/x/Projects/detox/detox/test
> detox test --configuration android.emu.release --loglevel trace --take-screenshots all --record-videos none --record-logs all
configuration="android.emu.release" loglevel="trace" artifactsLocation="artifacts/android.emu.release.2018-07-24 09-58-04Z" recordLogs="all" takeScreenshots="all" recordVideos="none" node_modules/.bin/jest e2e --config=e2e/config.json …
```
=> Printing environment variables before `jest` test command

scripts/publish-website.sh, website/gatherDocs.js
There seem to be flakiness issues on CI, this is an approach to dampen the effect on us while investigating the root cause.
=> Make doc generation more robust

detox/ios/.tbzignore, detox/scripts/build.js
This will significantly reduce TBZ size
=> Add .tbzignore and use it when creating the Detox source tbz

detox/src/utils/exec.js, detox/src/utils/exec.test.js
See issue: https://github.com/wix/detox/issues/865
=> fix: stderr of the spawned process should be printed using log.error()

docs/Guide.Migration.md
in the jest migration guide, there are both ES5 function and arrow functions, so this makes it a little more consistent. related: https://github.com/wix/detox/pull/866#issuecomment-408868168
=> change ES5 function to arrow function for consistency

detox/local-cli/detox-test.js, detox/src/index.js, detox/src/index.test.js, docs/APIRef.DetoxCLI.md
For #875 
This PR adds an extra command line param to `detox test` to override the device name in a given configuration. This is handy for when you want to run a test for the same configuration across multiple devices. E.g:
```
detox build --configuration ios.sim.release --device-name 'iPhone X'
```
=> Add CLI parameter for overriding device name

detox/src/devices/android/ADB.js
=> fix(win32): new regexp for ADB.pid which is compatible with findstr utility

detox/ios/Detox/GREYMatchers+Detox.m, detox/test/package.json
=> Fix multiple elements matched when dealing with nested scrollviews.

detox/scripts/build_framework.ios.sh
The `()` syntax spawns a subshell and executes the commands. Hence, the "successful" `exit 0` is trapped and is effectively a no-op. This change instead moves the execution of the `echo` statement to the parent shell which causes the `exit 0` to actually kill the process where it is.
This is part of the fixes to the `build_framework.ios.sh` shell script that I had requested in #897.
This PR changes from subprocess execution to in-shell execution. The biggest change that this makes is that it causes the `exit 0` to actually stop the shell script.
=> build_framework.ios.sh: echo/exit from current shell

docs/APIRef.DetoxObjectAPI.md
* Noticed the links to the methods for detox `object` didn't work, so went ahead an fixed them up.
* And apparently my editor cleaned up some whitespace 🤷‍♂️
=> Fix links in detox object docs

detox/android/detox/src/main/java/com/wix/detox/espresso/ReactBridgeIdlingResource.java
remove @override annotation on onBridgeDestroyed as it is not introduced until react-native 0.56 and breaks previous react-native versions
See https://github.com/wix/Detox/issues/919
The [NotThreadSafeBridgeIdleDebugListener](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/bridge/NotThreadSafeBridgeIdleDebugListener.java) interface doesn't add the method   `onBridgeDestroyed()` until RN 0.56 this causes builds prior than that to break with an error as follows:
```
Task :detox:compileMinReactNative46DebugJavaWithJavac FAILED
.../node_modules/detox/android/detox/src/main/java/com/wix/detox/espresso/ReactBridgeIdlingResource.java:65: error: method does not override or implement a method from a supertype
@Override
^
Note: …
```
=> [Android] Remove @override annotation to support RN 0.53-0.55 on detox 9.0

detox/scripts/build_universal_framework.sh
In Xcode 10, the build system defaults to the `New Build System` launched in Xcode 9. Because of this, the `postinstall` script fails with the following error (only important parts added. [see here for complete log](https://gist.github.com/karanjthakkar/6a5cda03cc223e688f4e7e623fa43750)): 
```
<blah blah>
PhaseScriptExecution Run\ Script /Users/karanthakkar/Library/Detox/ios/3b8bf121e33a47a46e6d2ca92c7d743d2d56b3cf/DetoxBuild/Build/Intermediates.noindex/Detox.build/Release-iphoneos/DetoxFramework.build/Script-3941F4F61DC6203000F23DAC.sh (in target: DetoxFramework)
<blah blah>
note: Using new build system
error: Could not delete `/Users/karanthakkar/Work/skyscanner-app/react-native/node_modules/detox/ios_src/COSTouchVisualizer/Classes/build` because it was not created by the build system …
```
=> Use legacy build system to build framework

detox/test/package.json, examples/demo-native-ios/package.json, examples/demo-react-native-jest/package.json, examples/demo-react-native/package.json
Intended to be temporary so we can check Detox + XCode 10 issues as well.
=> hotfix: legacy build workaround to fix monorepo build on XCode 10

detox/scripts/build_universal_framework.sh
avoid the `mktemp: too few X's in template 'DetoxBuild'` error on macosx when using mktemp from coreutils
=> Make compatible with BSD + GNU mktemp

detox/src/devices/ios/AppleSimUtils.js
Resolves #954 
I suggest merging a hotfix given a blocker status of `appleSimUtils.install()` with XCode 10.
@LeoNatan , @rotemmiz , what do you think?
@guyca , can you check if it helps in your case, please?
=> hotfix: added a retry on install (XCode 10 issue)

docs/Guide.Expo.md
I've checked the [docs](https://expo.io/tools) right here for installation and thought that perhaps `Expo Client` is more clear than `Expo app`?
=> Update the document for Expo

detox/scripts/build_framework.ios.sh
We found out that a project that lives under a path with spaces make the
post-install script fail. Our CI checks the project under `~/Application Support/project` which makes the script throw an error.
```
> detox@8.2.3 postinstall /Users/bruno/Go
Agent/mobile/node_modules/detox
> node scripts/postinstall.js
+ xcodebuild -version
+++ dirname /Users/bruno/Go
Agent/mobile/node_modules/detox/scripts/build_framework.ios.sh
usage: dirname path
++ dirname
usage: dirname path
+ detoxRootPath=
child_process.js:632
throw err;
^
Error: Command failed: /Users/bruno/Go
Agent/mobile/node_modules/detox/scripts/build_framework.ios.sh
```
This is caused by the argument expansion on shell to think it is taking
more arguments than it should. The strategy is to use quotes on shell
scripts when refering to …
=> Fix post-install script when project lives on a path with spaces

detox/src/devices/android/ADB.js
Seeing lately errors like this:
```
detox[39596] ERROR: [exec.js/SPAWN_STDERR, #31] read: unexpected EOF!
```
Looks like a workaround for unsupported logcat `-f` option on older API levels did not work 100% correctly. So I think we could revert to the previous logic for API levels that support it.
=> hotfix: read unexpected EOF error message in logs

examples/demo-react-native/android/build.gradle
I was having some issues running the demo (stuff from react-native was not being found during build), and this seems to fix it. Note that this is the same value as in https://github.com/wix/detox/blob/master/examples/demo-react-native-jest/android/build.gradle which was generated with a newer version of RN
steps to reproduce:
- clone repo and cd to the example folder
- run yarn
- run `detox build --configuration android.emu.debug` output:
```
vojta@Vojta-MacBook-Pro demo-react-native (master)$ detox build --configuration android.emu.debug
pushd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && popd
~/dev/temp/Detox/examples/demo-react-native/android ~/dev/temp/Detox/examples/demo-react-native
> Configure project :app
WARNING: The option 'android.enableAapt2' …
```
=> update build.gradle in demo-react-native

docs/Guide.Contributing.md
Contribution guide has been lacking this for quite a while.
=> docs: update info on how to update artifacts snapshots for e2e

detox/ios/Detox/ReactNativeSupport.m, detox/test/ios/example/AppDelegate.m
=> Refine WXRNLoadIdlingResource to wait for JSDidLoad rather than ContentDidAppear

detox/src/ios/earlgreyapi/EarlGreyImpl.js, detox/src/ios/earlgreyapi/GREYActions.js, detox/src/ios/earlgreyapi/GREYCondition.js, detox/src/ios/earlgreyapi/GREYConfiguration.js, detox/src/ios/earlgreyapi/GREYInteraction.js, detox/src/ios/earlgreyapi/GREYMatchers.js, generation/__tests__/ios.js, generation/adapters/android.js, generation/adapters/ios.js, generation/core/generator.js, generation/core/type-checks.js, generation/helpers.js, generation/package.json
This allows us to have nicer comments in our generated code (and we need to do it anyways at some point).
=> Move generation to babel 7

examples/demo-native-ios/e2e/init.js
Depending on the npm package means we don't need to `npm install` the root detox/ project.
=> Reverted relative import of detox

detox/ios/Detox/DetoxManager.m, docs/APIRef.DeviceObjectAPI.md
Allow the user to set the blacklist for EarlGrey upon initialization of the `DetoxManager`. This will also help fix https://github.com/wix/Detox/issues/917
When `device.launchApp` is called, it waits for the device to be ready. In order for the device to be ready, all the tracked Earl Grey resources must be idle. Because Earl Grey tracks all network requests by default, if there are any network calls happening, the app will be considered 'busy'. 
Consider the case where an app is making many network calls to an URL we wish to be blacklisted. First, the app must be launched via `device.launchApp`. Next, the blacklist needs to be set via `device.setURLBlacklist`. However, because there is currently no way to set the blacklist upon initialization, Earl Grey will always consider the app to be …
=> add blacklistRegex to GREYConfiguration on init

detox/src/devices/ios/AppleSimUtils.js, detox/src/devices/ios/AppleSimUtils.test.js, detox/src/devices/ios/__snapshots__/AppleSimUtils.test.js.snap
Whatever the user specifies in `SIM_CTL_DYLD_INSERT_LIBRARIES` should propagate through and be reflected in the `xcrun simctl launch` call that AppleSimUtils makes.
My use case: I am passing in my own dylibs that I specify in `SIM_CTL_DYLD_INSERT_LIBRARIES`, and I would like this dylib to get used by my app. This will also help me fix https://github.com/wix/detox/issues/917
I append the detox framework path to the env var, separated by a colon, as this is the format expected specified by `man dyld`: 
```
DYLD_INSERT_LIBRARIES
This is a colon separated list of dynamic libraries to load before the ones specified in the program.  This lets you test new modules of
existing dynamic shared libraries that are used in flat-namespace images by loading a temporary dynamic shared library with just …
```
=> append instead of clobber SIM_CTL_DYLD_INSERT_LIBRARIES

docs/Guide.Mocking.md
Metro versions >= v0.43 have a new configuration format. By default RN >= 0.57 need to use this new configuration for rn-cli.config.js otherwise it won't work.
This PR updates the mocking guide with this new format which is needed to use e2e.js files in RN from version 0.57
=> Update mocking guide for RN >= 0.57

docs/Guide.Expo.md
Expo apps didn't play well with detox 7 and above. I've since made some fixes for this, and it works for detox v9.0.6 now. Updating docs to reflect this change.
=> update expo usage guides

detox/src/devices/drivers/AttachedAndroidDriver.js
Resolves #1027 
/cc @jgreen210
=> fix: enable acquiring an already attached emulator by ADB name

docs/APIRef.Configuration.md
Lists the possible values for the `type` configuration, even though `ios.simulator` is the only supported value.
=> List possible values for `type`

detox/android/detox/src/main/java/com/wix/detox/ReactNativeSupport.java, detox/android/detox/src/main/java/com/wix/detox/espresso/DetoxViewActions.java, detox/android/detox/src/main/java/com/wix/detox/espresso/ReactNativeTimersIdlingResource.java, detox/src/android/espressoapi/ViewActions.js, detox/test/e2e/03.actions.test.js, detox/test/e2e/09.stress-timeouts.test.js, detox/test/e2e/12.animations.test.js
@rotemmiz just for review, don't merge
=> Android: Increase RN-timers idling resources look-ahead to 1.5sec

detox/src/android/expect.js, detox/src/android/expect.test.js, detox/src/ios/expect.js, detox/src/ios/expect.test.js, detox/test/e2e/03.actions.test.js, detox/test/src/Screens/ActionsScreen.js, docs/APIRef.ActionsOnElement.md
---
This PR adds support for pressing the backspace and return keys on both iOS and Android. Although iOS support exists by using typeText and the `\b` and `\n` keys, this was unclear and not cross-platform. The pressBackspaceKey and pressReturnKey methods abstract these features for both platforms.
**Note:** I did try adding a `numberOfTimes` parameter as a shortcut for pressing the backspace or return key multiple times, however I wasn't able to figure out the simplest way for executing multiple actions:
For both Android and iOS, the addition `numberOfTimes` for pressReturnKey is pretty straightforward:
```javascript
async pressReturnKey(numberOfTimes = 1) {
if (numberOfTimes && typeof numberOfTimes !== 'number') { throw new Error('...') }
return await new ActionInteraction(this, new …
```
=> New Actions: `tapBackspaceKey` and `tapReturnKey`

detox/android/detox/src/main/java/com/wix/detox/espresso/ReactNativeTimersIdlingResource.java, detox/test/e2e/09.stress-timeouts.test.js, detox/test/src/Screens/TimeoutsScreen.js
Though in 5a179cac we've improved the RN-timers idling resource on Android - making it effective for the 1st time, we didn't take repeating timers (i.e. JS intervals) into account.
This branch introduces an iOS-equivalent solution that simply ignores intervals and takes the nearest non-repeating timer as the one to inspect.
=> Android Sync: Improve RN-timers idling resource such that it would skip over interval-timers

detox/src/android/espressoapi/DetoxAssertion.js, detox/src/android/espressoapi/DetoxMatcher.js, detox/src/android/espressoapi/DetoxViewActions.js, detox/src/android/espressoapi/EspressoDetox.js, detox/src/android/espressoapi/UIDevice.js, detox/src/android/espressoapi/ViewActions.js, detox/src/android/expect.js, detox/src/invoke/Invoke.test.js, detox/src/ios/earlgreyapi/EarlGrey.js, generation/__tests__/__snapshots__/android.js.snap, generation/__tests__/android.js, generation/__tests__/global-functions.js, generation/adapters/android.js, generation/core/generator.js, generation/core/global-functions.js, generation/core/type-checks.js, generation/fixtures/example.java, generation/index.js
=> Move expect.js to generated code

docs/APIRef.DetoxObjectAPI.md
---
Previously there was an extra space between device and \`. Now, there is not.
=> Fix typo in APIRef.DetoxObjectAPI.md

detox/android/detox/src/main/java/com/wix/detox/Detox.java, detox/src/android/espressoapi/Detox.js, detox/src/devices/Device.js, detox/src/devices/Device.test.js, detox/src/devices/drivers/AndroidDriver.js, detox/test/android/app/src/androidTest/java/com/example/DetoxTest.java, detox/test/android/app/src/main/AndroidManifest.xml, detox/test/android/app/src/main/java/com/example/SingleInstanceActivity.java, detox/test/android/app/src/main/res/values/strings.xml, detox/test/e2e/15.urls.test.js, docs/Introduction.Android.md
Address the problem specified in #1125.
The root cause resides in what appears to be an Espresso bug (still need to validate this). This PR introduces a workaround, along with associated improvements around the current confusion the android driver currently has around activities launching. I suppose that can be further improved, but one step at a time.
=> Fix issues related to single-task activities

detox/src/ios/earlgreyapi/GREYMatchers.js, detox/test/e2e/02.matchers.test.js, generation/__tests__/global-functions.js, generation/core/global-functions.js
---
Fixes #1131
When searching for an element with the trait header I noticed that the Element matcher was searching for the trait UIAccessibilityTraitImage.
Corrected using the following list:
docs.microsoft.com/en-us/dotnet/api/UIKit.UIAccessibilityTrait
=> fix: correct ordering of accessibility traits

detox/local-cli/detox-test.js, detox/src/devices/android/Emulator.js
Resolves #1176 
Only adds the `-gpu [gpu mode]` flags to the android `emulator` command if the `--headless` parameter is specified or if an explicit `--gpu [gpu mode]` cli argument is provided.
=> PR (Issue #1176) - Stop Forcing -gpu host on android emulators

docs/APIRef.MockingUserNotifications.md
relauch -> relauNch.
- [  X ] This is a small change 
Corrected typo in relauNch word.
=> Corrected typo.

detox/ios/Detox/DetoxAppDelegateProxy.m
---
***Issue: https://github.com/wix/Detox/issues/1230***
Some iOS developer use `[UIApplicaiton sharedApplication].keyWindow.rootViewController` as a convenient way to get a VC instance. Surely, this isn't suggested, but it's widely used anyway.
When the app is driven by Detox, this call would return null. It's because DTXTouchVisualizerWindow has a very high windowLevel and doesn't has any ViewController.
This PR fixes this issue by avoid making DTXTouchVisualizerWindow the keyWindow.
=> Fix keyWindow.rootViewController nullability on iOS

detox/src/devices/Device.js, detox/src/devices/Device.test.js, docs/APIRef.DetoxObjectAPI.md
---
Detox-CLI supports to reuse existing app for a faster test run. When using detox with Cucumber or other test runners, we can't run test cases with Detox-CLI.
This PR add a new parameter to `Detox.init()` method to support reusing programmatically.
```js
Detox.init(config, {reuse: true});
```
=> feat: specify resuing existing app in Detox.init() params

detox/local-cli/cli.js
Will wait for #1247 to be discussed
---
Exits with status code `1` when an actual error (not a `yargs` validation error) is passed to the `.fail` callback
=> Exit process with error status code when a cli command fails

detox/android/detox/build.gradle, detox/android/detox/proguard-rules-app.pro, detox/android/detox/proguard-rules.pro, detox/test/android/app/build.gradle, detox/test/android/app/proguard-rules.pro, docs/Introduction.Android.md
---
Add Proguard configuration in a two-fold way:
1. Enable minification in Android test app.
2. Add config scripts + documentation for apps running Detox over minified apps.
Fixes #1216
=> (Android) Introduce Proguard all-around

detox/android/detox/build.gradle, detox/android/detox/src/main/java/com/wix/detox/Detox.java, detox/android/detox/src/main/java/com/wix/detox/uiautomator/UiAutomator.java, generation/index.js
---
Fix #1235 - Migrate uiautomator to `androidx`' uiautomator, which was somehow left behind in the big `androidx` migrate we did a while ago.
=> (Android) Migrate UIAutomator to AndroidX (#1235)

detox/android/detox/build.gradle, detox/android/detox/src/main/java/com/wix/detox/Detox.java, detox/android/detox/src/main/java/com/wix/detox/uiautomator/UiAutomator.java
---
This PR migrates the uiautomator dependency from `com.android.support.test.uiautomator:uiautomator-v18:2.1.3` to `androidx.test.uiautomator:uiautomator:2.2.0`
=> Migrate uiautomator to AndroidX

detox/test/e2e/17.datePicker.test.js, detox/test/package.json, detox/test/src/Screens/DatePickerScreen.js
The recent contribution in February to `DatePickerIOS` functionality does not pass end-to-end tests locally due to a timezone issue.
The pull request removes timezone ambiguities between test code and example app code, so you don't need to switch to Los Angeles time locally to make the tests pass.
=> fix: e2e test on timezones different from LA

detox/local-cli/cli.js, detox/src/utils/logger.js
A hacky but efficient enough solution to prevent a bug introduced in `12.1.0` with the `yargs` transition.
Prevents appearance of `detox_<pid>.log` files in your current working directory if you don't specify explicitly `--artifacts-location` to the Detox CLI. It's very annoying and quickly pollutes the project folder.
Previously, those very short logs were not created at all in these cases, so we don't really lose much by suppressing them again. Later we can think on how to do better.
=> hotfix: redundant logs in the folder

detox/src/artifacts/ArtifactsManager.js, detox/src/artifacts/ArtifactsManager.test.js, detox/src/artifacts/__snapshots__/ArtifactsManager.test.js.snap, detox/src/artifacts/log/ios/SimulatorLogRecording.js
Currently, errors emerging inside artifacts manager and plugins are printed with `ERROR` priority which often confuses people that have a failing test due to other reasons and lead them in a wrong direction.
That's why it is reasonable to switch `log.error` to `log.warn` inside artifacts subsystem - in reality, we suppress the errors, not letting them impact the execution of test scenarios.
The issue was discussed with @LeoNatan.
=> code: lower status of artifact manager errors

detox/package.json, detox/src/artifacts/ArtifactsManager.js, detox/src/artifacts/ArtifactsManager.test.js, detox/src/artifacts/__snapshots__/ArtifactsManager.test.js.snap, detox/src/artifacts/log/ios/SimulatorLogPlugin.js, detox/src/artifacts/log/ios/SimulatorLogPlugin.test.js, detox/src/artifacts/log/ios/SimulatorLogRecording.js, detox/src/artifacts/templates/plugin/ArtifactPlugin.js, detox/src/artifacts/templates/plugin/ArtifactPlugin.test.js, detox/src/artifacts/templates/plugin/__snapshots__/ArtifactPlugin.test.js.snap, detox/src/devices/drivers/AndroidDriver.js, detox/src/devices/drivers/DeviceDriverBase.js, detox/src/devices/drivers/SimulatorDriver.js
The pull request has two improvements to the simulator log plugin:
Finally, I've found the reason for the weird `tail` + `SimulatorLogPlugin` integration errors we were experiencing for the last year:
https://github.com/lucagrulla/node-tail/blob/3791355a0ddcc5de72e1ad64ea2f0d6e78e2c9c5/src/tail.coffee#L102
So, we have a race condition here. At times, when the `SimulatorLogPlugin` tells its `stdout` and `stderr` tails to `unwatch()`, there is a delayed `setTimeout(() => this.watch(), 1000)` inside `tail`'s very own implementation which leads to unexpected issues:
1. It keeps emitting `line` events even after we unwatch the log and close the writeable stream.
2. It leaves CI hanging due to untracked `fs.watch` handle which is created by the library itself.
So, before we `tail.unwatch()`, it …
=> fix: stabilize simulator log plugin

detox/local-cli/test.js, detox/local-cli/test.test.js
The pull request, in its essence, is decorative, and its goal is to reduce the redundancy of the command line arguments passed to Mocha.
For example, if we run `detox test`, without specifying artifact recording options, previously it yielded:
> node_modules/.bin/mocha --opts e2e/mocha.opts --configuration android.emu.release --grep :ios: --invert --record-logs none --take-screenshots none --record-videos none  --artifacts-location "artifacts/android.emu.release.2019-04-15 04-54-07Z" "e2e" e2e/01.sanity.test.js
With this pull request, the command line arguments list passed to Mocha, becomes terser:
> node_modules/.bin/mocha --opts e2e/mocha.opts --configuration android.emu.release --grep :ios: --invert --artifacts-location "artifacts/android.emu.release.2019-04-15 04-54-07Z" "e2e" …
=> code: omit passing explicitly default command-line args to test runners

detox/local-cli/test.js, detox/local-cli/test.test.js, detox/src/artifacts/screenshot/ScreenshotArtifactPlugin.js, detox/src/artifacts/templates/plugin/TwoSnapshotsPerTestPlugin.js, docs/APIRef.Artifacts.md, docs/APIRef.DetoxCLI.md, docs/APIRef.DeviceObjectAPI.md
Resolves #1278.
---
Adds `--take-screenshot manual` mode, which is used by default from now on.
In `manual` mode, `device.takeScreenshot` is enabled as well, but `beforeEach.png` and `afterEach.png` screenshots are not being taken.
To have `device.takeScreenshot` API disabled forcibly, use `--take-screenshot none`.
=> feat: --take-screenshot manual mode by default

detox/src/devices/android/AAPT.js, detox/src/devices/android/ADB.js, detox/src/devices/android/ADB.test.js
---
Windows users with spaces in their APK path face an issue where the path is broken by spaces. I faced this issue and tried escaping the space, but it turned out the solution was to remove the backslash escapes I added and use quotation marks, like "path". Apostrophes like 'path' don't work.
For reference,
https://android.stackexchange.com/questions/185951/script-to-pull-from-directory-containing-spaces
This fixed the problem for me and I'm now able to run `detox build`.
I considered other places in the code where the path could be wrapped in quotes, but this seemed like the simplest and only place necessary.
=> fix(android): install APK with a file path that needs escaping

detox/local-cli/init.js
=> fix: append newline to package.json on detox init

docs/APIRef.DetoxCLI.md
Add missing - for --configuration and --gpu
---
Long option should be -- instead of - or else it will be error on parameter when run command
Reference: https://travis-ci.org/guhungry/react-native-photo-manipulator/jobs/520852289
=> docs(APIRef.DetoxCLI) fix: missing - for options

detox/local-cli/templates/jest.js, detox/package.json, detox/src/android/expect.test.js, detox/src/ios/expect.test.js, detox/test/e2e/config.json, detox/test/package.json, docs/Guide.Jest.md, examples/demo-react-native-jest/.babelrc, examples/demo-react-native-jest/e2e/config.json, examples/demo-react-native-jest/package.json, generation/package.json
---
The motivation is that since Jest 24 `setupTestFrameworkScriptFile` is deprecated, and `setupFilesAfterEnv` should be used instead.
Recently, @cs01 suggested his changes in pull request #1162 (and closed it, unfortunately), so the idea of this pull request is to refine it and extend to all the affected places in Detox codebase.
In the pull request, I've bumped Jest to `24` in every project it is required and made sure to fix all the warnings I've stumbled across.
=> fix: upgrade configs for Jest 24

detox/src/devices/ios/AppleSimUtils.js
---
If passing a URL such as `https://testt.com/go/?screen=BehaviorLessons&behaviorKey=helpful` to `device.launchApp` the `&behaviorKey` URL parameter would not be passed on to the app. This PR fixes that.
Thanks to @LeoNatan for this fix.
=> Fix for supporting multiple URL arguments for device.launchApp

examples/demo-react-native/package.json, scripts/demo-projects.ios.sh
---
Makes `scripts/demo-projects.android.sh` pass and enables us to set up another Jenkins job for the demo projects (specifically for Android)
=> ci(android): fix demo-react-native project

docs/APIRef.ActionsOnElement.md
---
`startPositionX -> startPositionY`
```diff
- startPositionX - The Y starting scroll position, in percentage; valid input: (0.0, 1.0), `NaN`; default: `NaN`—Choose the best value<br>
+ startPositionY - The Y starting scroll position, in percentage; valid input: (0.0, 1.0), `NaN`; default: `NaN`—Choose the best value<br>
```
=> Fix `startPositionY ` typo

.gitignore, detox/android/build.gradle, detox/android/detox/build.gradle, detox/android/detox/detox-publishing.gradle
Introduce maven publishing for Android: Packaging of artifacts into a predefined @root folder, that's accessible in end-projects using the detox library.
This is the first step in introducing the entire feature (see issue #1323), which would include:
1. Migrating the example projects to using .aar, all-the-while integrating them into the CI as downstream builds.
2. Actual invocation of the packaging in the publishing flow in CI (so that the .arr's etc will be published to npm).
=> (Android) Introduce android build-artifacts' packaging (.aar, source, docs)

examples/demo-react-native-jest/e2e/init.js, examples/demo-react-native/e2e/mocha.opts, examples/demo-react-native/e2eExplicitRequire/mocha.opts, scripts/demo-projects.android.sh
Description:
This is one of the preliminaries for issue #1323: As Android arfiacts' packaging is available, we need to integrate their usage onto the CI. Hence the example projects' tests run.
Still needed to follow: same for iOS.
=> (Android) Restore example project tests in CI (context: issue #1323)

examples/demo-react-native-jest/android/app/build.gradle, examples/demo-react-native-jest/android/app/proguard-rules.pro, examples/demo-react-native-jest/android/build.gradle, examples/demo-react-native-jest/android/settings.gradle, examples/demo-react-native/android/app/build.gradle, examples/demo-react-native/android/app/proguard-rules.pro, examples/demo-react-native/android/build.gradle, examples/demo-react-native/android/settings.gradle, examples/demo-react-native/package.json, scripts/ci.android.sh, scripts/demo-projects.android.sh
Integrate detox packaging and usage of the artifact (i.e. `aar` file) into the android example projects.
Yet another step underway to resolving #1323 .
=> (Android) Switch example projects to use .aar

detox/src/artifacts/instruments/SimulatorInstrumentsPlugin.js, docs/APIRef.Artifacts.md
---
To enable using Detox on CI agents where it is not easily possible to install Detox Instruments in a default location `/Applications/Detox Instruments.app`, here we add a way to define the default path via environment variable:
```bash
DETOX_INSTRUMENTS_PATH="/path/to/Detox Instruments.app" detox test ...
```
@rotemmiz, please review.
=> feat: support for DETOX_INSTRUMENTS_PATH environment variable

detox/src/artifacts/templates/artifact/Artifact.js, detox/src/artifacts/templates/artifact/Artifact.test.js
---
Instead of red error lines in the log, Detox will be printing warnings — to not confuse the users who might attribute the "errors" to a cause of why their tests are failing.
=> code: print a warning instead of an error if artifact files are not found

detox/src/artifacts/instruments/SimulatorInstrumentsPlugin.js, detox/src/artifacts/instruments/SimulatorInstrumentsRecording.js, detox/src/artifacts/templates/artifact/Artifact.js, docs/APIRef.Artifacts.md
---
To enable using Detox on CI agents where it is not easily possible to install Detox Instruments in a default location `/Applications/Detox Instruments.app`, here we add a way to define the default path via environment variable:
```bash
DETOX_INSTRUMENTS_PATH="/path/to/Detox Instruments.app" detox test ...
```
=> feat: DETOX_INSTRUMENTS_PATH environment variable

detox/test/e2e/init.js
---
1. The code in `detox/test/e2e/init.js`, inside `before` statement is historically inherited from my workaround to Jest issues (buffered console logs) which are being addressed in @d4vidi's PR #1351.
2. Moreover, currently, we don't use Jest in the e2e test suite, but Mocha. The code there is not relevant.
3. There's even more to it. Given `try {} catch {}` statement performs a redundant `detox.cleanup()`. Why? If you check the code of `detox.init()` implementation, it already has `try {} catch { cleanup() }` logic, so this is obviously extraneous.
=> test: remove jest workaround in e2e

detox/test/package.json
---
Currently, `eslint` takes `.eslintrc` configuration from the parent project - `detox`. And there is a `node` preset there:
https://github.com/wix/Detox/blob/bb61030b68986ddd3f3265ba8c76c54597ea5957/detox/.eslintrc#L1-L3
It takes into consideration a field (`engines.node`) in `package.json`, so to get rid of lint warnings in `detox/test` project, I specify this non-harmful property explicitly.
=> lint: fix intellisense warning

detox/src/index.js, detox/src/index.test.js
---
There's no sense to do the same cleanup twice on the same detox object instance, so why not set it to `null` after the cleanup?
=> fix: ensure cleanup cannot be called twice

detox/android/detox/build.gradle, docs/Introduction.Android.md
With respect to 29b7b44c, which seems to have potentially broken detox-compiling projects -- this ought to fix it by restoring `detoxKotlinVersion`.
=> (Android) Revisit kotlin stdlib issue fix for projects compiling detox

detox/local-cli/rebuild-framework-cache.js
In most cases, `clean-framework-cache` and `build-framework-cache` are called together. This PR adds `rebuild-framework-cache` to local CLI so that these two steps are easier to accomplish.
Right now, it doesn't replace the existing ones. I don't think `clean-framework-cache` should be removed, but `build-framework-cache` may be unnecessary.
One caveat here is that `rebuild-framework-cache` cleans all cache but only builds for the current Detox. Not sure how bad this is, considering the use-cases.
=> Add rebuild-framework-cache command to local CLI

detox/ios/Detox/DetoxManager.h, detox/ios/Detox/DetoxManager.m, detox/ios/Detox/TestFailureHandler.m, detox/ios/Detox/WebSocket.h, detox/ios/Detox/WebSocket.m
Until now, there was no retry mechanism on iOS. If the app was launched before the Detox server, it would never connect, requiring a further relaunch.
The new mechanism will retry connecting once every second if the server is unavailable, or if the server dropped connection.
=> Web Socket Connection Retry

detox/android/detox/build.gradle
Fixes #1380 and similar problems in some projects that _compile_ Detox, typically running RN-59, maybe 58.
This explains the fix in a nutshell:
- Using gradle's `+` wildcard for auto version resolution - which in facts yields the _newest available version_, works for react native as a dep, because RN gets resolved strictly from the synthetic `node_modules/react-native/android` "repo". The "newest" version is simply the one that's installed there.
- This isn't the case for `okhttp` and `okio`, which are found at the `google` and/or `jcenter` repos. In the current setting, that basically gives Detox the mandate to claim it relies on new, perhaps incompatible versions (e.g. `okhttp` 4), while really it can work with anything not too old.
Luckily, `okhttp` and `okio` …
=> Cancel explicit deps in okio and okhttp

detox/src/artifacts/instruments/SimulatorInstrumentsPlugin.js
Removed triggering of instruments recording  (--record-performance) for apps launched in before/beforeApp scopes
```js
before(async () => {
await device.launchApp({newInstance: true, permissions: {notifications: 'YES'}});
});
```
In that case, the beforeEach scope handles starting of a recording on an already launched app, and instruments will crash on an invalid state.
```
Suppressed error inside function call: SimulatorInstrumentsPlugin.onBeforeEach({ title: 'Launch logged in app from dead state',
fullName:
'Open installed app - logged in Launch logged in app from dead state',
status: 'running' })
err: A recording is already in progress
(
0   CoreFoundation                      0x00000001101421bb __exceptionPreprocess + 331
1   libobjc.A.dylib …
```
=> Removed triggering of instruments recording  (--record-performance) for apps launched in before/beforeApp scopes

detox/test/e2e/19.crash-handling.test.js
Currently, crash e2e's start by reloading RN instead of restarting from scratch. This means the test doesn't really begin fresh, from scratch - as some native state properties can leak in. Not just theoretical -- on Android, this made the app load inside a different activity that's related to url launch checking (previous test was urls related).
=> Make crash e2e more stable

detox/src/devices/drivers/SimulatorDriver.js, detox/src/devices/drivers/SimulatorDriver.test.js, detox/src/devices/ios/AppleSimUtils.js
---
This is a hotfix for https://github.com/wix/Detox/pull/1385.
There is a not very obvious logic in `SimulatorInstrumentsPlugin` that mutates `launchArgs` in order to be able to launch the app with Detox Instruments recording enabled from the very beginning. Also, it can specify `detoxInstrumentsPath` via that specific mutation.
This particular oversight had two implications:
1. You can’t override Detox Instruments Path when launching an app.
2. And you can’t collect profiling if you launch an app inside `it()`.
This fix moves all the command-line argument manipulation logic of launchApp to `AppleSimUtils` class.
=> fix: include launch args that come from artifact plugin

detox/local-cli/init.js
1. Remove redundant PREFIX in logs, because `require('../src/utils/logger').child({ __filename });` already gives the logger a prefix.
2. As @d4vidi suggested in his PR #1351, to explicitly specify `runner-config` field in package.json (and that's an additional parameter to a scaffolding function), so to be on the safe side, I refactored `patchDetoxConfigInPackageJSON` function to accept named parameters (via destructuring). As a result, we have here a more generic `loggedSet` instead of a crafted-once log message.
3. `createFolder` log message has been fixed (interpolated `${dir}` instead of a constant `./e2e`).
4. `createFolder` won't throw an unhandled exception if creating a folder fails - instead, it will log an error with an explanation and go to the next step. 
5. …
=> code: logging fixes in detox init

detox/test/e2e/15.urls.test.js, detox/test/e2e/19.crash-handling.test.js
This reimplements commit 3e9688dadf6650bb0618178b42e5a5d89f390f27
Instead of relaunching prior to crash handling, relaunch in url tests' `afterAll()` to make solution more generic.
No actual review required, CI results will set the tone here.
=> Reimplement crash-e2e stabilization

detox/android/build.gradle, detox/android/detox/build.gradle, detox/android/gradle/wrapper/gradle-wrapper.properties, detox/package.json, detox/test/android/app/build.gradle, detox/test/android/app/src/androidTest/java/com/example/DetoxTest.java, detox/test/android/app/src/main/AndroidManifest.xml, detox/test/android/app/src/main/java/com/example/MainApplication.java, detox/test/android/build.gradle, detox/test/android/gradle.properties, detox/test/android/gradle/wrapper/gradle-wrapper.properties, detox/test/e2e/03.actions.test.js, detox/test/e2e/03.fs-scroll-actions.test.js, detox/test/e2e/05.waitfor.test.js, detox/test/e2e/utils/custom-it.js, detox/test/e2e/utils/rn-consts.js, detox/test/package.json, detox/test/src/Screens/ScrollActionsScreen.js, detox/test/src/Screens/index.js, detox/test/src/app.js, scripts/ci.android.sh, scripts/demo-projects.android.sh
> Replaces PR #1416
Introduce required changes in order to have our demo app test suite successfully run on Android (with the necessary restrictions introduced by the RN issue).
- Documentation will follow.
- We nevertheless have to upgrade our visibility matcher in order to work around the RN issue, even though it's far from trivial.
- This does not include an upgrade to the example projects.
=> Restricted support in RN .59

detox/src/artifacts/log/LogArtifactPlugin.js, detox/src/artifacts/log/ios/SimulatorLogPlugin.js, detox/src/artifacts/log/ios/SimulatorLogPlugin.test.js, detox/src/artifacts/log/ios/SimulatorLogRecording.js, detox/src/devices/ios/AppleSimUtils.js, detox/src/utils/exec.js, detox/src/utils/exec.test.js
The existing `SimulatorLogPlugin` implementation appears to be **not informative** (does not include various NSLog messages, etc) and **hacky** (relies on tailing two temporary files which contain piped output from a simulator launched in a special way).
The suggested reimplementation is based on two extra commands:
```
/usr/bin/xcrun simctl spawn ${udid} log stream --level debug --style compact --predicate '${predicate}
```
, where the predicate is built via:
```
/usr/bin/xcrun simctl get_app_container ${udid} ${bundleId}
```
and looks like:
```
processImagePath beginsWith "${appContainer}"
```
Ultimately, the plugin now is able to produce logs like these:
```
2019-06-04 14:01:49.918 E  example[59318:22c78e] [com.wix.Detox:DetoxManager] Web socket failed to connect with …
```
=> Reimplemented SimulatorLogPlugin to use log stream

docs/Guide.Contributing.md
---
This PR adds missing info in docs on how to run example projects after https://github.com/wix/Detox/commit/331f517328d7ee3ad86406891e0d839da64f4c83 and https://github.com/wix/Detox/commit/9bd9edcc1f211e307947ce1d3e682bc71a846f87 .
=> docs: info on contributing to example projects

detox/src/artifacts/ArtifactsManager.js, detox/src/artifacts/log/LogArtifactPlugin.js, detox/src/artifacts/log/android/ADBLogcatPlugin.js, detox/src/artifacts/log/android/ADBLogcatRecording.js, detox/src/artifacts/log/ios/SimulatorLogPlugin.js, detox/src/artifacts/log/ios/SimulatorLogRecording.js, detox/src/artifacts/templates/plugin/ArtifactPlugin.js, detox/src/artifacts/templates/plugin/StartupAndTestRecorderPlugin.js, detox/src/artifacts/templates/plugin/StartupAndTestRecorderPlugin.test.js
This issue popped up when we tried to debug why `*.dtxrec` are not being recorded on CI.
This PR addresses some of them, specifically:
1) the log plugin starts recording first and ends recording last (`priority` field);
2) the log plugin for iOS gracefully terminates the spawned logging process (to save more logs);
3) the log plugin for Android requests logs from a more correct timestamp (either from "before the app was launched" or "before the last recording was stopped").
4) to reflect the recent `process.log` naming, Android log plugin will not record logs if no PID is specified.
=> fix(artifacts): more precise log recording on iOS and Android

detox/src/devices/ios/AppleSimUtils.js
---
fixes usage with newest applesimutils https://github.com/wix/AppleSimulatorUtils/releases
tested in CI
before:
```
detox[15997] INFO:  [DetoxServer.js] server listening on localhost:52500...
detox[15997] ERROR: [exec.js/EXEC_FAIL, #6] "applesimutils --simulator 14B76F33-6E7F-4F0F-9079-B75A57BD0B41 --bundle com.some.company--restartSB --setPermissions notifications=YES" failed with code = 253, stdout and stderr:
detox[15997] ERROR: [exec.js/EXEC_FAIL, #6] A collection of utils for Apple simulators.
Usage Examples:
applesimutils --byId <simulator identifier> --bundle <bundle identifier> --setPermissions "<permission1>, <permission2>, ..."
applesimutils --byName <simulator name> --byOS <simulator OS version> --bundle <bundle identifier> --setPermissions "<permission1>, …
```
=> use --byId instead of --simulator

detox/src/devices/android/ADB.js, detox/src/devices/android/ADB.test.js, detox/src/devices/ios/AppleSimUtils.js, detox/src/utils/__snapshots__/exec.test.js.snap, detox/src/utils/exec.js, detox/src/utils/exec.test.js
---
Since we don't know what the root cause is for the sporadic failures of #1427, for now we'll have to settle on getting more info. With this PR, we'll `debug`-log the result of each `adb devices` instead of just `trace`-ing it. This will give us high visibility the next time this happens.
=> Increase log-level for result of 'adb devices' command

detox/src/client/Client.test.js, detox/src/client/actions/actions.js, detox/src/server/DetoxServer.js, detox/test/e2e/23.flows.test.js
=> fix: conduct cleanup even if app has been already terminated

detox/src/server/DetoxServer.js
Fixes the issue we began getting after bumping `ws` to `^3.3.1`.
---
Private builds on TeamCity began failing with unhandled `read ECONNRESET` error in logs, and the domino effect led to failures in consequent tests.
To my great displeasure, I could not reproduce it consistently in Detox e2e suite, but the fix has been verified locally on the private build.
More details here: https://github.com/websockets/ws/issues/1256
=> fix(ws): explicit error handling

docs/Guide.Mocking.md
Updating Guide.Mocking with Metro breaking changes
=> Updating Guide.Mocking with Metro breaking changes

detox/scripts/postinstall.js
Resolves #1338
@rotemmiz, what's your opinion on that issue? I understand what problem they might have and indeed there's no other solution so far as I am concerned - that's because `npm install` is not really flexible, and there is a goal to speed up some builds on @haswalt's CI, we should support that from our codebase.
=> feat: allow disabling of post install with env var

detox/android/detox/src/main/java/com/wix/detox/espresso/DetoxAssertion.java, detox/android/detox/src/main/java/com/wix/detox/espresso/DetoxMatcher.java, detox/android/detox/src/main/java/com/wix/detox/espresso/assertion/ViewAssertions.java, detox/android/detox/src/main/java/com/wix/detox/espresso/matcher/NullableTypeSafeMatcher.java, detox/android/detox/src/main/java/com/wix/detox/espresso/matcher/ViewAtIndexMatcher.kt, detox/android/detox/src/main/java/com/wix/detox/espresso/matcher/ViewMatchers.kt, detox/src/android/expect.js, detox/test/e2e/05.waitfor.test.js
---
Bottom line is - this fixes #1463. Effectively, however, in order to do so, it introduces an essential (mini) overhaul in the way view matching works on Android.
A typical (native) Espresso matching test-code looks like this:
```java
onView(withId(R.id.viewId)).check(matches(isDisplayed()))
```
Or to be on the accurate side, since in Detox we don't use native ID's - but testID's, the code should actually like this:
```java
onView(matcherForTestId('someJSElement')).check(matches(isDisplayed())
```
But when trying to compose an equivalent assertion to represent the `waitFor` API (e.g. `waitFor(element(...)).toBeVisible().withTimeout()`), what we accidentally had created, was this:
```java
onView(allOf(matcherForTestId('someJSElement'), isDisplayed())).check(matches(isDisplayed())
``` …
=> (Android) Fix a unidentified non-visibility matching when using waitFor()

detox/runners/jest/DetoxJestAdapter.js, detox/runners/mocha/DetoxMochaAdapter.js, detox/src/Detox.js, detox/src/Detox.test.js, detox/src/client/AsyncWebSocket.js, detox/src/client/AsyncWebSocket.test.js, detox/src/client/Client.js, detox/src/client/Client.test.js, detox/src/client/__snapshots__/Client.test.js.snap
Currently, it is not easy to track what requests to `testee` have never been resolved, leading to timeout errors in tests.
To make it Detox debug-friendly in those cases, I suggest dumping pending network requests if:
1. a test has failed with a timeout (mocha offers this as an API, in Jest I scan for timeouts in failed expectations)
2. in `detox.cleanup()`, before we clean up the client.
Although it does not cover all the cases (e.g. cannot catch infinite `detox._client.cleanup()` but looks like a good start IMO.
=> feat(log): dump pending network requests on test timeout

detox/android/detox/src/main/java/com/wix/detox/espresso/scroll/ScrollHelper.java, detox/test/e2e/03.scroll-actions.test.js, detox/test/e2e/03.visibility-workaround-actions.test.js, detox/test/e2e/drivers/fs-scroll-driver.js, detox/test/src/Screens/ScrollActionsScreen.js
---
Fix #1485. The core here is to wait until all scroll-view children leave the on-press state, which becomes in-effect since, presumably, the parent scroll-view is pressed-on and it propagates it to the children (see `ViewGroup`'s impl of `dispatchSetPressed()`). This adds up to 3 lines, really.
The fix was taken from Espresso's original implementation -- much like Detox's entire implementation of scrolling, except that is was probably "lost in translation" beforehand.
=> (Android) Fix issue with taps being ignored if made right after scrolling

detox/ios/Detox.xcodeproj/project.pbxproj, detox/ios/Detox/DetoxAppDelegateProxy.m, detox/ios/Detox/DetoxUserNotificationDispatcher.swift, detox/ios/DetoxUserNotificationTests/DetoxUserNotificationTests.swift, detox/ios/DetoxUserNotificationTests/TestableAppDelegate.swift, detox/ios/DetoxUserNotificationTests/UNApiAppDelegate.swift, detox/test/ios/example.xcodeproj/xcshareddata/xcschemes/example.xcscheme, detox/test/ios/example/AppDelegate.m
Move sample app to use UN API, rather than legacy API
Drop usage of terribly outdated RCTPushNotificationManager
Closes #1509
=> Call userNotificationCenter:willPresentNotification:withCompletionHandler: as part of user notification sending to active apps

detox/local-cli/test.js, docs/Guide.ParallelTestExecution.md
---
when running detox test, the devices lock file is removed, detox test -keepsimlock will not delete the lock file.
it will be manually managed.
=> Add option to keep simulator lock file to cli

docs/Introduction.GettingStarted.md
---
As mentioned in [the React Native 0.60 announcement blog post](https://facebook.github.io/react-native/blog/2019/07/03/version-60#cocoapods-by-default), React Native now uses Cocoapods, and therefore `.xcworkspace` files, by default.
To make the Getting Started instructions easier for users who aren't familiar with Cocoapods, this PR explicitly says that the `-workspace` option is needed for React Native 0.60 and above.
I've confirmed in [a tutorial project](https://github.com/learn-tdd-in/react-native) that in RN 0.60 Detox does not work with the `-project` flag but does work with this change applied.
=> Add explicit note about React Native 0.60 and workspace

detox/ios/Detox.xcodeproj/project.pbxproj, detox/ios/Detox/DTXAddressInfo.h, detox/ios/Detox/DTXAddressInfo.mm, detox/ios/Detox/Detox.pch, detox/ios/Detox/DetoxAppDelegateProxy.h, detox/ios/Detox/DetoxAppDelegateProxy.m, detox/ios/Detox/DetoxManager.m, detox/test/ios/example.xcodeproj/xcshareddata/xcschemes/example.xcscheme
Instead, swizzle the `UIApplication` delegate accessor to do magic and provide a proxy delegate to UIKit/UIKitCore, while still returning the user app delegate when user code requests it.
Fixes #1525
=> Move away from swizzling the app delegate

detox/src/devices/Device.js, detox/src/devices/Device.test.js, detox/src/devices/drivers/DeviceDriverBase.js, detox/src/devices/drivers/SimulatorDriver.js, detox/src/devices/drivers/SimulatorDriver.test.js, detox/src/devices/ios/AppleSimUtils.js, docs/APIRef.DeviceObjectAPI.md
This is a small change (which was requested in #958).
It adds support for Biometrics by adding the following methods to DeviceDriver:
- `enrollBiometrics` and `disenrollBiometrics` - for setting up biometrics on a Simulator
- `matchFace` and `unmatchFace` - for matching a face on a Simulator
- `matchFinger` and `unmatchFinger` - for matching a finger on a Simulator
It uses an underlying call in `AppleSimUtils.js` to three new methods:
- `setBiometricEnrollment` - which accepts a UDID and either `"YES"` or `"NO"`
- `matchBiometric` - which accepts a UDID and either `"Face"` or `"Finger"`
- `unmatchBiometric` - which accepts a UDID and either `"Face"` or `"Finger"`
I believe I added the appropriate tests so I think this should be good to go - however, I'm happy to change if …
=> Add Support for Biometrics on SimulatorDriver

detox/android/detox/src/main/java/com/wix/detox/espresso/DetoxViewActions.java, detox/android/detox/src/main/java/com/wix/detox/espresso/action/DetoxTypeTextAction.java, detox/android/detox/src/main/java/com/wix/detox/espresso/action/RNClickAction.java, detox/src/android/espressoapi/DetoxViewActions.js, detox/src/android/expect.js, detox/test/android/app/src/main/java/com/example/NativeModule.java, detox/test/e2e/03.actions.test.js, detox/test/src/Screens/ActionsScreen.js, detox/test/src/Views/TextInput.js
---
Fix #1462 by replacing Espresso's implementation of `typeText()` with a custom one that manages the pre-tap in a way that is safe for RN apps (just like detox does for standard clicks).
As a side note, the challenge here was not in fixing the issue (except for researching it), but in having associated use cases tested. This isn't trivial since `TextInput` components cannot be set a long-press callback from the JS side.
=> (Android) Fix undesired turning of typeText() taps into long taps over InputText components

detox/src/devices/android/Emulator.js
---
Fixes #1546 by indirectly switching to `fs.watchFile()` instead of `fs.watch()`, which uses polling and seems to be more stable throughout node.js versions (ref for why `fs.watch()` is unstable: https://github.com/nodejs/node/issues/28882).
=> Fix test runner's hang when spawning Android emulators by new node.js versions (>=10.16.0)

detox/android/detox/src/main/java/com/wix/detox/espresso/scroll/ScrollHelper.java
---
Fixes regression of issue initially described in #1485.
=> Improve robustness of scroller by increasing initial post-scrolling idle lookahead window

detox/src/devices/ios/AppleSimUtils.js
- The matchBiometric and unmatchBiometric commands failed because of an incorrect parenthesis.
- The correct commands are --matchFace or --matchFinger, see https://github.com/wix/AppleSimulatorUtils
The biometrics functionality was introduced with https://github.com/wix/Detox/pull/1554 and https://github.com/wix/Detox/pull/1547
---
Using the biometrics commands caused errors on my computer. I fixed them with this PR.
Fyi, using `await device.matchFinger();` still fails on my computer with the timeout below. I could not yet find the reason why. There may be additional errors that need fixing.
```
1) with his matching finger
detox[71526] WARN:  [Client.js/PENDING_REQUESTS] App has not responded to the network requests below:
(id = 12) waitForBackground: {}
That might be the …
```
=> Fix matchBiometric and unmatchBiometric commands

detox/ios/Detox/GREYActions+Detox.m
=> Move cursor to the end of the text elements before clearText()

detox/src/devices/android/ADB.js, detox/src/devices/drivers/AndroidDriver.js, detox/src/devices/drivers/AndroidDriver.test.js
---
This PR addresses 2 things for testing on android devices:
- Automatic reverse port forwarding for `DetoxServer` to connect back to the host machine. Relevant issues: #1174 #1200 #968 
- Screen unlocking from `'Dozing'` state
=> fix(attached-android): reverse port forwarding, and screen unlocking

detox/src/devices/Device.js
- [x ] This is a small change 
Attempting to match biometrics always times out. These functions call 'waitForBackground' which is unnecessary as far as I can tell. The app does not background after matching a face or finger and this causes the test to always time out.
I believe there is still an issue with biometrics where `waitForActive` will always time out when a Face ID or Touch ID dialog is opened upon app launch. However that may be a broader issue.
=> Fix biometric matching timeout

detox/.npmignore
Just small extension of npmignore, to save npm traffic and npminstall time.
=> chore(npmignore): exclude extra files in npm package

detox/android/detox/src/main/java/com/wix/detox/ReactNativeSupport.java
- [ x] This is a small change 
If you are trying to set-up Detox in your app and there is a proguard misconfiguration then this usage of reflection may fail and it will be silent. If this log were here, it would have been a huge clue that would have saved me from having to manually debug Detox to find this thrown exception.
=> Log reflection errors from looper introspection

detox/android/build.gradle, detox/android/gradle.properties, detox/android/gradle/wrapper/gradle-wrapper.properties, detox/test/android/build.gradle, detox/test/android/gradle.properties, detox/test/android/gradle/wrapper/gradle-wrapper.properties, examples/demo-native-android/build.gradle, examples/demo-native-android/gradle.properties, examples/demo-native-android/gradle/wrapper/gradle-wrapper.properties, examples/demo-react-native/android/build.gradle, examples/demo-react-native/android/gradle.properties, examples/demo-react-native/android/gradle/wrapper/gradle-wrapper.properties
---
Upgrade Gradle to `5.1.1` and the Android gradle-plugin to equivalent version `3.4.1` in all demo apps. Biggest motivation for doing this is the [HTTP retries](https://docs.gradle.org/5.0/release-notes.html#http-retries-during-dependency-resolution) feature.
Disclaimer: the feature may not be fully functional as described [in this report to gradle](https://github.com/gradle/gradle/issues/8264). I hope it'd be ok for us nevertheless.
=> Upgrade Gradle to 5.1.1

detox/android/detox/src/main/java/com/wix/detox/espresso/scroll/ScrollHelper.java, detox/test/e2e/03.integ-actions.test.js, detox/test/e2e/drivers/integ-actions-drivers.js
---
Improves native-scrolling accuracy (Android), in terms of how close the effective scrolling will be on the device, compared to the scrolling amount provided in DIP in Detox tests.
As a result, it should stabilize currently flaky integration-actions tests that involve intense scrolling scenarios.
=> Improve overall accuracy of native android scrolling

detox/android/detox/src/main/java/com/wix/detox/espresso/DetoxAction.java, detox/android/detox/src/main/java/com/wix/detox/espresso/scroll/ScrollHelper.java, detox/src/android/espressoapi/DetoxAction.js, detox/src/android/expect.js, detox/test/e2e/03.actions.test.js, detox/test/src/Screens/ActionsScreen.js
---
Adds support for `scroll()`'s `startPosition[XY]` params on Android - [docs ref](https://github.com/wix/Detox/blob/master/docs/APIRef.ActionsOnElement.md#scrollpixels-direction-startpositionxnan-startpositionynan).
Effectively, this should fix #1593.
=> Scroll start position android

detox/local-cli/test.js, detox/local-cli/test.test.js, detox/src/devices/android/Emulator.js, detox/src/devices/drivers/SimulatorDriver.js, detox/src/devices/ios/AppleSimUtils.js, docs/APIRef.DetoxCLI.md
Resolves #1669.
---
Allows users to provide custom args in CLI that would be passed-through onto the device (Android emulator / iOS simulator) when (if) launched by Detox.
@swabbass @silyevsk
=> feat: --device-launch-args passthrough parameter

detox/local-cli/test.js, detox/local-cli/test.test.js
Jest allows percent values for `--maxWorkers`.
This is a small change to allow this same behavior.
Currently `--workers 100%` will become `--maxWorkers NaN`
I added some tests but I believe the naming should be reviewed
=> fix(jest): allow passing --maxWorkers as a percent value

docs/Guide.Mocking.md
---
The two scenarios for the different React Native version ranges misses 0.59. This corrects the latter range.
=> Corrects React Native version specifier in Mocking

detox/src/devices/DeviceRegistry.js, detox/src/devices/DeviceRegistry.test.js, detox/src/devices/android/ADB.js, detox/src/devices/android/ADB.test.js, detox/src/devices/drivers/AndroidDriver.js, detox/src/devices/drivers/AttachedAndroidDriver.js, detox/src/devices/drivers/EmulatorDriver.js, detox/src/devices/drivers/SimulatorDriver.js, detox/src/devices/ios/AppleSimUtils.js, detox/src/devices/ios/applesimutils.mock.json, detox/src/utils/ExclusiveLockfile.js, detox/src/utils/ExclusiveLockfile.test.js, detox/src/utils/argparse.js, detox/src/utils/argparse.test.js, detox/src/utils/safeAsync.js, detox/src/utils/safeAsync.test.js
This pull request prepares the ground to finally deal with #853 and also should potentially resolve #1565. 
The consequent PR will add `device` property to a configuration, which can be configured in a more powerful way.
**Changes:**
1. **AppleSimUtils**: make it thinner and more explicit, therefore the search method is called now `list` (similar to the CLI). The query handler logic (`iPhone X, iOS 12.0`) is moved 1 layer upwards, to SimulatorDriver.
2. **SimulatorDriver**: logic of search remains intact - device type (+ device os, if specified via comma).
3. **AppleSimUtils**: remove the dependency on a heavy and non-maintainable direct call `xcrun simctl list -j`, by allowing `new AppleSimUtils().create(device)` to accept a "prototype" for a device you want to create. I pick it from the …
=> refactor: device selection revisited

detox/local-cli/init.js
init now exits and sets an error status of 1 if it can't compelte a
task. This prevents it from overwrite `package.json`.
---
There are two ways to close #1692:
1. to test the returned object representing the package is defined, or
2. fail fast at the point where the package raises a `SyntaxError`.
I'd suggest 2, but am more than happy to implement 1 as it has the fewest number of changes.  Dealers choice.
=> fix(init) exits on error before erasing package.json

detox/src/devices/Device.js, detox/src/devices/Device.test.js, detox/src/devices/drivers/DeviceDriverBase.js, detox/src/devices/drivers/SimulatorDriver.js, detox/src/devices/ios/AppleSimUtils.js, docs/APIRef.DeviceObjectAPI.md
---
Adds the ability to delete the iOS Keychain by adding `clearKeychain` to `Device`.
I opted to not add a new e2e test as a dependency would need to be added, but will if you guys think it's needed.
=> feat(ios): add method device.clearKeychain()

detox/src/DetoxExportWrapper.js, detox/src/configuration.js, detox/src/configurations.mock.js, detox/src/devices/Device.js, detox/src/devices/Device.test.js, detox/src/devices/drivers/AttachedAndroidDriver.js, detox/src/devices/drivers/DeviceDriverBase.js, detox/src/devices/drivers/EmulatorDriver.js, detox/src/devices/drivers/SimulatorDriver.js, detox/src/devices/drivers/SimulatorDriver.test.js, detox/src/index.test.js, detox/test/package.json, docs/APIRef.Configuration.md, docs/Guide.DebuggingInXcode.md, docs/Guide.Migration.md, docs/Guide.RunningOnCI.md, docs/Introduction.Android.md, docs/Introduction.GettingStarted.md, docs/More.AndroidSupportStatus.md, examples/demo-react-native-jest/package.json, examples/demo-react-native/package.json
Resolves #853 (to query a simulator specifically by name, use appropriately):
```
"device": { name: "Simulator name" }
```
It is recommended to change `"name"` string to `"device"` object in your configurations, like shown below:
Before:
```json
{
"ios.sim.debug": {
"type": "ios.simulator",
"name": "iPhone 11 Pro"
},
"android.emu.release": {
"type": "android.emulator",
"name": "Nexus_5X_API_29"
},
"android.att.release": {
"type": "android.attached",
"name": "YOGAA1BBB412"
}
}
```
After:
```js
{
"ios.sim.debug": {
"type": "ios.simulator",
"device": { // one of these or a combination of them
"id": "D53474CF-7DD1-4673-8517-E75DAD6C34D6",
"type": "iPhone 11 Pro",
"name": "MySim",
"os": "iOS 13.0",
}
},
"android.emu.release": {
"type": "android.emulator",
"device": { // only avdName is …
```
=> feat(configuration): name string -> device object

detox/ios/Detox/WXJSTimerObservationIdlingResource.m
The API for createTimer has changed in react native master branch. 
See relevant change: https://github.com/facebook/react-native/commit/2b5f4de7eb4e5453e91d4956bcb0f58fe37b6562
Due to this change, Detox seems to crash.
The stack trace appears like this:
```
Signal 11 was raised
(
0   Detox                               0x000000010cf38b36 _ZL16__DTXHandleCrashP11NSExceptionP8NSNumberP8NSString + 497
1   Detox                               0x000000010cf388bb _ZL17__DTXHandleSignali + 61
2   libsystem_platform.dylib            0x0000000116f52b5d _sigtramp + 29
3   ???                                 0x0000000000000000 0x0 + 0
4   CoreFoundation                      0x0000000110b544cc __invoking___ + 140
5   CoreFoundation                      0x0000000110b51a45 …
```
=> Avoid crash due to iOS createTimer API change

detox/src/devices/drivers/SimulatorDriver.js
Fixed non-optimal performance on multiple simulator boot, while every worker performed the boot inside the critical section, causing all the others to wait for it.
This fix moves everything besides the acquiring of devide udid outside the critical section.
=> iOS: Move boot + bootstatus from critical section. 

detox/android/build.gradle, detox/android/detox/build.gradle, detox/android/gradle/wrapper/gradle-wrapper.properties, detox/test/android/app/build.gradle, detox/test/android/build.gradle, detox/test/android/gradle/wrapper/gradle-wrapper.properties, examples/demo-react-native/android/app/build.gradle, examples/demo-react-native/android/build.gradle, examples/demo-react-native/android/gradle/wrapper/gradle-wrapper.properties
Upgrade example/test-apps' target SDK to 29 (i.e. android 10) and various dep's versions to the latest available (e.g. android's test runner, Gradle and even Espresso).
---
*Note: avoided an upgrade of the Android Gradle plugin to 3.5+ (3.5.2 currently) as it has been found to break the build on CI (and not locally) due to problems in evaluating RN's ReactAndroid build script. More specifically:*
```
12:02:24 * What went wrong:
12:02:24 A problem occurred evaluating project ':ReactAndroid'.
12:02:24 > extensionSupplier.get()!!.compileSdkVersion must not be null
```
> Example: https://jenkins-oss.wixpress.com/view/Tree/job/detox-android-61-4-master/560/console
=> Upgrade demo apps to android 10 (sdk 29), upgrade espresso and gradle

detox/android/detox/src/main/java/com/wix/detox/reactnative/ReactNativeInfo.kt
---
Hopefully fix a crash seen in the Wix app:
```
1-18 17:32:05.510 32451 32527 E AndroidRuntime: java.lang.NoSuchMethodError: No static method getValue(Ljava/util/Map;Ljava/lang/Object;)Ljava/lang/Object; in class Lkotlin/collections/MapsKt; or its super classes (declaration of 'kotlin.collections.MapsKt' appears in /data/app/com.wix.android.dev-V3p587DH9Rh1U3XZZqydAg==/base.apk:classes2.dex)
11-18 17:32:05.510 32451 32527 E AndroidRuntime:     at com.wix.detox.reactnative.ReactNativeInfo.<clinit>(ReactNativeInfo.kt:12)
11-18 17:32:05.510 32451 32527 E AndroidRuntime:     at com.wix.detox.reactnative.ReactNativeExtension.waitForRNBootstrap(ReactNativeExtension.kt:53)
11-18 17:32:05.510 32451 32527 E AndroidRuntime:     at …
```
=> Fix wix-app crash introduced due to recent Detox RN-code refactoring

detox/src/devices/Device.js, detox/src/devices/Device.test.js, detox/src/devices/drivers/AndroidDriver.js, detox/src/devices/drivers/AndroidDriver.test.js, detox/src/devices/drivers/DeviceDriverBase.js, docs/APIRef.DeviceObjectAPI.md
---
Introduce the common `adb reverse` command in Detox' `device` API.
@viktorijasujetaite
=> Make Android's adb-reverse a public device API

detox/src/devices/android/Emulator.js, detox/src/utils/exec.js, detox/src/utils/exec.test.js, detox/src/utils/retry.js, detox/src/utils/retry.test.js
---
Introduce retry code for when Android emulators are started by Detox and crashed with an unknown error code (i.e. "failed with code null" message).
=> Enable emulator boot retry when crashed with unspecified reason

detox/android/detox/src/main/java/com/wix/detox/Detox.java, detox/src/android/espressoapi/Detox.js
---
Fixes #1728. Core issue was that app activity launches made while the app is running (e.g. in background) were performed using `appContext.startActivity()` rather than `activity.startActivity()`, which seems to have been protected-from in newer sdk's (>= 28 I presume).
The diff is however larger than that because just by changing that one line didn't resolve having multiple activities of the test app running in the same task (which we're really trying to avoid). Usage of additional pin-point flags fixes that.
---
+Note on this: on CI, we're currently only running on an SDK 26 emu. Nevertheless I've deep-inspected this solution (often running `adb shell dumpsys activity activites`) locally and it works. With upcoming plans to upgrade the emu to a clean …
=> Fix crash related to FLAG_ACTIVITY_NEW_TASK intent flag in url launches (#1728)

detox/src/utils/fsext.js
---
Update `getDirectories` to follow symbolic links and return those ones whose destinations are folders.
=> Update getDirectories to include symbolic links to directories

detox/test/package.json, examples/demo-react-native-jest/package.json, examples/demo-react-native/package.json
---
Move CI to an SDK-28 AOSP Emulator
=> (Android) Switch to Pixel_API_28 w/o google-api's

scripts/demo-projects.android.sh
---
Lately we've been facing major instabilities with the demo-project build job on CI on Android.
In a nutshell - though things used to be a bit different (but still unstable), the script runs a total of 4 test projects/configurations such that the first 2 (in the context of`demo-react-native`) are run on a single emulator (no parallelization) and then those of the 2nd group (context of `demo-react-native-jest`) are run on 2 emulators (parallel-execution).
It appears that the *emulator binary* (/ `qemu`) does not cope very well the loading of an additional emulator, while a different emulator is already fully up and running (as resulted by the script's run). More specifically, in about 40-50% of the cases the newly dispatched emulator (or actually it's `adb` at fault...) …
=> Swap order of mocha vs. jest demo-prj run to stabilize CI

detox/test/android/app/build.gradle, examples/demo-react-native/android/app/build.gradle
---
All of our emulators on Detox CI agents are `x86_64` and since we don't include `x86_64` as an abi the emulators produce this unnecessary warning:
```
12-23 05:34:30.046  2849  2849 W dex2oat : Mismatch between dex2oat instruction set features (ISA: X86 Feature string: -ssse3,-sse4.1,-sse4.2,-avx,-avx2,-popcnt) and those of dex2oat executable (ISA: X86 Feature string: ssse3,sse4.1,sse4.2,-avx,-avx2,popcnt) for the command line:
12-23 05:34:30.046  2849  2849 W dex2oat : /system/bin/dex2oat --zip-fd=8 --zip-location=base.apk --input-vdex-fd=-1 --output-vdex-fd=10 --oat-fd=9 --oat-location=/data/app/com.wix.detox.test-prlD12c1NzR2c6C8rI4Kcg==/oat/x86/base.odex --instruction-set=x86 --instruction-set-variant=x86_64 --instruction-set-features=default --runtime-arg -Xms64m …
```
=> Resolve "Mismatch between dex2oat instruction set features" warning by android emu's on CI

detox/android/detox/src/main/java/com/wix/detox/Detox.java, detox/src/devices/drivers/AndroidDriver.js, detox/src/devices/drivers/AndroidDriver.test.js, detox/test/e2e/22.launch-args.test.js
---
Fixes #1804 by introducing these two changes:
1. On the tester (JS) side, allow reserved instrumentation args to pass-through unencoded.
2. On the Android-native side, refrain from passing such instrumentation args into the activity through the intent's extras.
=> Properly handle instrumentation args passed in as launch-args

detox/local-cli/templates/jest.js
---
Compliments #1821 by applying fix in Jest init template.
Related to #1194 (i.e. the root that's sparked all of this).
=> Apply Jest timeout setup optimization into init (cli) template

detox/src/configuration.js, docs/APIRef.Configuration.md, examples/demo-react-native-jest/package.json
---
Fixes the following bug in #1729 :
The custom `pathBuilder` string in the configuration originally was intended to be a regular `Node.js`-ish path to a module, but by mistake, I made it something like a relative path.
Before:
```
"pathBuilder": "config/pathbuilder.js",
```
After:
```
"pathBuilder": "./config/pathbuilder.js",
```
=> fix(configuration): pathBuilder resolution should be Node.js-ish

detox/src/artifacts/ArtifactsManager.js, detox/src/artifacts/ArtifactsManager.test.js, detox/src/artifacts/instruments/SimulatorInstrumentsPlugin.js, detox/src/artifacts/instruments/SimulatorInstrumentsRecording.js, detox/src/artifacts/log/ios/SimulatorLogPlugin.js, detox/src/artifacts/templates/plugin/ArtifactPlugin.js, detox/src/artifacts/templates/plugin/ArtifactPlugin.test.js, detox/src/devices/drivers/AndroidDriver.js, detox/src/devices/drivers/DeviceDriverBase.js, detox/src/devices/drivers/SimulatorDriver.js, detox/test/e2e/23.flows.test.js
---
If we terminate a tested app inside a test, then the test next to it won't pass if you have `--record-performance all` flag turned on. :disappointed:  Detox tries to send `setRecordingState` via `Client.js` right inside `beforeEach` phase, which is a bad idea in the case when the app is not running.
=> fix(instruments): should not crash if the app was terminated inside a test

detox/local-cli/test.js, detox/local-cli/test.test.js, detox/local-cli/utils/deprecation.js
I am going to release a major version of Detox due to a small yet breaking :man_shrugging: change in https://github.com/wix/Detox/pull/1827.
It's time to fulfill the deprecation warnings for `file` and `specs`.
=> deprecation: CLI (-f, --file, -s, --specs), package.json (detox.file)

detox/src/Detox.js, detox/src/Detox.test.js, detox/src/artifacts/ArtifactsManager.js, detox/src/artifacts/ArtifactsManager.test.js, detox/src/artifacts/log/ios/SimulatorLogPlugin.test.js, detox/src/artifacts/templates/plugin/ArtifactPlugin.js, detox/src/artifacts/templates/plugin/ArtifactPlugin.test.js, detox/src/artifacts/templates/plugin/StartupAndTestRecorderPlugin.js, detox/src/artifacts/templates/plugin/StartupAndTestRecorderPlugin.test.js, detox/src/artifacts/templates/plugin/TwoSnapshotsPerTestPlugin.js, detox/src/artifacts/templates/plugin/TwoSnapshotsPerTestPlugin.test.js, detox/src/artifacts/templates/plugin/WholeTestRecorderPlugin.js, detox/src/artifacts/templates/plugin/WholeTestRecorderPlugin.test.js
This is the first step to implement: https://github.com/wix/Detox/issues/1661 .
This pull request aligns `before each` and `after each` events from Detox terminology to the `test start` and `test done` from Jest Circus terminology. This naming reflects much more closely the actual workflow in Detox artifacts manager.
The full solution of #1661 will be too voluminous for one pull request and involve way too many files for a human reviewer's eye, hence I'll be splitting it into micro-PRs.
=> code(artifacts): beforeEach -> testStart, afterEach -> testDone

detox/src/Detox.js, detox/src/Detox.test.js, detox/src/artifacts/ArtifactsManager.js, detox/src/artifacts/ArtifactsManager.test.js, detox/src/artifacts/log/LogArtifactPlugin.js, detox/src/artifacts/log/ios/SimulatorLogPlugin.test.js, detox/src/artifacts/templates/plugin/ArtifactPlugin.js, detox/src/artifacts/templates/plugin/ArtifactPlugin.test.js, detox/src/artifacts/templates/plugin/StartupAndTestRecorderPlugin.js, detox/src/artifacts/templates/plugin/StartupAndTestRecorderPlugin.test.js, detox/src/artifacts/templates/plugin/TwoSnapshotsPerTestPlugin.js, detox/src/artifacts/templates/plugin/TwoSnapshotsPerTestPlugin.test.js
---
This is the second step to implement: https://github.com/wix/Detox/issues/1661 .
This pull request returns the original meaning to `before all` and `after all` events from Detox terminology, which is `onAfterInit` and `onBeforeCleanup`, if we are honest.
However, after looking at the code, I have found out that the former `onBeforeAll` is no longer in use, apparently, after the SimulatorLogPlugin refactoring in the past year. That's why I just remove the unused code.
The new naming reflects much more closely the actual workflow in Detox artifacts manager.
The full solution of #1661 will be too voluminous for one pull request and involve way too many files for a human reviewer's eye, hence I'll be splitting it into micro-PRs like #1845 and this one.
=> code(artifacts): remove onBeforeAll, rename onAfterAll -> onBeforeCleanup

detox/android/detox/src/main/java/com/wix/detox/espresso/DetoxAction.java, detox/android/detox/src/main/java/com/wix/detox/espresso/action/RNClickAction.java
---
Except for offsets calculation, reimplement `tapAtPoint()` so as to apply existing fixes and adjustment implemented in `tap()`.
=> (Android) Apply existing tap improvements and adjustments to tapAtPoint()

detox/package.json, detox/runners/jest/WorkerAssignReporterImpl.js, detox/src/Detox.js, detox/src/DetoxExportWrapper.js, detox/src/index.test.js, detox/src/utils/MissingDetox.js
I am very tired of user reports that tell `device (or element) is not defined` and so on.
Let's solve it.
The goal of this pull request to transform those errors:
To these, telling that there was an error in detox.init():
=> More helpful error message if Detox.init() fails

detox/src/devices/ios/AppleSimUtils.js, detox/src/utils/exec.js, detox/src/utils/exec.test.js, detox/wallaby.js
Changed `log stream` predicate from processImagePath to process==. This predicate suites detox much more since it is constant between installs, unlike processImagePath which changes on every reinstallation.
=> Changed log stream predicate from processImagePath to process==

detox/src/artifacts/ArtifactsManager.js, detox/src/artifacts/ArtifactsManager.test.js, detox/src/configuration.js, detox/src/configuration.test.js, detox/src/index.test.js
---
1. There was code in the artifacts manager that has never been in use since 2018, so I removed a good part of it.
2. `pathBuilder` in the configuration object, IMO, should be already some class instance, not a string. ArtifactsManager should not take this responsibility for resolving paths and modules. I move that to `configuration.js`.
3. Unit tests fixes.
=> code: cleanup redundant artifacts code

detox/android/detox/src/main/java/com/wix/detox/Detox.java, detox/android/detox/src/main/java/com/wix/detox/DetoxManager.java, detox/src/devices/drivers/AndroidDriver.js, detox/src/devices/drivers/AndroidDriver.test.js, detox/src/devices/drivers/InstrumentationLogsParser.js, detox/src/devices/drivers/InstrumentationLogsParser.test.js, detox/test/android/app/src/androidTest/java/com/example/DetoxTest.java, detox/test/android/app/src/main/AndroidManifest.xml, detox/test/android/app/src/main/java/com/example/CrashingActivity.java, detox/test/android/app/src/main/java/com/example/MainActivity.java, detox/test/android/app/src/main/res/values/strings.xml, detox/test/e2e/15.urls.test.js, detox/test/e2e/19.crash-handling.test.js
---
Fixes #1880 by monitoring instrumentation status immediately after instrumentation launch (i.e. by running the `adb shell am instrument ...` command), alongside waiting for the traditional 'device ready' response from the device. Upon failure, also dumps stacktrace parsed from background-reported instrumentation logs.
=> (Android) Friendly-fail test runner if app crashes on launch

detox/android/detox/src/main/java/com/wix/detox/espresso/action/DetoxSingleTap.kt, detox/android/detox/src/test/java/com/wix/detox/espresso/action/DetoxSingleTapSpec.kt
---
In the context of issues such as https://github.com/software-mansion/react-native-reanimated/issues/596, we find that the current implementation of Detox' single-tap - though optimal, can be a bit too rough. We therefore need to unwillingly tone it down a bit, in the very least, until that bug is fixed.
=> Tone down tap gesture on Android

docs/Introduction.Android.md
---
I spent a good few hours trying to work out how to get product flavors working before stumbling across 
issue https://github.com/wix/Detox/issues/1810.
To help other developers who may want to use [productFlavors](https://developer.android.com/studio/build/build-variants#product-flavors) i've added an example to the Android getting started docs.
=> Add product flavor docs to Android

lerna.json
---
Just stumbled upon an error resulted by this matter. We don't commit nor rely on dep management via `package-lock.json` files so it's better to remove them altogether.
=> Configure lerna to avoid adhering to dangling package-lock files

detox/src/artifacts/video/SimulatorRecordVideoPlugin.js, detox/src/devices/ios/AppleSimUtils.js, docs/APIRef.Configuration.md
---
Adds `codec` option to artifacts JSON config (in package.json), e.g.:
```json
{
"detox": {
"artifacts": {
"plugins": {
"video": {
"simulator": {
"codec": "h264"
}
}
}
}
}
}
```
=> feat(artifacts): codec option for simulator video recording

detox/android/detox/build.gradle, detox/android/detox/src/main/java/com/wix/detox/DetoxANRHandler.kt, detox/android/detox/src/main/java/com/wix/detox/DetoxCrashHandler.kt, detox/android/detox/src/main/java/com/wix/detox/DetoxManager.java, detox/src/Detox.js, detox/src/Detox.test.js, detox/src/client/Client.js, detox/src/client/Client.test.js, detox/src/client/actions/actions.js, detox/test/android/app/src/main/java/com/example/NativeModule.java, detox/test/e2e/19.app-responsiveness.test.js, detox/test/e2e/utils/log-interceptor.js, detox/test/src/app.js
---
Resolves #1925. Introduces usage of the very interesting [ANR-WatchDog project](https://github.com/SalomonBrys/ANR-WatchDog) for the sake of ANR-state proximation. The ends result is a warning on the Detox (tester) side with a main-thread stacktrace, when main-thread blockage is detected, alongside a complete thread-dump on the device logs.
Integration of it all was pretty straightforward, but testing this (e2e) was a bit of a pain since logs are not easy to intercept.
=> (Android) Introduce ANR monitor to produce warn-logs

detox/android/build.gradle, detox/test/android/build.gradle, docs/Introduction.Android.md, examples/demo-react-native/android/build.gradle
---
This was previously proposed in #1836, #1835 and #1833 but never made it to a fulfilling PR level (see https://github.com/wix/Detox/pull/1836#issuecomment-572244062). This is a one-PR-to-rule-them-all.
=> Fix the 'Verion' typo that caused kotlin version usage mixup

detox/local-cli/test.js, detox/src/utils/callsites.js, detox/src/utils/callsites.test.js, detox/src/utils/customConsoleLogger.js, detox/src/utils/customConsoleLogger.test.js, detox/src/utils/logger.js, docs/APIRef.DetoxCLI.md
---
Introduce a unified logging solution that overrides `console` functions implementation. Goal here is twofold:
1. Wire user logs onto bunyan, such that (in addition to its nice optional features) the log would be associated with the `pid` -- as in parallel-exec envs all user logs are currently scarce without it.
2. Pave way for thus bundling user logs into the timeline trace artefact.
Initially, the plan was to simply grab the logs as-is and just rewire through bunyan. This turned out to be a bit of a dirty but mostly an imperfect solution - especially in Jest (which already provide a custom logger), which logs the log-origin (which gets broken in this approach) and also log in multiple lines and thus ident to start (which by default overrides the bunyan pid prefix). …
=> Introduce unified custom logger to log user events using bunyan

detox/android/detox/build.gradle, detox/test/android/app/build.gradle, docs/Introduction.Android.md, examples/demo-react-native/android/app/build.gradle
---
- Removes unneeded transitive deps currently defined for the Detox lib, improves docs and adds notes as to explain why deps are needed.
- Resolves #1898.
=> Clean up and document Android deps

docs/Introduction.AndroidEmulatorsBestPractices.md
---
Add a note in the docs on how to download AOSP images from your dev machine when you get this error message: `Error: Package path is not valid. Valid system image paths are:`
=> Enhance docs: how to download AOSP system images

detox/android/detox/src/main/java/com/wix/detox/DetoxJUnitRunner.java
Fixed issue with DetoxJUnitRunner.
Instance of `ApplicationLifecycleCallback` should be stored as ref, because `monitor.addLifecycleCallback` stores callback only as weak reference.
=> Fixed DetoxJUnitRunner

detox/src/utils/callsites.js, detox/src/utils/callsites.test.js, detox/src/utils/customConsoleLogger.test.js
---
1. Fixed implementation of `callsites.stackdump` - added RegExp escaping. Otherwise, I see issue on Windows 10:
```
● callsites › stack-dump › should slice according to end-frame arg
SyntaxError: Invalid regular expression: /C:\Users\noomo\Projects\wix\Detox\detox\/: \ at end of pattern
at new RegExp (<anonymous>)
16 |     .slice(2 + endFrame) // 2 = 1 for 'Error:' prefix and 1 for this function's frame
17 |     .join('\n')
> 18 |     .replace(new RegExp(cwd, 'g'), '');
|              ^
19 | };
20 |
at Function.stackdump (src/utils/callsites.js:18:14)
at callStackDumpFromWrapperFn (src/utils/callsites.test.js:23:64)
at callStackDumpFromTwoWrapperFn (src/utils/callsites.test.js:24:57)
at Object.<anonymous> (src/utils/callsites.test.js:38:25)
```
Most likely, it is apt …
=> fix(windows): unescaped regexp issue, unit tests

detox/src/Detox.js, detox/src/artifacts/ArtifactsManager.js, detox/src/artifacts/ArtifactsManager.test.js, detox/src/artifacts/templates/plugin/ArtifactPlugin.js, detox/src/artifacts/templates/plugin/ArtifactPlugin.test.js
---
During another code review, I have noticed that `onInit` is technically useless and not in use at all, so why not remove it?
=> code(artifacts): remove not used event onInit

detox/src/devices/drivers/AndroidDriver.test.js, detox/src/errors/DetoxRuntimeError.js
---
The way I was adding `DetoxRuntimeError: ` prefix for this custom error code is not idiomatically correct. When you call `err.toString()`, you can see something like `Error: DetoxRuntimeError: …`.
It appears that nowadays all you need when [extending Error](https://javascript.info/custom-errors#extending-error), is just to call `super(message)` and write down `this.name = 'MyCustomError'` and voila.
=> code: fix Error inheritance

detox/scripts/build_framework.ios.sh
---
This is a fix for missing logs on `build_universal_framework.sh` failures. (`build_framework.ios.sh` runs with `bash -e` which means it fails right away on `build_universal_framework.sh` failure, so no log is printed)
=> Fixed output of build_framework.ios.sh on failures

docs/APIRef.ActionsOnElement.md
---
I used JS Date object to call `setDatePickerDate` and it took me a while to figure out the correct format. I thought this might help someone else.
=> give hint for setDatePickerDate date conversion

detox/src/devices/drivers/AdbDevicesHelper.js, detox/src/devices/drivers/AdbDevicesHelper.test.js, detox/src/devices/drivers/EmulatorDriver.js, detox/src/devices/drivers/EmulatorLookupHelper.js, detox/src/devices/drivers/EmulatorLookupHelper.test.js
---
Refactor part-1 of `EmulatorDriver`, which has become bloated. In this episode - moving away emulator acquiring logic, which is used by the device registry as its acquiring callback.
Happy to say that the episode ends with everything jolly and merry - all thanks to TDD, strictly used the main character as its main weapon!
=> Refactor bloated emulator driver according to sub-concerns

detox/src/devices/drivers/android/EmulatorDriver.js, detox/src/devices/drivers/android/EmulatorVersion.js, detox/src/devices/drivers/android/EmulatorVersion.test.js
---
Part 2 of #1984. This time, extracting away emulator-version querying logic. To be continued...
=> Refactor bloated emulator driver according to sub-concerns, part 2

docs/Introduction.GettingStarted.md
Version 16.x now requires Xcode 10.2 or greater
---
I see the latest release notes that 10.2 is now required, updating corresponding doc. Searched the project and seems like you already got all the other ones updated!
=> Update getting started iOS

detox/src/Detox.js, detox/src/Detox.test.js, detox/src/artifacts/ArtifactsManager.js, detox/src/artifacts/ArtifactsManager.test.js, detox/src/artifacts/screenshot/ScreenshotArtifactPlugin.js, detox/src/artifacts/templates/plugin/ArtifactPlugin.js, detox/src/artifacts/templates/plugin/ArtifactPlugin.test.js, detox/src/devices/Device.js, detox/src/devices/Device.test.js, detox/src/devices/drivers/DeviceDriverBase.js, detox/src/devices/drivers/android/AndroidDriver.test.js, detox/src/devices/drivers/ios/SimulatorDriver.test.js
---
Supplements #1914 . Will be taking an automatic screenshot `appNotReady.png`, when there was an issue with launching the app, when it never signalled back that it is ready and active.
@d4vidi, here the question is mostly whether `device.driver.emitter` makes you smell _Feature envy_, one of the code smells, or it is fine?
=> feat(artifacts): take appNotReady.png screenshot if needed

detox/src/artifacts/screenshot/ScreenshotArtifactPlugin.js, detox/src/artifacts/screenshot/ScreenshotArtifactPlugin.test.js
---
This fixes the thing I forgot when merging both #1971 and #1980.
I think that the right thing to do even if the user supplies this as a configuration:
```js
{
"takeWhen": {
"testStart": true,
// "appNotReady": undefined,
}
}
```
is still set `appNotReady = true` by default, unless it is explicitly forbidden, which is doubtful, to be honest.
=> fix(artifacts): by default take appNotReady screenshot

detox/src/devices/drivers/android/EmulatorDriver.js, detox/src/devices/drivers/android/emulator/EmulatorVersionResolver.js, detox/src/devices/drivers/android/emulator/EmulatorVersionResolver.test.js
---
With respect to #1995 - which has been closed nonetheless, this applies less extreme failing measures in case of emulator version detection.
Also, will evidently resolve #1157.
=> Resort to soft-failing errors in emulator version detection for skin-cfg patching

scripts/ci.android.sh, scripts/ci.ios.sh
---
The latest extra e2e tests overwrite the coverage of the main suite, so I am giving now the coverage files different names to save it all.
=> ci: save coverage from different e2e tests

docs/APIRef.DetoxCLI.md
---
Remove iOS only flag for workers flag
=> Remove iOS only flag for workers flag

docs/APIRef.Configuration.md
---
detox supports `--workers` flag to enable parallelization with jest as noted in CLI docs: https://github.com/wix/Detox/blob/master/docs/APIRef.DetoxCLI.md
=> config(docs): rm outdated parallelization note

detox/package.json
---
I see CI build stuck with telnet connecting for 1 hour in TeamCity.
Checked source code of the former telnet-client version and it appears...
...they don't throw any error on timeout.
P. S. Cannot bump to the latest, because they have changed licensing to LGPLv3, and I am not legally sure if we can use it.
=> fix: use bugfixed telnet-client version

detox/runners/jest/SpecReporterCircus.js, detox/runners/jest/SpecReporterImpl.js
---
Associated with #2040. Adds reporting of retry attempt index, if applicable (e.g. when [`jest.retryTimes()`](https://jestjs.io/docs/en/jest-object#jestretrytimes) is used in conjunction with `jest-circus`). Example of what an output generated by the spec-reporter looks like with this change:
```
detox[60507] INFO:  Sanity is assigned to emulator-15200 (Pixel_API_28)
detox[60507] INFO:  Sanity: should have welcome screen
detox[60507] INFO:  Sanity: should have welcome screen [FAIL]
detox[60507] INFO:  Sanity: should show hello screen after tap
detox[60507] INFO:  Sanity: should show hello screen after tap [OK]
detox[60507] INFO:  Sanity: should have welcome screen
detox[60507] INFO:  Sanity: should have welcome screen (retry #1) [FAIL]
detox[60507] INFO:  Sanity: …
```
=> Add reporting of a spec exec retry to spec-reporter

detox/src/devices/drivers/android/AndroidDriver.js, detox/src/devices/drivers/android/EmulatorDriver.js, detox/src/devices/drivers/android/tools/ADB.js, detox/src/devices/drivers/android/tools/ADB.test.js
---
Add missing flags to recently instated `adb shell pm install` command (see #2019) - the same ones as used to be specified for `adb install`:
- `-r` to allow for the replacement of existing apps (hence no need to manually uninstall)
- `-t` to allow for test packages (seems useless, but nevertheless)
- `-g` to auto-allow for all runtime permissions.
This doesn't fix any reported issue in particular, but rather addresses [this comment](https://github.com/wix/Detox/pull/2019#issuecomment-623632126) in the original PR.
=> Apply missing flags to "pm install": reinstall, permissions, test

detox/local-cli/run-server.js, detox/src/Detox.js, detox/src/Detox.test.js, detox/src/DetoxExportWrapper.js, detox/src/artifacts/ArtifactsManager.js, detox/src/artifacts/ArtifactsManager.test.js, detox/src/client/__mocks__/Client.js, detox/src/configuration.js, detox/src/configuration.test.js, detox/src/configurations.mock.js, detox/src/devices/Device.js, detox/src/devices/Device.test.js, detox/src/devices/DriverRegistry.js, detox/src/devices/DriverRegistry.test.js, detox/src/devices/__mocks__/Device.js, detox/src/devices/__mocks__/DriverRegistry.js, detox/src/devices/drivers/__mocks__/FakeDriver.js, detox/src/index.test.js, detox/src/server/DetoxServer.js, detox/src/server/__mocks__/DetoxServer.js, detox/src/utils/resolveModuleFromPath.js, detox/src/utils/resolveModuleFromPath.test.js, detox/test/package.json, docs/APIRef.Configuration.md, examples/demo-plugin/package.json
Prepares ground for landing #1910.
Slightly extends configuration capabilities, but the main point is that a configuration object for `new Detox` now contains all data it needs. No more scattering over places and files.
As a side effect, you can specify all that you previously could do via `detox.init(config, userParams)`, but now those params reside also in `package.json` Detox's section, called `behavior`.
```json
{
"detox": {
"behavior": {
"init": {
"reinstallApp": true,
"launchApp": true,
"exportGlobals": true
},
"cleanup": {
"shutdownDevice": false
}
},
}
}
```
Also, this PR fixes a partially incorrect custom driver require logic, where it was not using `process.cwd()` to resolve relative path dependencies.
I plan to add the new config object extension to the …
=> refactor: unified configuration

detox/src/utils/customConsoleLogger.js, detox/src/utils/customConsoleLogger.test.js
---
Sorry I didn't file an issue cuz this was such a small change. 
When using mocha, and trying to log within a hook/test `detox/src/utils/customConsoleLogger.js:: getOrigin()` blows up because `userCallsite.getFileName()` is `undefined` and therefore `path.relative()` explodes.
Simple reproduce:
```
before: async () => {
console.log('**********BLAH');
```
PR is not the most elegant solution, but not sure there is much that can be done when using https://github.com/sindresorhus/callsites
Without this fix, I can not use Detox (and I want to, cuz really like it :)
=> Handle logging in async function

docs/Introduction.Android.md
---
Just updates the Getting Started for Android guide.
Previously this said to use `<domain-config cleartextTrafficPermitted="false">` which is how you explicitly set domains to not allow cleartext traffic but for Detox we want the opposite.  I also tried to make the readme section a little more explicit on exactly what to do.
I also removed the "untested" part of this because I have tested and confirmed it works.
=> Fix and clarify troubleshooting "The app loads but tests fail to start in SDK >= 28" on android

docs/Introduction.Android.md, examples/demo-react-native/android/app/src/main/AndroidManifest.xml, examples/demo-react-native/android/app/src/main/res/xml/network_security_config.xml
---
This is a follow-up on #2061:
- Integrates the proper Android network-security configuration for Detox.
- Update setup docs accordingly.
=> Update Android network-security in example app

detox/local-cli/init.js, detox/local-cli/templates/mocha.js, detox/local-cli/test.js, detox/local-cli/test.test.js, detox/src/client/Client.js, examples/demo-react-native/e2e/.mocharc, examples/demo-react-native/e2e/mocha.opts, examples/demo-react-native/package.json
Resolves #2057 
---
1. In `detox` section of `package.json`, when `test-runner` is `mocha`, and `runner-config` field points to a file with an extension different from `.opts`, Detox CLI in `detox test` command will use `--config` option instead of `--opts`.
2. `detox init -r mocha`  generates a template with `e2e/.mocharc` file instead of the deprecated `e2e/mocha.opts`.
=> fix(mocha): use .mocharc when possible

docs/Introduction.Android.md
---
Just noticed this spelling error :)
=> Fix spelling of developers in android quick start

detox/src/devices/drivers/android/EmulatorDriver.js, detox/src/devices/drivers/android/tools/ADB.js, detox/src/devices/drivers/android/tools/ADB.test.js, detox/test/android/app/src/main/java/com/example/AnimationViewManager.java, detox/test/android/app/src/main/java/com/example/AnimatorListenerStub.java, detox/test/android/app/src/main/java/com/example/NativeModulePackage.java, detox/test/android/app/src/main/res/layout/animation_test.xml, detox/test/e2e/12.animations.test.js, detox/test/src/Screens/NativeAnimationsScreen.js, detox/test/src/Screens/index.js, detox/test/src/app.js
---
Addressing this has long-overdued, and its been recently incentivised for upon coming across related problems in internal apps. After making numerous futile attempts at creating an idling-resource that would fill in the missing gap<sup>*</sup>, it is now clear that the only option is to go with Google's recommendation and turn off animations across the board.
---
<sup>* System components such as `RenderThread` and the centralized (though thread-based) `AnimationHandler` (method `getAnimationCount()`) are all hidden and inaccessible even via reflection on actual devices.</sup>
=> Disable Android animations for all emulators

detox/android/detox/src/main/java/com/wix/detox/Detox.java, detox/test/android/app/src/androidTest/java/com/example/DetoxTest.java, examples/demo-react-native/android/app/src/androidTest/java/com/example/DetoxTest.java
---
This has been discussed in the past in https://github.com/wix/Detox/issues/1782#issuecomment-560125814. After getting associated failures in internal projects, it's time to increase the defaults (yet allow for custom overrides).
=> Apply custom, less tight, IdlePolicy timeouts

detox/src/devices/drivers/android/tools/EmulatorExec.js
=> hotfix(android): respect --headless option in Mocha and other runners

docs/APIRef.waitFor.md
---
#1473 fixed `waitFor().withTimeout()` so that an exception is raised when the assertion fails. That PR updated other sections of the doc to remove the note about using `expect()` but it looks like this line was missed.
=> Update waitFor docs

detox/android/detox/src/main/java/com/wix/detox/espresso/action/DetoxMultiTap.kt, detox/android/detox/src/main/java/com/wix/detox/espresso/action/DetoxSingleTap.kt, detox/android/detox/src/main/java/com/wix/detox/espresso/common/DetoxViewConfiguration.kt, detox/android/detox/src/test/java/com/wix/detox/espresso/action/DetoxMultiTapSpec.kt, detox/android/detox/src/test/java/com/wix/detox/espresso/action/DetoxSingleTapSpec.kt, detox/test/android/app/src/main/java/com/example/AnimationViewManager.java, detox/test/android/app/src/main/java/com/example/DoubleTapsTextViewManager.java, detox/test/android/app/src/main/java/com/example/NativeModule.java, detox/test/android/app/src/main/java/com/example/NativeModulePackage.java, detox/test/android/app/src/main/java/com/example/utils/AnimatorListenerStub.java, detox/test/android/app/src/main/java/com/example/utils/DoubleTapListenerStub.java, detox/test/android/app/src/main/java/com/example/utils/ViewSpies.java, detox/test/e2e/03.actions.test.js, detox/test/src/Screens/ActionsScreen.js, detox/test/src/Screens/NativeAnimationsScreen.js, docs/APIRef.ActionsOnElement.md
---
Improve implementation of `tap()` and `multiTap()` on Android so as to consider potential gesture-handler listening to complex gestures - double-taps in particular, that can hijack tap-events if not applied by-the-book.
Motivated for fixing now in the wake of related bugs recently found while integrating test-suites of newly joining internal projects (for execution on Android emulators) -- where an interesting sequence of taps has been applied in the beginning of each test.
---
As for implementation, most work was around creating e2e tests that would uncover the faulty behaviour. That required the creation of a custom native view, now rendered as a part of the test-app's actions screen (but only on Android), that would provide a simple impl. of a tappable text view …
=> Apply a clear, by-the-book impl. for taps and multi-taps on Android

docs/APIRef.DetoxCLI.md
=> Fix typo in APIRef.DetoxCLI.md

detox/ios/Detox/DetoxInstrumentsManager.m
=> Use EarlGrey with no XCTest dependency

docs/Introduction.Android.md, examples/demo-react-native/android/app/src/main/res/xml/network_security_config.xml
---
This PR adds `localhost` to android `network_security_config` in example app and docs. This rule is required to run tests on attached device (because `adb reverse` exposes ports on localhost) and its absence is discouraged for newbies
=> Add localhost to android network_security_config.xml (both in example and docs) to fix tests stuck on attached devices

detox/runners/jest-circus/environment.js, examples/demo-react-native-jest/detox.config.js, examples/demo-react-native-jest/e2eExplicitRequire/config.json, examples/demo-react-native-jest/e2eExplicitRequire/environment.js, examples/demo-react-native-jest/e2eExplicitRequire/example.e2e.js, examples/demo-react-native/detox.config.js, examples/demo-react-native/package.json, scripts/demo-projects.android.sh, scripts/demo-projects.ios.sh
---
This is a common use case, when users explicitly destructure our facade:
```js
const { device, expect, /* ... so on ... */ } = require('detox');
```
It appears that our `demo-react-native-jest` example project had no `e2eExplicitRequire` checks, and a bug slipped into production:
The new DetoxCircusEnvironment relies on the existence of `global.detox` variable, to prevent creating new and new Detox facade instances every time the `require` sandbox is reset by Jest for every next test file.
https://github.com/wix/Detox/blob/53d46b9a31d88f224b6593d89800cdf96e6485b6/detox/src/index.js#L1-L3
That's why this PR:
1. Fixes the issue by setting `detox` global variable after environment setup, like it was planned initially in #2009. It simply was never set, or more precisely …
=> fix(jest-circus): explicit require('detox') should not fail

detox/runners/jest-circus/environment.js, detox/src/DetoxExportWrapper.js, detox/src/utils/__mocks__/logger.js, detox/src/utils/callsites.js, detox/src/utils/callsites.test.js, detox/src/utils/customConsoleLogger.js, detox/src/utils/customConsoleLogger.test.js, detox/src/utils/logger.js, detox/test/e2e/config.js
---
Fixes a regression bug that has popped after DetoxCircusEnvironment rewrite.
Before the fix (regression):
After the fix:
=> fix(jest-circus): reinitialize custom logger on every Environment.setup

detox/android/detox/src/main/java/com/wix/detox/Detox.java, detox/android/detox/src/main/java/com/wix/detox/LaunchIntentsFactory.kt, detox/src/android/espressoapi/Detox.js, detox/src/devices/Device.js, detox/src/devices/Device.test.js, detox/src/devices/drivers/DeviceDriverBase.js, detox/src/devices/drivers/android/AndroidDriver.js, detox/src/devices/drivers/android/AndroidDriver.test.js, detox/test/android/app/src/main/java/com/example/MainActivity.java, detox/test/e2e/11.user-notifications.test.js, detox/test/src/Screens/AbstractArgsListScreen.js
---
Resolves #1192, by filling the missing gaps - as described in #2134, namely, by adding support for these two API usage cases:
```js
await device.launchApp({ newInstance: false, userNotification });
```
and:
```js
await device.sendUserNotification(userNotification);
```
---
In the process, I've also cleaned up and aligned the way URL-based launches are done. Formerly, the driver used to hold a transient pending-url property for the time between `deliverPayload` and `launchApp()` are called (by `device.launchApp()`). This has been removed, and `deliverPayload` is now completely ignored in this use case, as it is effectively irrelevant for Android.
=> Introduce basic support for all user-notification API's in all relevant use cases

detox/src/devices/drivers/android/AndroidDriver.js, detox/src/devices/drivers/android/AndroidDriver.test.js, detox/src/devices/drivers/android/tools/instrumentationArgs.js, detox/src/devices/drivers/android/tools/instrumentationArgs.test.js
---
Following work on #1192 -- need to break some of the AndroidDriver monolith into sub-units. This is prep-step 0.2, following #2146: refactor instrumentation launch-arguments preparation logic onto a dedicated module.
=> Refactor instrumentation-args preparation

detox/src/devices/drivers/android/AndroidDriver.js, detox/src/devices/drivers/android/AndroidDriver.test.js, detox/src/devices/drivers/android/tools/Instrumentation.js, detox/src/devices/drivers/android/tools/Instrumentation.test.js
---
Following work on #1192 -- need to break some of the AndroidDriver monolith into sub-units. This is the main step - 1.0, following #2146 and #2148: refactor away all the core of instrumentation process management.
=> Android driver refactor 1.0

detox/src/devices/drivers/android/AndroidDriver.js, detox/src/devices/drivers/android/tools/Instrumentation.js, detox/src/devices/drivers/android/tools/Instrumentation.test.js, detox/src/utils/retry.js, detox/src/utils/retry.test.js
---
Following work on #1192 -- need to break some of the AndroidDriver monolith into sub-units. This is a post-refactor step - 1.1, following #2146, #2148 and #2149: tidy-up work in driver itself, and some periphery.
=> Android driver refactor 1.1: Clean up android-driver and periphery even further

docs/APIRef.DeviceObjectAPI.md, docs/APIRef.MockingOpenWithURL.md, docs/APIRef.MockingUserNotifications.md
---
Updates the missing documentation with respect to changes introduced in #2134 and #2138, both associated with #1192 (i.e. android notification mocking support). Resolves #1192.
=> Update docs across the board with respect to notification support on Android

detox/test/android/app/build.gradle, detox/test/android/app/src/androidTest/java/com/example/DetoxTestAppJUnitRunner.java
---
Integrate Linkedin's awesome test-butler, which - among many other things, disables ANR's 🚀  (takes the assumption that a stock-android image is used... lucky us).
First creating a draft just to see how the CI responds.
=> Integrate test-butler with ANR disabling

docs/APIRef.Configuration.md, docs/Guide.Jest.md, docs/Guide.Mocha.md, docs/Introduction.Android.md, docs/Introduction.AndroidDevEnv.md, docs/Introduction.GettingStarted.md, docs/Introduction.Ios.md, docs/Introduction.IosDevEnv.md, docs/More.AndroidSupportStatus.md, docs/README.md
---
Resolves #2115. The change in a nutshell is as follows:
- Extraction of iOS specific instructions into equivalent android guides (dev-env, configuration+general setup)
- Generalization of getting-started guide with pointers to delegated guides where necessary
- Slight reorganization of the getting-start guide.
In order to review, consider simply going over the getting-started as a new detox user - as the diffs are impossible to interpret.
---
Rules of thumb I followed:
- DRY: tried my best not to have anything repeated. I managed to do so for the most part, except for two similar explanations regarding the configuration files resolution.
- (Somewhat related): Unify what's possible onto the main guide, and delegate onto platform-specific guides where things should be …
=> Consolidate (and split) setup onto a single getting-start guide [ci skip]

docs/APIRef.Configuration.md
---
Some little spelling and formatting tweaks to the Configuration docs
=> Spelling & linting of Config docs

detox-cli/cli.js
This adds support for [DetoxRecorder](https://github.com/wix/DetoxRecorder) in Detox CLI.
Now, when running `detox recorder`, CLI will test to see if Recorder is installed and forward that binary the commands. Otherwise behave the same as before.
=> Add support for Detox Recorder in Detox CLI

detox/src/devices/drivers/android/tools/FileXfer.js
---
Fixes #2178 
No idea how I can cover this with tests, honestly. E2E on Windows would do the job much better than faking the `path` module. 🤷
=> fix(android): installing issue on Windows

detox/android/detox/src/main/java/com/wix/detox/reactnative/idlingresources/timers/DelegatedIdleInterrogationStrategy.kt, detox/android/detox/src/test/java/com/wix/detox/reactnative/idlingresources/timers/DelegatedIdleInterrogationStrategySpec.kt
Due to wrong logic in [DelegatedIdleInterrogationStrategy.kt#L29](https://github.com/wix/Detox/blob/master/detox/android/detox/src/main/java/com/wix/detox/reactnative/idlingresources/timers/DelegatedIdleInterrogationStrategy.kt#L29)
With this wrong logic make Detox in android for React Native 0.63.0 time out with 
IdlingPolicy	These resources are not idle: [com.wix.detox.reactnative.idlingresources.timers.TimersIdlingResource]
UiControllerImpl	Waiting for: DYNAMIC_TASKS_HAVE_IDLED for 1600 iterations.
UiControllerImpl	Waiting for: DYNAMIC_TASKS_HAVE_IDLED for 1700 iterations.
UiControllerImpl	Waiting for: DYNAMIC_TASKS_HAVE_IDLED for 1800 iterations.
UiControllerImpl	Waiting for: DYNAMIC_TASKS_HAVE_IDLED for 1800 iterations.
...
---
Logic to determine TimersIdlingResource …
=> Fix Android React Native 0.63.0 testee not connected

detox/src/Detox.js, detox/src/Detox.test.js, detox/src/android/expect.js, detox/src/android/expect.test.js, detox/src/devices/Device.js, detox/src/devices/Device.test.js, detox/src/devices/DriverRegistry.js, detox/src/devices/DriverRegistry.test.js, detox/src/devices/drivers/DeviceDriverBase.js, detox/src/devices/drivers/android/AndroidDriver.js, detox/src/devices/drivers/android/AndroidDriver.test.js, detox/src/devices/drivers/ios/IosDriver.js, detox/src/ios/expectTwo.js, detox/src/ios/expectTwo.test.js, detox/src/ios/expectTwoApiCoverage.test.js, detox/src/matchersRegistry.js, detox/src/matchersRegistry.test.js, examples/demo-plugin/driver.js
---
Relates to #2012: lays some preliminary ground work so that we could introduce it with proper API.
Looking at the current software architecture of Detox at a high-level perspective, we see two main **distinct** units, top-to-bottom:
1. A framework for providing `expect` and element-interactions as a top-level, user-facing API (e.g. `element(by.id(testId)).tap()`), which in turn uses a distinct, platform-specific node-side (JS) implementation that eventually directly triggers device-side logic using `invoke`.
2. A framework for providing element-less, device-scope, top-level, user-facing APIs (e.g. `device.takeScreenshot()`), which are provided mainly by the (currently) singleton `Device` object, that in turns delegates platform-specific logic to Drivers.
While the two global _units_ …
=> Bump top-level matchers api to upper Detox layer (where they should be)

detox/src/devices/drivers/android/AndroidDriver.test.js, detox/src/devices/drivers/android/emulator/AVDValidator.test.js, detox/src/devices/drivers/android/emulator/FreeEmulatorFinder.test.js, detox/src/devices/drivers/android/tools/AppUninstallHelper.test.js, detox/src/devices/drivers/android/tools/MonitoredInstrumentation.test.js, detox/src/matchersRegistry.test.js
---
Optimize JS unit-tests code, mainly by utilizing Jest's amazing class-level mocking capabilities, which makes definition of various Mock-classes all-around scarce.
=> Crunch JS unit-tests code by utilizing Jest's mock.instances API

detox/local-cli/test.js, detox/src/configuration/collectCliConfig.js, detox/src/configuration/collectCliConfig.test.js, docs/APIRef.DetoxCLI.md
I added a flag to allow attaching a debugger to the underlying test runner.
Usage:
```
detox test --debug-test-runner
```
Haven't updated the docs yet, I wanted to get some initial feedback before doing so.
=> create flag to trigger --inspect-brk on test runner

detox/android/detox/src/main/java/com/wix/detox/Detox.java, detox/android/detox/src/main/java/com/wix/detox/common/DetoxErrors.java, detox/android/detox/src/main/java/com/wix/detox/config/DetoxConfig.kt, detox/android/detox/src/main/java/com/wix/detox/config/DetoxIdlePolicyConfig.kt, detox/android/detox/src/main/java/com/wix/detox/espresso/DetoxAction.java, detox/android/detox/src/main/java/com/wix/detox/espresso/DetoxAssertion.java, detox/android/detox/src/main/java/com/wix/detox/reactnative/ReactNativeLoadingMonitor.kt, detox/test/android/app/src/androidTest/java/com/example/DetoxTest.java, examples/demo-react-native/android/app/src/androidTest/java/com/example/DetoxTest.java
---
Resolves #2197. Migrates Detox' idle-policy config to a more generic config structure (that handles idle-policy as well), such that it can also hold a custom timeout for waiting for RN's loading to complete. That enables, for example, the customization of the timeout based on whether the app running in debug mode rather than release - where this can take longer for large apps. See [here](https://github.com/wix/Detox/pull/2231/files#diff-8c8eebd6512cc7aeed7d36a9bdc0b170R32).
=> Allow for setting rn-context load time in DetoxTest

docs/Introduction.Android.md
`binaryPath` is *not* the path that Detox should use for the binary.  Rather, Detox uses this as a base path and tries to transform it to determine its own test binary path via the internal function `getTestApkPath`.  This tripped me up and also a number of other users:
https://stackoverflow.com/questions/53984667/detox-app-could-not-be-found-did-you-run-gradlew-assembleandroidtest/63414420#63414420
https://stackoverflow.com/questions/58951816/detox-build-successful-but-detox-test-fails/63414275#63414275
Adding to troubleshooting here to try and help future users solve this more quickly.
---
=> Add binaryPath troubleshooting

.gitmodules, detox/ios/Detox.xcodeproj/project.pbxproj, detox/ios/Detox/Next/DetoxManager.swift, detox/ios/Detox/Next/Utilities/UIView+DetoxUtils.m, detox/src/artifacts/uiHierarchy/IosUIHierarchyPlugin.js, detox/src/artifacts/uiHierarchy/IosUIHierarchyPlugin.test.js, detox/src/artifacts/utils/temporaryPath.js, detox/src/artifacts/utils/temporaryPath.test.js, detox/src/client/AsyncWebSocket.js, detox/src/client/AsyncWebSocket.test.js, detox/src/client/Client.js, detox/src/client/Client.test.js, detox/src/client/actions/actions.js, detox/src/configuration/composeArtifactsConfig.js, detox/src/devices/Device.js, detox/src/devices/Device.test.js, detox/src/devices/drivers/DeviceDriverBase.js, detox/src/devices/drivers/ios/IosDriver.js, detox/src/devices/drivers/ios/SimulatorDriver.js, detox/src/devices/drivers/ios/SimulatorDriver.test.js, detox/src/utils/setUniqueProperty.js, detox/src/utils/setUniqueProperty.test.js, detox/test/e2e/19.crash-handling.test.js, detox/test/e2e/21.artifacts.test.js, detox/test/package.json
When an invocation error occurs, an attempt to dump view hierarchy will be attempted, and on success, the resulting URL will be placed in `viewHierarchyURL` in returned params.
New invoke command `captureViewHierarchy` has been added, where `viewHierarchyURL` is expected to hold the URL to place the view hierarchy. The URL must have “path/name.viewhierarchy” syntax.
Closes #2181
#2078
=> View hierarchy dumping on demand and on error

detox-cli/cli.js
Supplements #2278.
Fixes non-effective `PATH` modification on Windows by taking into the account the following platform quirk:
> The command lookup will be performed using options.env.PATH environment variable if passed in options object, otherwise process.env.PATH will be used. To account for the fact that Windows environment variables are case-insensitive Node.js will lexicographically sort all env keys and choose the first one case-insensitively matching PATH to perform command lookup. This may lead to issues on Windows when passing objects to env option that have multiple variants of PATH variable.
See more details: https://nodejs.org/api/child_process.html
=> fix(cli): case-insensitive PATH key on Win32

detox/src/utils/errorUtils.js
---
Just realized, when testing on a Windows laptop, that error stack traces use Unix path separator (`/`) nevertheless, so I've fixed both unit tests here and the production behavior too. This code is used for improving error stack traces, so they don't point to Detox internals but places in user e2e tests.
=> fix(windows): remove correctly internal stack traces

detox/test/android/app/src/androidTest/java/com/example/DetoxTest.java, detox/test/android/app/src/androidTest/java/com/example/TestButlerProbe.java
---
This isn't really essential for Detox itself, as test butler is hard-installed on the running device in each global setup (at least for the _test_ app). This is more of a reference for other projects. Nevertheless it's good practice to have, so keeping it nonetheless.
=> Restrict test-butler assertion to devices actually incorporating the TB service

detox/src/client/Client.js, detox/src/client/Client.test.js
---
Previously, `--debug-synchronization` was only triggered on `actions.Invoke()` commands. This PR adds support for debug sync over all slow websocket calls.
Still needs to polish over edge cases.
=> Debug sync will be activated on all WS calls, not only on invoke.

detox/ios/Detox/Actions/UIScrollView+DetoxActions.m, detox/src/ios/expectTwo.js, detox/src/ios/expectTwo.test.js
iOS: fix default scroll and ability to override params (NaN and null params were being deleted, they aren't anymore)
=> iOS: fix default scroll and ability to override params

detox/local-cli/test.js, detox/local-cli/utils/misc.js
---
In case if users call `detox test` in a direct way, i.e.: `node_modules/.bin/detox test ...`, it fixes errors like:
```
/bin/sh: mocha: command not found
```
=> hotfix(cli): backward compatible path handling

detox/src/artifacts/uiHierarchy/IosUIHierarchyPlugin.js, detox/src/artifacts/uiHierarchy/IosUIHierarchyPlugin.test.js
artifacts.plugins.uihierarchy is propogated to native, to make sure uiHierarchy is not created when not enabled.
=> feat(artifacts) artifacts.plugins.uihierarchy config is propogated to native

detox/local-cli/test.js, detox/local-cli/test.test.js, detox/src/devices/drivers/android/AndroidDriver.js, detox/src/devices/drivers/android/emulator/AVDValidator.js, detox/src/devices/drivers/android/emulator/AVDValidator.test.js, detox/src/devices/drivers/android/emulator/EmulatorDriver.js, detox/src/devices/drivers/android/emulator/EmulatorVersionResolver.js, detox/src/devices/drivers/android/emulator/EmulatorVersionResolver.test.js, detox/src/utils/environment.js, detox/src/utils/environment.test.js
=> Remove warning regarding Android parallel being experimental, add robust version check

detox/local-cli/utils/splitArgv.js, detox/package.json
---
Eliminates the need to explicitly install `jest-cli`.
Resolves `jest-cli` from `jest` npm package.
=> fix(jest): resolve jest-cli relatively to jest itself

detox/src/client/Client.js, detox/src/client/Client.test.js
---
Fixes flood of `currentStatus` messages when the app is really busy and cannot reply.
Each currentStatus request generates one extra currentStatus request, and that goes up quite fast.
Looks like a regression after https://github.com/wix/Detox/commit/41400bfc (kudos to @d4vidi for the investigation)
```
[09:17:40]W:		 [Phase: Tests] detox[3748] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND]  [90m{"type":"currentStatus","params":{},"messageId":63396} [39m
[09:17:40]W:		 [Phase: Tests] detox[3748] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND]  [90m{"type":"currentStatus","params":{},"messageId":63397} [39m
[09:17:40]W:		 [Phase: Tests] detox[3748] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND]  [90m{"type":"currentStatus","params":{},"messageId":63398} [39m
[09:17:40]W:		 [Phase: …
```
=> fix: prevent flooding currentStatus messages

detox/android/detox/src/main/java/com/wix/detox/espresso/DetoxMatcher.java, detox/android/detox/src/main/java/com/wix/detox/espresso/matcher/ViewMatchers.kt, detox/src/android/espressoapi/DetoxMatcher.js, detox/src/android/expect.js, detox/src/android/expect.test.js, detox/src/android/matcher.js, detox/src/ios/expectTwo.js, detox/src/ios/expectTwo.test.js, detox/test/e2e/04.assertions.test.js, detox/test/src/Screens/AssertionsScreen.js, docs/APIRef.Expect.md
---
Fixes #1972 by introducing an explicit expect-API for supporting anything toggle-able, such as option-switches and check-boxes.
=> Introduce expectation for matching toggleable widgets

detox/local-cli/test.test.js, detox/local-cli/utils/splitArgv.js
---
The recent refactor of `local-cli/test.js` in https://github.com/wix/Detox/pull/2269 has introduced the following bug concerning `-- <...direct passthrough args>` syntax. 
Expected:
```
> detox test ... e2e/mytest.js -- --forceExit
... jest --forceExit ... e2e/mytest.js
```
Actual:
```
> detox test ... e2e/mytest.js -- --forceExit
... jest ... -- --forceExit e2e/mytest.js
```
In other words, there should be just `--forceExit`, not `-- --forceExit` in this example.
Detox should not forward the double dash (`--`) itself, when this syntax is used.
=> fix(cli): double dash -- argv forwarding

detox/runners/jest/DetoxAdapterImpl.js, detox/src/artifacts/templates/plugin/WholeTestRecorderPlugin.js
---
When tests burst into failures on the very beginning in Jasmine, I saw a few errors which had to do with race conditions.
Hence, I decided why don't we fix that, to be on the safe side.
Bug 1 (in the Jest-Jasmine adapter):
```
FAIL  e2e/specs/owner/ChallengesScreen/challengesScreen.spec.ts
● Test suite failed to run
DetoxRuntimeError: Invalid test summary was passed to detox.beforeEach(testSummary)
Expected to get an object of type: { title: string; fullName: string; status: "running" | "passed" | "failed"; }
HINT: Maybe you are still using an old undocumented signature detox.beforeEach(string, string, string) in init.js ?
See the article for the guidance: https://github.com/wix/detox/blob/master/docs/APIRef.TestLifecycle.md
testSummary was: null
at …
```
=> fix: minor race condition bugs

detox/local-cli/test.js, detox/local-cli/test.test.js, detox/local-cli/utils/splitArgv.js
Resolves #1881.
E.g.:
```bash
detox test -c ios.sim.release -t hello.*tap
```
as expected, translates to:
```bash
configuration="ios.sim.release" ... jest ... --testNamePattern "hello.*tap"
```
instead of the former:
```bash
configuration="ios.sim.release" ... jest ...  --testNamePattern '^((?!:android:).)*$'  --testNamePattern "hello.*tap"
```
/cc @andy-zy
=> fix(jest): allow `-t, --testNamePattern` overriding

detox/local-cli/test.js, detox/local-cli/test.test.js, detox/package.json
---
Try running: `detox test -c ios.sim.release --testNamePattern="should tap"`, and instead of expected:
```bash
configuration="ios.sim.release" ... jest --config e2e/config.js --testNamePattern 'should tap' --maxWorkers 1 e2e
```
you actually get:
```bash
configuration="ios.sim.release" ... jest --config e2e/config.js --testNamePattern should tap --maxWorkers 1 e2e
```
All the other Detox native and forward arguments are prone to this very same issue.
This pull request aims to fix the incorrect behavior.
=> fix(cli): proper quoting args

detox/local-cli/test.js, detox/local-cli/test.test.js, detox/local-cli/utils/shellQuote.js, detox/package.json, detox/src/utils/pipeCommands.js, detox/src/utils/shellUtils.js, detox/src/utils/shellUtils.test.js
---
It appears that using `shell-quote` npm package in the most straightforward way is not really possible, due to Win32 integration bugs.
That's why I limited the current implementation to use the former Detox technique (escaping with single and double quotes), but I've modernized it a bit, so it is able to pass my updated test suite.
Also, there were a few tests that I had previously changed due to alternative `shell-quote` escaping implementation, so I am reverting them back to the norm.
=> fix(local-cli): lighter, cross-platform quoting

detox/local-cli/test.test.js, detox/src/utils/environment.test.js, detox/src/utils/errorUtils.test.js, detox/src/utils/shellUtils.js, detox/src/utils/shellUtils.test.js
---
Struggling here for the justice, to make sure our fellow contributors on Windows can run the unit tests with zero manual patches.
Also, the PR removes redundant `\` escaping on Windows (when using CMD.exe). I've overlooked this possibility in the initial PR for improving the escaping algorithm — unfortunately, had to split the table unit tests for escaping implementations for Shell and CMD.exe.
=> test(win32): unit tests should pass on Windows

detox/local-cli/test.test.js, detox/src/utils/argparse.js
---
The latest PR #2399 had issues on Windows, which slipped unnoticed, fortunately before the release. The `argparse` utils have been slightly reimplemented to correctly extract camelCased env vars along with DETOX_SNAKE_CASE ones on both Win32 and POSIX.
=> fix(win32): environment vars handling

detox/android/detox/src/main/java/com/wix/detox/config/DetoxIdlePolicyConfig.kt
---
Significantly increase the default (yet customizable) _native_ timeouts on Android: master timeout, idling resource timeout.
=> Longer native timeouts for Android

detox/android/detox/src/main/java/com/wix/detox/Detox.java, detox/android/detox/src/main/java/com/wix/detox/common/DetoxErrors.java, detox/android/detox/src/main/java/com/wix/detox/common/collect/PairsIterator.kt, detox/android/detox/src/main/java/com/wix/detox/common/proxy/MethodsSpy.kt, detox/android/detox/src/main/java/com/wix/detox/common/proxy/SpyingInvocationHandler.kt, detox/android/detox/src/main/java/com/wix/detox/espresso/UiAutomatorHelper.java, detox/android/detox/src/main/java/com/wix/detox/espresso/UiControllerSpy.kt, detox/android/detox/src/main/java/com/wix/detox/espresso/action/DetoxMultiTap.kt, detox/android/detox/src/main/java/com/wix/detox/espresso/common/DetoxViewConfiguration.kt, detox/android/detox/src/main/java/com/wix/detox/espresso/common/utils/UiControllerUtils.kt, detox/android/detox/src/main/java/org/joor/Reflect.java, detox/android/detox/src/test/java/com/wix/detox/common/collect/PairsIteratorSpec.kt, detox/android/detox/src/test/java/com/wix/detox/common/proxy/MethodsSpySpec.kt, detox/android/detox/src/test/java/com/wix/detox/espresso/action/DetoxMultiTapSpec.kt, detox/test/android/app/src/main/java/com/example/NativeModulePackage.java, detox/test/android/app/src/main/java/com/example/SluggishTextTextViewManager.java, detox/test/e2e/03.actions.test.js, detox/test/e2e/drivers/actions-driver.js, detox/test/src/Screens/ActionsScreen.js
---
Fixes #2207 by spying over Espresso's `UiController` (or actually over the internals of `UiControllerImpl: `UiControllerImpl>EventInjector>EventInjectionStrategy`), and monitoring the inject-method call timestamps.
This time-stamps are utilized (in order to be able to fail the tap if it turns "long" - see #2207), by recording them in the taps handler and then post-processing there in order to calculate down/up event deltas, comparing to Android's long-tap time threshold.
The reason this works is because `UiController` always injects the last event syncrhonously - waiting for the injection to complete, and thus the global beginning and ending timestamps truly depict what happened in between.
=> Introduce tap-time verification through ui-controller swizzling

detox/android/detox/src/main/java/com/wix/detox/DetoxActionHandlers.kt, detox/android/detox/src/main/java/com/wix/detox/common/ErrorUtils.kt, detox/android/detox/src/test/java/com/wix/detox/DetoxActionHandlersSpec.kt, detox/src/client/Client.test.js, detox/src/client/actions/actions.js, detox/src/utils/__mocks__/logger.js, detox/test/e2e/03.actions.test.js
---
Often enough, errors sent from the device's native fail to convey proper meaning to test user. Usually (perhaps always), this happens because the test runner side (JS) only logs the top-most wrapping error, and not the very original one, specified by the error's `cause` field (recursively).
This attempts at fixing that by drilling down to the root cause of errors, before sending them to the test-runner side of Detox. As an example of why this works, it is verified in the recently added slow-tap e2e test in the actions suite.
=> Improve content of native errors shown on the JS test runner

detox/android/detox/src/main/java/com/wix/detox/espresso/UiAutomatorHelper.java
---
A tiny fix for a regression caused by 9dd9635f. Error - coming from one-app, looks something like this:
```
10-26 03:26:58.112  4153  4153 E detox   : java.lang.NoSuchMethodException: No similar method loopMainThreadUntilIdle with params [class java.lang.Long] could be found on type class androidx.test.espresso.base.UiControllerImpl.
10-26 03:26:58.112  4153  4153 E detox   : 	at org.joor.Reflect.similarMethod(Reflect.java:491)
10-26 03:26:58.112  4153  4153 E detox   : 	at org.joor.Reflect.call(Reflect.java:421)
10-26 03:26:58.112  4153  4153 E detox   : 	at com.wix.detox.espresso.UiAutomatorHelper$2.run(UiAutomatorHelper.java:64)
10-26 03:26:58.112  4153  4153 E detox   : 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
10-26 03:26:58.112 …
```
=> Fix regression caused by 9dd9635f

detox/src/utils/exec.js, detox/src/utils/exec.test.js, detox/src/utils/retry.js, detox/src/utils/retry.test.js
---
Associated with the ongoing work on Genymotion-Cloud integration (#2429), where logging of command failures, and better-retry control, are required.
In particular, in the case where a command is retried due to repeated failures, instead of having an obscure log - simply showing the command and an overdue failure, as is today (in trace level):
```
detox[18311] DEBUG: [exec.js/EXEC_CMD, #2] "gmsaas" --format compactjson instances start --stop-when-inactive 5974e92c-5ec6-4576-a93e-2ceec4338f0b "Detox-1603890039526.4004"
(log stuck for ~1.5m... :-/)
detox[18311] ERROR: [exec.js/EXEC_FAIL, #2] ""gmsaas" --format compactjson instances start --stop-when-inactive 5974e92c-5ec6-4576-a93e-2ceec4338f0b "Detox-1603890039526.4004"" failed with code = 4, stdout and stderr: …
```
=> Expand retry() API and improve exec() retry-logging

detox/android/detox/src/main/java/com/wix/detox/espresso/DetoxAction.java, detox/android/detox/src/main/java/com/wix/detox/espresso/DetoxViewActions.java, detox/android/detox/src/main/java/com/wix/detox/espresso/action/DetoxMultiTap.kt, detox/android/detox/src/main/java/com/wix/detox/espresso/action/DetoxSingleTap.kt, detox/android/detox/src/main/java/com/wix/detox/espresso/action/DetoxTypeTextAction.java, detox/android/detox/src/main/java/com/wix/detox/espresso/action/RNClickAction.java, detox/android/detox/src/test/java/com/wix/detox/espresso/action/DetoxMultiTapSpec.kt, detox/src/android/espressoapi/DetoxAction.js, detox/src/android/espressoapi/DetoxViewActions.js, detox/src/android/expect.js, detox/src/android/expect.test.js, detox/test/e2e/03.actions.test.js, detox/test/e2e/drivers/actions-driver.js
---
Allow for passing a `{ strict: false }` argument to the various element tapping API's, in order to hold back error checking. Currently, this includes only the tap turning into a long-tap, validation.
=> Introduce strict-mode to taps

detox/android/detox/src/main/java/com/wix/detox/common/DetoxLog.kt, detox/android/detox/src/main/java/com/wix/detox/espresso/DetoxAction.java, detox/android/detox/src/main/java/com/wix/detox/espresso/DetoxViewActions.java, detox/android/detox/src/main/java/com/wix/detox/espresso/action/DetoxMultiTap.kt, detox/android/detox/src/main/java/com/wix/detox/espresso/action/DetoxSingleTap.kt, detox/android/detox/src/main/java/com/wix/detox/espresso/action/DetoxTypeTextAction.java, detox/android/detox/src/main/java/com/wix/detox/espresso/action/RNClickAction.java, detox/android/detox/src/test/java/com/wix/detox/espresso/action/DetoxMultiTapSpec.kt, detox/src/android/espressoapi/DetoxAction.js, detox/src/android/espressoapi/DetoxViewActions.js, detox/src/android/expect.js, detox/src/android/expect.test.js, detox/test/e2e/03.actions.test.js, detox/test/e2e/drivers/actions-driver.js
---
Revert #2438 - kill 'strict mode' for now, and make tap2long-tap validation a soft one (i.e. warning instead of error).
=> Disable tap2longtap err

docs/Introduction.Android.md
---
Fixing typo (`acheived ` -> `achieved`) and using more consistent Android file paths, since other parts of the documentation used `android/... `
=> Fix typo; More consistent file paths (android/...)

detox/src/devices/drivers/android/genycloud/services/GenyInstanceNaming.js, detox/src/devices/drivers/android/genycloud/services/GenyInstanceNaming.test.js
Apply the suggestion by @noomorph as to utilize `JEST_WORKER_ID` for naming genycloud instances more clearly
=> Make instance names more concise with jest

detox/android/detox/src/main/java/com/wix/detox/common/DetoxErrors.java, detox/android/detox/src/main/java/com/wix/detox/espresso/DetoxAction.java, detox/android/detox/src/main/java/com/wix/detox/espresso/common/annot/MotionDefs.kt, detox/android/detox/src/main/java/com/wix/detox/espresso/scroll/SwipeHelper.kt, detox/android/detox/src/main/java/com/wix/detox/espresso/utils/Vector2D.kt, detox/android/detox/src/test/java/com/wix/detox/espresso/scroll/SwipeHelperSpec.kt, detox/android/detox/src/test/java/com/wix/detox/espresso/utils/Vector2DSpec.kt, detox/android/gradle/wrapper/gradle-wrapper.properties, detox/ios/Detox/Actions/NSObject+DetoxActions.h, detox/ios/Detox/Actions/NSObject+DetoxActions.m, detox/ios/Detox/Actions/UIScrollView+DetoxActions.h, detox/ios/Detox/Invocation/Action.swift, detox/ios/Detox/Invocation/Element.swift, detox/ios/Detox/Utilities/UIView+DetoxUtils.m, detox/src/android/espressoapi/DetoxAction.js, detox/src/android/expect.js, detox/src/android/expect.test.js, detox/src/ios/expectTwo.js, detox/src/ios/expectTwo.test.js, detox/src/ios/expectTwoApiCoverage.test.js, detox/src/utils/__snapshots__/assertArgument.test.js.snap, detox/src/utils/assertArgument.js, detox/src/utils/assertArgument.test.js, detox/test/android/gradle/wrapper/gradle-wrapper.properties, detox/test/e2e/03.actions.test.js, docs/APIRef.ActionsOnElement.md
---
Signature:
```js
/*
* @param { 'up' | 'down' | 'left' | 'right' } direction - Direction to swipe
* @param { 'fast' | 'slow' } speed
* @param {number} [normalizedSwipeOffset] - swipe amount relative to the screen width/height
* @param {number} [normalizedStartingPointX] - X coordinate of swipe starting point, relative to the view width
* @param {number} [normalizedStartingPointY] - Y coordinate of swipe starting point, relative to the view height
*/
function swipe(direction, speed, normalizedSwipeOffset = NaN, normalizedStartingPointX = NaN, normalizedStartingPointY = NaN) { ... }
```
Usage:
```js
await element(by.id('ScrollView161')).swipe('up');
await element(by.id('ScrollView161')).swipe('down', 'slow');
await element(by.id('ScrollView161')).swipe('left', 'fast', …
```
=> Add x,y coordinate support for swipe action

detox/src/devices/Device.js, detox/src/devices/drivers/android/genycloud/GenyCloudDriver.js, detox/src/devices/drivers/android/genycloud/GenyCloudDriver.test.js, detox/src/devices/drivers/android/genycloud/exec/GenyCloudExec.js, detox/src/devices/drivers/android/genycloud/exec/GenyCloudExec.test.js, detox/src/devices/drivers/android/genycloud/services/GenyAuthService.js, detox/src/devices/drivers/android/genycloud/services/GenyAuthService.test.js, detox/src/utils/environment.js, detox/src/utils/environment.test.js
As per insightful notes by @noomorph - added a validation of that `gmsaas` is in path (so as to avoid pointless retires to take place in trying to execute initial setup command, resulting in obscure, unfriendly errors).
Actually, with genymotion's SaaS, there are two things to handle before enabling access to the cloud:
1. Setting up `gmsaas` in path
2. Logging in
This PR effectively handles both aspects.
=> Prevalidate gmsaas: binary and auth

detox/src/utils/logger.js
---
When something wrong happens, we usually go to the logs.
When things mostly go alright, we don't turn on verbose logging mode.
At the moment, verbosity in log artifacts is tightly coupled to the verbosity of CLI output.
This PR suggests using always `loglevel=trace` for log artifacts, presuming that a user will stick to `--record-logs failing` in the majority of cases. If it is `--record-logs all` — better to take care of CI storage. ;)
=> feat(artifacts): always loglevel=trace for log artifacts

detox/android/detox/proguard-rules-app.pro, detox/android/detox/proguard-rules.pro, detox/android/detox/src/main/java/com/wix/detox/reactnative/helpers/RNHelpers.kt, detox/android/detox/src/main/java/com/wix/detox/reactnative/idlingresources/AsyncStorageIdlingResource.kt, detox/test/android/app/proguard-rules.pro, docs/Introduction.Android.md, examples/demo-react-native/android/app/build.gradle, examples/demo-react-native/android/app/proguard-rules.pro, examples/demo-react-native/android/app/src/main/java/com/example/MainApplication.java, examples/demo-react-native/android/build.gradle, examples/demo-react-native/android/gradle.properties, examples/demo-react-native/android/settings.gradle, examples/demo-react-native/package.json
Resolves #2431.
1. Adds ProGuard/R8 rules to Detox' app-associated rules-set (aka `proguard-rules-app.pro`) so as to retain interrogated React-Native code.
2. Turns on obfuscation in the example app, to consistently prove that the rules-set is sufficient.
3. Elaborates on ProGuard+Detox in the Android setup doc.
cc @GEllickson-Hover - you've been credited in the docs.
=> Fix Detox' proguard rules-set to support obfuscating apps, with docs

.github/CODEOWNERS, detox/ios/Detox/Invocation/Element.swift, detox/ios/Detox/Utilities/NSObject+DetoxUtils.m, detox/ios/Detox/Utilities/NSObject+DontCrash.h, detox/ios/Detox/Utilities/NSObject+DontCrash.m
=> Fixed crash in Google Maps SDK, caused by exposing a `text` property on every object

detox/src/devices/drivers/android/genycloud/GenyCloudDriver.js, detox/src/devices/drivers/android/genycloud/GenyCloudDriver.test.js, detox/test/e2e/global-teardown.js
Restore previously reverted call to our definition of Geny-cloud "global cleanup" (i.e. the driver method that stops all associated instances).
This was reverted a while ago because it has caused issues with other platforms, running on machines where `gmsaas` was not installed.
=> Restore call to Genycloud global cleanup through detox global cleanup

detox/src/devices/DeviceRegistry.js, detox/src/devices/DeviceRegistry.test.js, detox/src/devices/drivers/android/genycloud/GenyCloudDeviceAllocator.js, detox/src/devices/drivers/android/genycloud/GenyCloudDeviceAllocator.test.js, detox/src/devices/drivers/android/genycloud/GenyCloudDriver.js, detox/src/devices/drivers/android/genycloud/GenyCloudDriver.test.js, detox/src/devices/drivers/android/genycloud/GenyCloudInstanceHandle.js, detox/src/devices/drivers/android/genycloud/services/dto/GenyInstance.js, detox/src/devices/drivers/android/genycloud/services/dto/GenyRecipe.js
Improve Genymotion leakage warnings by including instance names, in addition to meaningless UUID's.
This incorporates 2 main things:
1. Enhancing the device registry such that it would allow for managing object, and not just strings (!)
2. Managing the device cleanup registry using objects, containing both instance `uuid`'s _and_ names (thus allowing for the instance names to be logged, eventually, in global-cleanup).
Related to #2429.
=> Improve Genymotion leakage warning by including instance names

detox/src/devices/drivers/android/genycloud/GenyCloudDriver.js, detox/src/devices/drivers/android/genycloud/GenyCloudDriver.test.js, detox/src/devices/drivers/android/genycloud/exec/GenyCloudExec.js, detox/src/devices/drivers/android/genycloud/exec/GenyCloudExec.test.js, detox/src/devices/drivers/android/genycloud/services/GenyInstanceLookupService.js, detox/src/devices/drivers/android/genycloud/services/GenyInstanceLookupService.test.js
In `gmsaas` version `1.6.0`, as per Wix' request, a reach onto the `getInstance` endpoint via `gmsaas` was introduced through the `gmsaas instances get <uuid>` command. This PR plugs that in into the driver by reimplementing lookup-service' `getInstance()`, which previously fetched _all_ instances and manually filtered them (which wasn't scalable - hence the point in all this).
This comes alongside a preliminary check in the driver's `prepare()` of that the `gmsaas` executable is sufficiently new on the host machine.
=> Make usage of new gmsaas getInstance 'endpoint' of 1.6.0

detox/src/devices/drivers/ios/IosDriver.js, detox/src/devices/drivers/ios/SimulatorDriver.js
---
Resolves #2162 for `ios.none` configuration.
=> fix(ios): disable artifacts plugins with incomplete support

detox/src/devices/drivers/ios/tools/AppleSimUtils.js
Fix an issue introduced in #2540, where `--args` was dropped from `xcrun simctl launch`.
Missing: some sort of testing for this, to make sure args are being passed correctly.
=> Added back --args to xcrun simctl launch, was wrongly removed in #2540

detox/src/DetoxExportWrapper.js, detox/src/devices/DeviceRegistry.js, detox/src/devices/DeviceRegistry.test.js, detox/src/devices/drivers/android/genycloud/GenyCloudDriver.js, detox/src/devices/drivers/android/genycloud/GenyCloudDriver.test.js, detox/src/index.test.js, detox/test/e2e/global-setup.js
Part of the ongoing work on Genymotion-cloud support (#2429).
Warn about Genycloud instances leakage in case test suite execution is terminated prematurely (e.g. due to the user hitting a CTRL+C, or a kill signal). That is to take place on top of the standard (controlled) cleanup performed by Detox following a proper execution of the test suites down to the very end.
- This relates mostly to users cancelling their jobs manually while running test locally.
- It is not related to whether the tests in the suite have failed: A test suite failure still undergoes a proper cleanup.
- It will _not_ run in case of a CI agent's sudden shutdown.
=> Warn about Genycloud instances leakage in case of abrupt terminations

detox/src/devices/DeviceRegistry.js, detox/src/devices/DeviceRegistry.test.js, detox/src/devices/drivers/android/genycloud/GenyCloudDriver.js, detox/src/devices/drivers/android/genycloud/GenyCloudDriver.test.js, detox/src/devices/drivers/android/genycloud/services/GenyInstanceLookupService.js, detox/src/devices/drivers/android/genycloud/services/GenyInstanceLookupService.test.js, detox/src/devices/drivers/ios/SimulatorDriver.js, detox/src/devices/drivers/ios/SimulatorDriver.test.js
Expand `DeviceRegistry` so as to be made capable of storing device-handles of 3 possible types, rather than just ~2:
- Explicit strings
- Plain objects (functions stripped away)
- New: Class instances.
That is achieved by making changes on two levels:
- Reimplementation of `DeviceRegistry`'s modification methods (e.g. device allocation / dispose) - also `includes`, so as to sanitize (i.e. strip-off functions, any class meta data, etc.) the given handle before using it. This is a non-API-breaking change.
- Change of registry whole-state query methods, namely `getRegisteredDevices()`, `readRegisteredDevices()` and `readRegisteredDevicesUNSAFE()` such that instead of returning an array, they'd return an abstraction (`DeviceHandlesList` class) that's different in two ways:
- It allows for a …
=> DeviceRegistry to support all handle types

detox/ios/Detox/Invocation/Element.swift
---
Fixes a small typo in the UIScrollView visibility error message.
“UISrollView” -> “UIScrollView”
=> Fix “UISrollView” typo

detox/local-cli/test.test.js, detox/local-cli/utils/testCommandArgs.js, detox/src/configuration/composeSessionConfig.js, detox/src/configuration/composeSessionConfig.test.js, docs/APIRef.DetoxCLI.md
---
The resurrection of the pre-existing PR, originally by @rotemmiz.
* Updated the docs
* Added unit tests
* Use `--debug-synchronization false` instead of the original `off`, to be in line with `yargs` logic, which already processes `true` value (as 3000, due to compatibility reasons).
=> feat(config): --debug-synchronization=10000 by default

detox/index.d.ts, detox/src/devices/Device.js, detox/src/devices/Device.test.js, detox/test/e2e/22.launch-args.test.js, docs/APIRef.DeviceObjectAPI.md
I've decided to take a step forward and reduce the added complexity in e2e's of large-scale apps (as Wix' internal ones) in trying to prepare and set up suitable app launch arguments.
The typical use case is of modules settings up mock servers, in particular.
Some mock servers are provided by frameworks, while some by modules/apps, which are separate - yet all must be aggregated into the same call to `launchApp({ launchArgs: { ... } })`. This API allows the separation to be properly retained, and eliminate hacks such as `launchApp` swizzling, currently used to overcome this.
_This is in a way both a PR and a discussion, BTW. I've went ahead and implemented this ahead of time because there's very little production code involved._
=> Introduce device.setLaunchArg()

detox/index.d.ts, detox/src/devices/Device.js, detox/src/devices/Device.test.js, detox/src/devices/LaunchArgs.js, detox/src/devices/LaunchArgs.test.js, detox/test/detox.config.js, detox/test/e2e/22.launch-args.test.js, docs/APIRef.Configuration.md, docs/APIRef.DetoxCLI.md, docs/APIRef.DeviceObjectAPI.md, docs/APIRef.LaunchArgs.md, docs/Guide.Mocking.md
A rewrite of #2618, #2613, introducing app launch-args editing according to the following syntax:
```js
device.appLaunchArgs.modify({
newArg: 'aValue',
existingArgToOverride: 'newValue',  
existingArgToDelete: undefined,
});
```
and there's also:
```js
device.appLaunchArgs.reset();
device.appLaunchArgs.get();
```
In the future, we expect to support multiple apps according to the following terms:
- In a multi-apps environment, launch-args will be managed per each, separately (following the equivalent logic of the global Detox config).
- Arguments will be available via the same API, in the form of `device.appLaunchArg('app-name')`.
- In case `app-name` isn't explicitly specified -- will modify the currently "selected" app.
=> Introduce launch-args modification API

README.md, detox/local-cli/test.js, detox/runners/jest/SpecReporterImpl.js, detox/runners/jest/WorkerAssignReporterImpl.js, detox/src/devices/drivers/ios/SimulatorDriver.js, detox/src/devices/drivers/ios/tools/AppleSimUtils.js, detox/src/server/DetoxServer.js, detox/src/utils/customConsoleLogger.js, detox/src/utils/customConsoleLogger.test.js, detox/src/utils/logger.js
This will be the default output:
Instead of:
=> Clean up default log printing to prevent clutter

detox/android/detox/src/main/java/com/wix/detox/DetoxActionHandlers.kt
---
It seems that there was a quick'n'dirty reimplementation, and by accident nobody remembered that Android native implementation sends legacy format of `currentStatusResult`.
Hereby I return the historical justice, although, of course, the best solution is to eventually align the JSON formats for `currentStatusResult` for both iOS and Android.
Before:
After:
=> Fix currentStatus logging on Android

detox/index.d.ts, detox/src/android/AndroidExpect.test.js, detox/src/android/matchers/index.js, detox/src/ios/expectTwo.js, detox/src/ios/expectTwo.test.js, detox/test/e2e/28.webview.test.js, detox/test/types/detox-global-tests.ts
---
Per request of @OrenZak, I've renamed `by.html` matchers to `by.web`, and `by.html.selector` now is `by.web.cssSelector`.
=> code: rename by.html to by.web

detox/local-cli/test.test.js, detox/src/Detox.js, detox/src/Detox.test.js, detox/src/configuration/composeDeviceConfig.js, detox/src/configuration/composeDeviceConfig.test.js, detox/src/devices/DriverRegistry.js, detox/src/devices/DriverRegistry.test.js, detox/src/errors/DetoxConfigErrorComposer.js, detox/src/errors/DetoxConfigErrorComposer.test.js, detox/src/errors/__snapshots__/DetoxConfigErrorComposer.test.js.snap
---
```
DetoxConfigError: Invalid device type "android.apk" inside your configuration.
HINT: Did you mean to use one of these?
* ios.simulator
* ios.none
* android.attached
* android.emulator
* android.genycloud
P.S. If you intended to use a third-party driver, please resolve this error:
Cannot find module 'android.apk'
Please check your Detox config at path:
/Users/yaroslavs/Projects/wix/Detox/detox/test/.detoxrc.json
{
configurations: {
debug: {
binaryPath: 'C:/Users/adema/Desktop/myMoney/android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk',
build: 'cd android && ./gradlew build assembleDebug ' +
'assembleAndroidTest -DtestBuildType=debug',
type: 'android.apk',
devices: {
emulator: [Object]
}
}
}
}
```
P. S. @Ademar-SJ, this is the error message …
=> fix(config): throw err on invalid device type

docs/APIRef.DeviceObjectAPI.md
---
**Description:** Adding this note will make it clearer for future readers of the documentation that this external library is no longer working.
I saw that some people are already working on a proper solution in #1371, so I am wondering if it is appropriate to reference this issue in the documentation?
=> Add note about fbsimctl deprecation

detox/local-cli/cli.js, detox/runners/jest-circus/environment.js, detox/src/errors/DetoxRuntimeError.js, detox/src/errors/DetoxRuntimeError.test.js
---
* For thrown `DetoxRuntimeError` errors we'll be printing `err.message`.
* For other errors (except `child_process.execSync()` "Command failed" errors) we'll be printing `err.stack`, so that any unhandled errors contain more details and we can fix them.
* For unhandled non-error values, we'll be using `util.inspect()`.
**Examples:**
Before:
After:
Regression testing (there should be no error stacks for known messages):
=> fix: better error stacks for unhandled errors

detox/src/utils/argparse.js, detox/src/utils/argparse.test.js, detox/src/utils/logger.js
---
It appears that non-`detox test` commands do not really react to `-l` shorthand alias for `--loglevel`.
For example, `detox run-server` – it is confusing that you cannot start it in a standalone mode with `--loglevel trace` when required.
It is easy to show that on the example with INFO/WARN levels.
Before (incorrect, because WARN level is higher than INFO):
After (correct, the log level now allows only ERROR and WARN messages):
=> fix(logger): consider also -l, the alias for --loglevel

detox/src/devices/drivers/android/genycloud/exec/GenyCloudExec.js, detox/src/devices/drivers/android/genycloud/exec/GenyCloudExec.test.js, detox/src/utils/exec.test.js
As per request from Genymobile, adding `detox` as the (default) user-agent extra-data for requests sent out via Detox.
The actual value can be overridden by a user by setting `GMSAAS_USER_AGENT_EXTRA_DATA` themselves, before invoking detox.
Relates to #2655.
=> Passthrough or set user-agent to gmsaas

detox/src/configuration/__mocks__/configuration/badconfig/detox.config.js, detox/src/configuration/index.js, detox/src/configuration/loadExternalConfig.js, detox/src/configuration/loadExternalConfig.test.js
---
This is a preparation towards extendable presets - now resolving Detox config paths via Node.js resolution mechanism.
Legacy configuration paths will be getting a warning:
```
Cannot resolve Detox config path by using Node.js require() mechanism:
require("node_modules/my-preset/index.js")
Detox now will resort to legacy filesystem-based path resolution.
Please fix your config path, so it conforms to `require(modulePath)` resolution.
```
Also, here we've got a fix.
Now Detox will be reporting correct errors when trying to evaluate something erroneous in a user-created JS (not JSON) Detox config. Previously, we incorrectly handled `Cannot find module` error. Why? So, if there was an inner `require` that failed, we were handling it like the user had provided an incorrect …
=> fix: use Node.js resolution for Detox config paths

detox/index.d.ts
iOS 14 introduced a new user tracking permission. 
AppleSimulatorUtils added support for this permission on [v0.9](https://github.com/wix/AppleSimulatorUtils/releases/tag/0.9).
I've added the missing definition to enable the use of this permission to `DevicePermissions` and the related `type`
=> Adding UserTracking permission

detox/src/client/AsyncWebSocket.js, detox/src/client/AsyncWebSocket.test.js, detox/src/client/Client.js, detox/src/client/Client.test.js, detox/src/client/InflightRequest.js, detox/src/client/__snapshots__/AsyncWebSocket.test.js.snap, detox/src/devices/Device.js
1. Resolves the edge case, when the app does not respond to `cleanup` action at all, hence it breaks the entire Jest + Detox cleanup phase. Technically, I am adding a 5s graceful period before we reject the pending `cleanup` request and go further in our `detox.cleanup()` routine.
2. `client.cleanup()` now theoretically cannot throw an error now. That's important if we want to finish properly the outer  `detox.cleanup()`.
3. Also, here I fix an incorrect app PID saving (it is prescribed to run too late, only after the app responds to "isReady"). After the fix, I am able to verify the existing PID (=> app is running) even in cases when the app is not eager to respond it is ready. Not entirely related to this PR (although it was relevant in the first commit with the first implementation, …
=> fix: stabilize stuck cleanup

detox/android/detox/build.gradle, detox/android/detox/src/testFull/java/com/wix/detox/common/proxy/MethodsSpySpec.kt
Apparently, non-Spek unit tests (Android) were not executed by gradle (e.g. in commands such as `./gradle testFullReleaseUnitTest`).
See https://github.com/spekframework/spek/issues/232#issuecomment-610732158
=> Run non-Spek Android unit tests

detox/src/server/DetoxConnection.js, detox/src/server/DetoxServer.js, detox/src/server/DetoxServer.test.js, detox/src/server/__tests__/__snapshots__/server-integration.test.js.snap, detox/src/server/__tests__/server-integration.test.js
Adds a new event:
```
detox[35774] DEBUG: [WSS_CREATE] Detox server listening on localhost:64680...
detox[35774] DEBUG: [WSS_CONNECTION, #64681] registered a new connection.
detox[35774] TRACE: [WS_OPEN] opened web socket to: ws://localhost:64680
detox[35774] TRACE: [WS_SEND] {"type":"login","params":{"sessionId":"23d777b4-af00-6d1a-e59e-150c95b51006","role":"tester"},"messageId":0}
detox[35774] TRACE: [WSS_GET_FROM, #64681] {"type":"login","params":{"sessionId":"23d777b4-af00-6d1a-e59e-150c95b51006","role":"tester"},"messageId":0}
detox[35774] TRACE: [SESSION_CREATED] created session 23d777b4-af00-6d1a-e59e-150c95b51006
detox[35774] TRACE: [WSS_SEND_TO, #tester] {"type":"loginSuccess","params":{"testerConnected":true,"appConnected":false},"messageId":0}
detox[35774] TRACE: …
```
=> fix(logging): add missing log call for a new connection

docs/Guide.Mocking.md
In this pull request, I have improved the mocking guide slightly. Due to the way it was previously worded, I completely skipped step 1 as I assumed it was not relevant for me as I am using a modern version of RN. Had I read step 1 in more detail, I would have seen that I needed to follow this step. This change makes the instructions easier to consume to prevent confusion over the RN versions.
---
=> Improve mocking guide instructions

detox/local-cli/test.js, detox/local-cli/utils/testCommandArgs.js
- This pull request fixes #2729 
In this pull request, I have updated the messages produced by the CLI with respect to usage of `--workers` such that it would not show an iOS-only constraint.
---
=> Remove 'iOS only's from CLI associated with workers arg

detox/test/android/app/build.gradle, detox/test/e2e/global-setup.js
- This pull request addresses the issue described here: #2734
In this pull request, I have made the test-butler util-APK dynamic downloading take place from maven-central instead of bintray.
---
=> Get test-butler from maven-central, upgrade to v2.2.1

detox/test/package.json
- This pull request closes #2749.
In this pull request, I have increased the number of concurrent simulators running on our internal CI (Detox' self-test app) from 3 to 4.
This comes after some research, which has empirically showed the following:
- With 3 workers, total tests exec time is 7-7.5min
- With 4 workers, total tests exec time decreases to ~6:40
- With more than 4 workers (even just 5), the total tests exec time increases back up.
The original intent was to try to elevate the new tech introduced in DetoxSync, which should allow for this kind of an improvement.
The intermediate conclusion from this, I therefore believe, is that the benefits of DetoxSync's asynchronousity only shine when the executing machine is powerful enough. Of course, this is premature - we will have to …
=> Increase concurrent simulators count on CI

detox/src/devices/drivers/android/genycloud/exec/GenyCloudExec.js, detox/src/devices/drivers/android/genycloud/exec/GenyCloudExec.test.js
- This pull request addresses the issue described here: #2655.
In this pull request, I have removed retries for the `gmsaas instance start` command.
---
=> Cancel retries for the gmsaas instance start command

detox/index.d.ts
In this pull request, I have added the type for the new pinch function and added the deprecated label to the old one. This isn't really a feature or enhancement or bugfix, but I'm using typescript with the project and noticed it was wrong, so I figured I'd contribute the fix back.
=> fix: fix pinch types

detox/package.json, detox/src/devices/drivers/android/AndroidDeviceAllocation.js, detox/src/devices/drivers/android/AndroidDeviceLauncher.js, detox/src/devices/drivers/android/emulator/EmulatorDriver.js, detox/src/devices/drivers/android/emulator/helpers/EmulatorDeviceAllocation.js, detox/src/devices/drivers/android/emulator/helpers/EmulatorDeviceAllocation.test.js, detox/src/devices/drivers/android/emulator/helpers/EmulatorLauncher.js, detox/src/devices/drivers/android/emulator/helpers/EmulatorLauncher.test.js, detox/src/devices/drivers/android/genycloud/GenyCloudDriver.js, detox/src/devices/drivers/android/genycloud/GenyCloudDriver.test.js, detox/src/devices/drivers/android/genycloud/helpers/GenyCloudInstanceAllocation.js, detox/src/devices/drivers/android/genycloud/helpers/GenyCloudInstanceAllocation.test.js, detox/src/devices/drivers/android/genycloud/helpers/GenyCloudInstanceLauncher.js, detox/src/devices/drivers/android/genycloud/helpers/GenyCloudInstanceLauncher.test.js
I've found this while working on redefining the concept of a `DeviceId` throughout our JS framework, as a tech debt left from the work on Genymotion (see #2655):
In the context of Android drivers, the terms 'cleanup' and 'shutdown' were (semantically) wrongly interpreted inside the related delegate (i.e. `EmulatorDeviceAllocation` class). While the implementation was correct, the associated code was simply misplaced inside it.
In this pull request, I have reorganized `EmulatorDeviceAllocation` such that the code inside `deallocateDevice()` would in fact simply have it removed from the device registry, instead of shutting it down altogether. The latter was relocated onto a new method in an existing class: `EmulatorLauncher.shutdown()`.
UPDATE: I've done the same for Genymotion.
---
> _For …
=> Reorganize roles in Emu delegates to match cleanup vs. shutdown

detox-cli/cli.js, detox-cli/package.json, detox/package.json, detox/src/devices/drivers/android/genycloud/GenyCloudDriver.js
- This pull request resolves the issue described here: https://github.com/wix/Detox/issues/2750
In this pull request, I have:
* added an emergency exit when `detox-cli` detects itself running in a non-global mode:
* made all the error messages red (with `chalk`):
* fixed `semver` npm resolution issue on a bare project with Detox installed
* updated `detox-cli/package.json` with the up-to-date information and purged unused dependencies (`commander`, `minimist`, etc...)
=> fix(detox-cli): infinite loop if locally installed

detox/test/package.json
In this pull request, I have temporarily changed the demo-app's `react-native-webview` dependency specs to use version `11.4.4` specifically, due to recent build-breaking changes introduced in one of the [newer version](https://github.com/react-native-webview/react-native-webview/releases) (Versions `11.4.5`, and then `11.4.6` through `11.6.1` seemed to have been released in approximately the same recent time frame, and they are all broken. `11.4.6` Seems to be the particular culprit, at a glance, comparing with the error details).
The build error is as follows:
```
14:44:14 > Task :react-native-webview:compileReleaseJavaWithJavac FAILED
14:44:14 /home/jenkins/.jenkins/workspace/detox-android-63-x-master/detox/test/node_modules/react-native-webview/android/src/main/java/com/reactnativecomm …
```
=> Lock react-native-webview's verison in test-proj, temporarily

detox/src/devices/DeviceRegistry.js, detox/src/devices/DeviceRegistry.test.js, detox/src/devices/drivers/android/genycloud/GenyCloudDriver.js, detox/src/devices/drivers/android/genycloud/GenyCloudDriver.test.js, detox/src/devices/drivers/android/genycloud/GenyCloudInstanceHandle.js, detox/src/devices/drivers/android/genycloud/helpers/GenyCloudInstanceLauncher.js, detox/src/devices/drivers/android/genycloud/helpers/GenyCloudInstanceLauncher.test.js, detox/src/devices/drivers/android/genycloud/services/GenyInstanceLookupService.js, detox/src/devices/drivers/android/genycloud/services/GenyInstanceLookupService.test.js, detox/src/devices/drivers/ios/SimulatorDriver.js, detox/src/devices/drivers/ios/SimulatorDriver.test.js
- This pull request is associated with the issue described here: #2655.
In this pull request, I have reworked the device-registry implementation such that instead of allowing for the holding of objects (rather than plain strings as ID's), it now allows for storing ID's (strings) as DB-like keys, alongside associated data (arbitrary types).
The reason for ever allowing for objects storing was to support Genycloud, and it was a mistake. The main reason was that on top of holding an instance' UUID, we want to also have its name as meta-data, for proper logging during global tear-down.
Allowing for objects in device-registry is, by principle, wrong - because it makes the comparisons (i.e. in look-up queries) wrong in the sense that both the actual ID *AND* the meta data are forced to be …
=> Make DeviceRegistry DB-like: hold ids+data instead of objects

detox-cli/cli.js
Resolves #2789 in a hotfix fashion (to unblock people).
Ultimately requires a fix inside [global-dirs](https://github.com/sindresorhus/global-dirs) packages for Windows 10 and modern Node.js 14. @sindresorhus, we are coming to you with an issue.
=> hotfix(detox-cli): do not check -g on win32

detox/index.d.ts, detox/src/configuration/composeAppsConfig.js, detox/src/configuration/composeAppsConfig.test.js, detox/src/errors/DetoxConfigErrorComposer.js, detox/src/errors/DetoxConfigErrorComposer.test.js, detox/src/errors/__snapshots__/DetoxConfigErrorComposer.test.js.snap
- This pull request addresses the issue described here: #2757
In this pull request, I have improved error handling for the next cases:
1. Someone is using a legacy (plain) config yet wants to adds `app` or `apps` property:
```
DetoxConfigError: Your configuration "plain" appears to be in a legacy format, which can’t contain "app" or "apps".
HINT: Remove "type" property from configuration and use "device" property instead:
a) "device": { "type": "android.emulator", ... }
b) "device": "<alias-to-device>" // you should add that device configuration to "devices" with the same key
Check your Detox config at path:
/home/detox/myproject/.detoxrc.json
{
configurations: {
plain: {
type: 'android.emulator',
device: 'Pixel_3a_API_30_x86',
binaryPath: 'path/to/apk',
app: 'my-app'
}
}
}
```
2. Someone …
=> fix(config): better detection of app/apps errors

detox/src/artifacts/log/LogArtifactPlugin.js
In this pull request, I have change the `process.log` artifact's name to `device.log`.
For all those times we've requested the artifacts under the artifacts folder, and didn't get the device logs, as requested ([example](https://github.com/wix/Detox/issues/2787#issuecomment-851295525)) 😄 
---
=> Rename device log artifact from process.log to device.log

detox/src/utils/getAbsoluteBinaryPath.js
Before:
```
detox[24148] ERROR: app binary not found at '/Users/yaroslavs/Projects/1/SPECIFY_PATH_TO_YOUR_APP_BINARY', did you build it?
```
After:
```
detox[24868] ERROR: Failed to find the app binary at:
/Users/yaroslavs/Projects/wix/Detox/detox/test/ios/build/Build/Products/Debug-iphonesimulator/example2789.app
HINT: Make sure that:
1. You built the app before running tests:
detox build -c <your-configuration-name>
2. The app binary can be found at the given path.
```
=> dx: prettier error message on app binary not found

detox/test/e2e/03.actions-scroll.test.js
Fixed scrolling test for iOS which broke after this [PR](https://github.com/wix/Detox/pull/2820)
=> Fixed scrolling test for iOS

detox/src/Detox.test.js, detox/src/devices/Device.js, detox/src/errors/index.js, detox/src/utils/cutStackTraces.js, detox/src/utils/cutStackTraces.test.js, detox/test/e2e-unhappy/failing-device-method.test.js, detox/test/scripts/ci_unhappy.sh
This is a developer experience improvement.
It improves stack traces for known errors (derived from Detox) occurring inside asynchronous `device.***()` public methods, e.g.:
As you can see, the improved error stack points exactly to the user code, and not to the misleading lines in Detox internals.
Added an `e2e-unhappy` suite for this case. Regression tests on CI should pass as well before this can be merged.
=> dx: fix stack traces for device.*() calls

detox/src/devices/drivers/ios/tools/AppleSimUtils.js, detox/src/utils/exec.js, detox/src/utils/exec.test.js
Suppresses redundant messages from **stderr** of `xcrun ... recordVideo` command (used by `--record-videos all` on iOS), that started appearing since Xcode 12.4 (or even earlier).
```diff
detox[10505] INFO:  [test.js] DETOX_CONFIGURATION="ios.sim.release" DETOX_RECORD_VIDEOS="all" DETOX_REPORT_SPECS=true DETOX_START_TIMESTAMP=1623313422454 DETOX_USE_CUSTOM_LOGGER=true nyc jest --config e2e/config.js --testNamePattern '^((?!:android:).)*$' --maxWorkers 1 e2e/01.sanity.test.js
detox[10507] INFO:  [AppleSimUtils.js] com.wix.detox-example launched. To watch simulator logs, run:
/usr/bin/xcrun simctl spawn 6371830E-8B44-422B-A52C-DB0B62E6B6E3 log stream --level debug --style compact --predicate 'process == "example"'
detox[10507] INFO:  Sanity is assigned to …
```
=> fix(artifacts): suppress some stderr logs from iOS video recordings

detox/local-cli/test.js, detox/src/devices/drivers/android/genycloud/GenyCloudDriver.js, detox/src/devices/drivers/android/genycloud/GenyCloudDriver.test.js, detox/src/devices/drivers/android/genycloud/services/GenyInstanceNaming.js, detox/src/devices/drivers/android/genycloud/services/GenyInstanceNaming.test.js, detox/src/utils/getWorkerId.js, detox/src/utils/getWorkerId.test.js
This pull request addresses the issue described here: #2842
* Prevents cleanup when device id is null (otherwise, we'll get a fatal error) — useful for situations when `gmsaas` CLI exits with an error early
* Forbids taking devices that do not belong to a specific worker
* When running with `--retries N`, it resets lock file before EACH (not only the first) run.
=> fix(genycloud): prevent device stealing

detox/src/ios/expectTwo.js, detox/src/ios/expectTwo.test.js, detox/test/e2e/05.waitfor.misc.test.js
- This pull request addresses the issue described here: #2844
Indeed, there was an implementation gap on iOS — waitFor() was not copying `element.index`.
Added appropriate unit and e2e tests for this case.
=> fix(ios): waitFor + element().atIndex matcher

detox/android/detox/proguard-rules-app.pro
- This pull request addresses the issue described here: #2837
In this pull request, I have (blindly<sup>*</sup>) added pro-guard rules which will force-keep some Kotlin stdlib classes, corresponding to reports of missing class - as in #2837 and #1994.
> <sup>*</sup> Unfortunately, I haven't managed to to have similar crash issues reproduced on our example project. Nevertheless, I've [analyzed the APK's](https://developer.android.com/studio/build/apk-analyzer) alongside R8's output files (`seeds.txt`, in particular), and have managed to prove that indeed with the new rules in place, the missing kotlin classes _do_ get bundled into the **test** apk.
=> Add some allegedly missing kotlin minification rules

docs/APIRef.Configuration.md
When working with the new configuration file documentation, I noticed that a few of the examples were either invalid JSON, or were inconsistently formatted.
In this pull request, I have not made any changes to the data itself, but have allowed my local version of Prettier to reformat the code blocks, and made a few tweaks to comments.
=> docs: update APIRef.Configuration

detox/package.json, detox/src/configuration/__mocks__/configuration/extends/.detoxrc.js, detox/src/configuration/__mocks__/configuration/extends/.detoxrc.json, detox/src/configuration/__mocks__/configuration/extends/middle/index.js, detox/src/configuration/loadExternalConfig.js, detox/src/configuration/loadExternalConfig.test.js, detox/test/package.json, docs/APIRef.Configuration.md, examples/demo-native-android/package.json, examples/demo-native-ios/package.json, examples/demo-react-native-detox-instruments/package.json, examples/demo-react-native-jest/package.json, examples/demo-react-native/package.json, lerna.json, package.json
The recent `extends` feature (https://github.com/wix/Detox/pull/2707) has undefined behavior when it boils down to relative Node module paths. Moreover, I consider the present implementation of relative `extends` incorrect, because it always resolves relative paths relatively to `process.cwd()` and not the current directory of the current Detox config file.
This is why I am adding the relevant tests and mentions in the docs together with the fix:
> Please note that `extends` has to be a valid Node module path. Relative module paths will be resolved relatively
to the Detox config file which contains that specific `extends` property, e.g.:
```js
// given: ~/Projects/my-project/.detoxrc.json
{ extends: "./e2e/detox-base-config" }
// goes to: ~/Projects/my-project/e2e/detox-base-config.js
{ …
```
=> fix(config): extends: ./relative/path

detox/index.d.ts, detox/local-cli/init.js, detox/local-cli/templates/jest.js, detox/local-cli/test.js, detox/local-cli/test.test.js, detox/local-cli/utils/jestInternals.js, detox/local-cli/utils/splitArgv.js, detox/local-cli/utils/testCommandArgs.js, detox/package.json, detox/src/configuration/composeRunnerConfig.js, detox/test/e2e/config.js, detox/test/e2e/detox.config.js, detox/test/package.json, detox/test/types/detox-jest-circus-setup-tests.ts, docs/Guide.Jest.md, examples/demo-native-android/package.json, examples/demo-native-ios/package.json, examples/demo-react-native-detox-instruments/package.json, examples/demo-react-native-jest/e2e/config.json, examples/demo-react-native-jest/package.json, examples/demo-react-native/package.json, lerna.json, package.json
- This pull request addresses the issue described here: #2862.
In this pull request, I have added `skipLegacyWorkersInjection: boolean` to `Detox.DetoxConfig`, so that `detox test` command avoids the permanent passthrough of `--workers 1` to Jest by default. For the opposite case, when a user specifies a custom workers number via [`-w, --workers <count>` CLI option](https://github.com/wix/Detox/blob/28a34feb5ed6b2f4fb62bda188b12125379337bd/docs/APIRef.DetoxCLI.md#test), the previous behavior remains the same.
From now on, the default Jest config file generated by `detox init -r jest` contains `maxWorkers: 1` to prevent an unintended overallocation of devices if there are multiple test files — an average personal computer is likely to have a problem with more than 3-4 simulators/emulators …
=> feat(config): skipLegacyWorkersInjection

detox/src/Detox.js, detox/src/Detox.test.js, detox/src/devices/drivers/android/emulator/EmulatorDriver.js, detox/src/devices/drivers/android/emulator/helpers/EmulatorLauncher.js, detox/src/devices/drivers/android/emulator/helpers/EmulatorLauncher.test.js, detox/src/devices/drivers/android/exec/ADB.js, detox/src/utils/retry.js, detox/src/utils/retry.test.js
- This pull request addresses the issue described here: #1975
In this pull request, I have:
- added clearing callback for "app instrumentation end" when shutting down the device, because `adb.unreverseTcpPort` will fail if the device in the middle of shutting down;
- changed the implementation for shutting down an emulator: `adb -s SERIAL emu kill` instead of telnet
- added waiting until the emulator indeed shuts down - that prevents a telnet error in the next suite:
```
detox[31857] DEBUG: [EXEC_CMD, #123] "/Users/yaroslavs/Library/Android/Sdk/platform-tools/adb" -s emulator-18638 emu kill
detox[31857] TRACE: [SESSION_TORN] app exited session 2c5620bd-9097-a376-82ca-31c6b2d4965b
detox[31857] TRACE: [EXEC_SUCCESS, #122]
detox[31857] TRACE: [EXEC_SUCCESS, #123] OK: killing emulator, bye …
```
=> fix: emulator shutdown bugs

detox/package.json, detox/src/Detox.js, detox/src/Detox.test.js
This is another approach to crack the problem originally addressed by #2858.
The introduced optimization should eliminate that silly double uninstall-install process on our CI.
The implementation idea is to compare `binaryPath + testBinaryPath` for their uniqueness before calling uninstallApp/reinstallApp.
=> perf: skip initial multi-app reinstalls when binary paths are the same

detox/src/devices/drivers/android/emulator/helpers/EmulatorDeviceAllocation.js, detox/src/devices/drivers/android/emulator/helpers/EmulatorDeviceAllocation.test.js, detox/src/devices/drivers/android/genycloud/helpers/GenyCloudInstanceAllocation.js, detox/src/devices/drivers/android/genycloud/helpers/GenyCloudInstanceAllocation.test.js, detox/src/devices/drivers/ios/SimulatorDriver.js
Adds an emergency simulator deallocation for cases when `boot` fails in the middle.
```js
await this._boot(udid, deviceQuery.type || deviceQuery);
```
```
detox[22859] DEBUG: [EXEC_CMD, #37] applesimutils --list --byId EB449DF0-39DC-457A-B2D7-25CE51BB1A2E --maxResults 1
detox[22859] ERROR: [EXEC_FAIL, #37] "applesimutils --list --byId EB449DF0-39DC-457A-B2D7-25CE51BB1A2E --maxResults 1" failed with error = ChildProcessError: Command failed: applesimutils --list --byId EB449DF0-39DC-457A-B2D7-25CE51BB1A2E --maxResults 1
```
In this pull request, I'm catching unexpected errors and rethrow them after deallocating the device UDID.
```js
await this._launchEmulator(avdName, placeholderPort);
```
```js
await this._instanceLauncher.launch(instance);
```
=> fix: deallocate devices on cold boot errors

detox/android/detox/src/full/java/com/wix/detox/espresso/DetoxAction.java, detox/android/detox/src/main/java/com/wix/detox/espresso/action/ScrollToIndex.kt, detox/android/detox/src/main/java/com/wix/detox/espresso/action/ScrollToIndexAction.kt, detox/android/detox/src/main/java/com/wix/detox/espresso/scroll/FlinglessSwiper.kt, detox/android/detox/src/testFull/java/com/wix/detox/espresso/scroll/FlinglessSwiperSpec.kt, detox/index.d.ts, detox/src/android/AndroidExpect.test.js, detox/src/android/actions/native.js, detox/src/android/core/NativeElement.js, detox/src/android/espressoapi/DetoxAction.js, detox/test/e2e/03.actions-scroll.test.js, docs/APIRef.ActionsOnElement.md
Improve scrollTo speed by modifying safety buffer values, and add scrollToIndex on Android. Addresses issue #2496.
=> Improve scroll speed and add scrollToIndex

detox/local-cli/build.js, detox/local-cli/build.test.js, docs/APIRef.DetoxCLI.md
This pull request adds `-i, --if-missing` CLI argument to `detox build`, so that you don't have sometimes to write extra checks in your CI build scripts whether the binary exists or not.
```
-i, --if-missing     Execute the build command only if the app binary is missing.  [boolean]
```
```
➜  test git:(feat/lazy-build) npx detox build -c ios.sim.release --if-missing
detox[34137] INFO:  [build.js] Skipping build for "example" app...
```
=> feat(cli): add -i, --if-missing to detox build

detox/android/detox/src/full/java/com/wix/detox/espresso/DetoxAction.java, detox/android/detox/src/full/java/com/wix/detox/espresso/DetoxMatcher.java, detox/android/detox/src/full/java/com/wix/detox/espresso/matcher/ViewMatchers.kt, detox/android/detox/src/main/java/com/wix/detox/espresso/action/AdjustSliderToPositionAction.kt, detox/android/detox/src/testFull/java/com/wix/detox/espresso/action/AdjustSliderToPositionActionTest.kt, detox/index.d.ts, detox/src/android/AndroidExpect.test.js, detox/src/android/actions/native.js, detox/src/android/core/NativeElement.js, detox/src/android/core/NativeExpect.js, detox/src/android/espressoapi/DetoxAction.js, detox/src/android/espressoapi/DetoxMatcher.js, detox/src/android/matchers/native.js, detox/test/e2e/03.actions.test.js, detox/test/src/Screens/ActionsScreen.js, docs/APIRef.ActionsOnElement.md, docs/APIRef.Expect.md
Adding adjustSliderToPosition and toHaveSliderPosition for Android - addresses https://github.com/wix/Detox/issues/2792.
=> adjustSliderToPosition on Android

detox/test/e2e/16.location.test.js, detox/test/src/Screens/LocationScreen.js
- This pull request is associated with #1935.
In this pull request, I have changed our test-app's usage of `@react-native-community/geolocation` in an attempt to make it more stable with Genymotion-cloud emulators. ATM, these tests are flaky on our CI.
Follow-up:
=> Apply an attempt to make setLocation e2e stable with Genycloud

detox/src/client/Client.test.js, detox/src/errors/longreads/__snapshots__/failedToReachTheApp.test.js.snap, detox/src/errors/longreads/failedToReachTheApp.js, detox/src/server/__tests__/server-integration.test.js, detox/test/e2e/19.crash-handling.test.js, docs/Introduction.Android.md, docs/README.md, docs/Troubleshooting.BuildingTheApp.md, docs/Troubleshooting.Installation.md, docs/Troubleshooting.RunningTests.md, docs/Troubleshooting.md
- This pull request addresses the issue described here: #2904.
In this pull request, I have collected, aggregated and reorganized troubleshooting instructions Detox has in the various troubleshooting guides.
Originally, the point was to try to better warn regarding mistakes related to `DetoxTest.java`. However, it was not easy to do + much boyscouting seemed to have been necessary, regardless.
Eventually, most work boiled down to documentation improvements. However, in addition, I've had the existing Detox-app connection error messages - in the code itself, trimmed down so as to mostly contain a ref to the associated troubleshooting guide. They were a bit overly verbose, I believe -- making developers not really wanting to read through them through, as they should.
---
> _For …
=> Reorganize troubleshooting onto a first-class guide, and ref it in code

detox/src/devices/Device.js, detox/src/devices/Device.test.js, detox/src/devices/drivers/DeviceDriverBase.js, detox/src/devices/drivers/android/genycloud/GenyCloudDriver.js, detox/src/devices/drivers/android/genycloud/GenyCloudDriver.test.js, detox/src/devices/drivers/ios/SimulatorDriver.test.js
In this pull request, I have aligned `device.id` for the Genymotion-cloud case, which - according to our existing contract, should return `adbName` (and instead returns a fancy, highly-detailed description).
---
=> Align device.id for Genymotion to ext-api contract

detox-cli/cli.js
Resolves #2825.
Reopens #2750. 😢 
Since #2750 is not pleasant but not blocking, while #2825 is a dealbreaker, I have to revert the implementation which relies on `is-installed-globally`.
I'll need to submit fixes to that package, `is-installed-globally`, before I can return these checks back.
=> revert(global-cli): is installed globally

detox-cli/package.json
- This pull request is a follow-up on: #2925
In this pull request, I have remove the `is-installed-globally` dependency from `detox-cli`.
=> Follwing #2925: remove excess dep is-installed-globally

detox/android/detox/src/main/java/com/wix/detox/common/SDKSupports.kt, detox/android/detox/src/main/java/com/wix/detox/espresso/action/ViewScreenshot.kt
In this pull request, I have removed code-leftovers, associated with Android SDK version lower than our new minimum (21).
---
=> Android: Remove code associated with SDK<21 (Detox's min)

detox/index.d.ts
I noticed that some of the advertised APIs in the Docs weren't working with the latest version (I'm on 18.20.1). This makes two changes:
* `element().pinch()` has its `speed` and `angle` parameters marked as optional
* Added the missing API for `element().takeScreenshot()`, previously it only existed on `Device`
I happened to need both of these APIs in a new test I'm writing (iOS) and can confirm that the current functionality works just fine with this API definition.
=> Added Typescript definitions for element.pinch() and element.takeScreenshot()

detox/src/devices/Device.js, detox/src/devices/Device.test.js
Fixes an edge case when the device is started with no apps at all, yet all its app-related methods are used by passing `bundleId` explicitly.
```json
{
"configurations": {
"ios.noapps": {
"device": "ios.phone",
"apps": []
}
}
}
```
It appears, that I made a mistake in `launchApp` implementation which makes it unusable in this rare situation – it throws an error instead of letting the app run via the explicit bundle identifier.
```js
await device.launchApp({}, 'explicit.app.identifier');
```
=> fix(device): launchApp with explicit bundleId

detox/package.json, detox/src/artifacts/screenshot/SimulatorScreenshotPlugin.js, detox/src/artifacts/templates/artifact/FileArtifact.js, detox/src/artifacts/templates/artifact/FileArtifact.test.js, detox/src/artifacts/uiHierarchy/IosUIHierarchyPlugin.js, detox/src/artifacts/uiHierarchy/IosUIHierarchyPlugin.test.js, detox/src/artifacts/utils/temporaryPath.js, detox/src/utils/fsext.js, detox/src/utils/fsext.test.js, detox/test/e2e/21.artifacts.test.js, detox/test/e2e/utils/artifactUtils.js, detox/test/package.json, examples/demo-native-android/package.json, examples/demo-native-ios/package.json, examples/demo-react-native-detox-instruments/package.json, examples/demo-react-native-jest/package.json, examples/demo-react-native/package.json, lerna.json, package.json
- This pull request addresses the issue described here:
If there are pending app artifacts (iOS view hierarchies, screenshots made by app - e.g. visibility failures), and the app is being uninstalled – they just get lost in the middle. Artifacts plugin prints many warnings about missing files.
This is why here I improve the E2E test suite for this edge cases and make sure `uninstallApp()` does not affect the artifacts collection.
- In this pull request, I have implemented an artifact relocation mechanism for two plugins: UI hierarchy and screenshot plugin. If the app is about to be uninstalled, they will relocated all the pending artifacts (not saved and not deleted ones).
=> fix(artifacts): save app artifacts before its uninstall

detox/android/detox/src/full/java/com/wix/detox/DetoxMain.kt, detox/android/detox/src/full/java/com/wix/detox/LaunchArgs.java, detox/android/detox/src/full/java/com/wix/detox/reactnative/ReactNativeExtension.kt, detox/android/detox/src/full/java/com/wix/detox/reactnative/ReactNativeIdlingResources.kt, detox/android/detox/src/full/java/com/wix/detox/reactnative/idlingresources/NetworkIdlingResource.java, detox/test/e2e/14.network.test.js
Until now, the launchArgs detoxURLBlacklistRegex was supported only on ios - this PR adds support on Android. Relates to issue https://github.com/wix/Detox/issues/1695.
=> Add support for launch argument detoxURLBlacklistRegex on Android

detox/src/devices/drivers/android/exec/ADB.js, detox/src/devices/drivers/android/exec/ADB.test.js
- This pull request addresses the issue described here: 
- #2527
- #2919
- #274
These issues have been solved before, but broke again after #2922.
Under API 23, `pm install` only accept `-rg` instead of individual `-g` option.
I also added notice comments because this argument has been changed to `-r -g` several times in other PRs, these notice may be helpful while editing.
ref: https://github.com/wix/Detox/pull/2922#pullrequestreview-743410234
ref: https://github.com/wix/detox/issues/274#issuecomment-356529351
---
note: This is a bug fix. Not changing API and adding features.
=> Use `-rg` in adb install with API < 23

detox/index.d.ts, detox/test/types/detox-global-tests.ts
- This pull request addresses a regression introduced by #2977
In this pull request, I made the `duration` parameter optional, as it has been before.
=> fix(types): optional longPress duration

.gitattributes, .github/workflows/rapid-test.yml, detox/local-cli/test.test.js, detox/src/utils/shellQuote.test.js, detox/src/utils/wrapWithStackTraceCutter.test.js, package.json, scripts/postinstall.js, scripts/postinstall.sh
The pull request introduces quick checks (under 4 minutes) on a matrix of OSes:
* `windows-latest`
* `mac-latest`
* `ubuntu-latest`.
There we run:
* lint
* typing tests
* unit tests
This becomes especially important to keep being contribution-friendly to developers using various platforms.
=> ci(github-actions): add rapid test workflow

.github/workflows/website.yml
Use webfactory action to release the website to Github pages, as Docusaurus recommended in their [docs](https://docusaurus.io/docs/deployment).
=> ci(github-actions): use webfactory.

detox/index.d.ts, detox/test/types/detox-global-tests.ts, docs/APIRef.DeviceObjectAPI.md
- This pull request adds missing information about `device.captureViewHierarchy` API to the documentation and TS typings.
In this pull request, I have:
=> types: add .captureViewHierarchy typings

detox/test/e2e/22.launch-args.test.js
A follow-up to #3038. Adds lacking E2Es.
=> test(e2e): cover the new device.appLaunchArgs API

website/docusaurus.config.js, website/package.json
Integrate [Detox website](https://wix.github.io/Detox/) with [Algolia DocSearch](https://docsearch.algolia.com/).
This will add a search box in our navigation bar.
The DocSearch is built in two parts:
- a crawler which runs on Algolia DocSearch infrastructure every 24 hours. It follows every link in Detox website and extract content from every page it traverses. It then pushes this content to an Algolia index.
- a JavaScript snippet to be inserted in Detox website that will bind this Algolia index to your search input and display its results in a dropdown UI.
I've used the App-ID, API-key and index-name as given to us by the DocSearch team.
See [DocSearch docs](https://docsearch.algolia.com/docs/what-is-docsearch/) or [Docusaurus docs (Using Algolia …
=> feat(DocSearch): integrate Detox website with Algolia DocSerach.

detox/android/detox/src/full/java/com/wix/detox/espresso/matcher/ViewAtIndexMatcher.kt, detox/android/detox/src/testFull/java/com/wix/detox/espresso/matcher/ViewAtIndexMatcherSpec.kt, detox/test/e2e/02.matchers.test.js
- This pull request fixes #2430.
In this pull request, I have improved the error message generated whenever `atIndex` fails (index out of bounds), and improved the testing around it (added coverage for Android).
It boils down to this, instead of the original message (as described in #2430):
---
=> Improve atIndex matching message for Android

docs/Introduction.iOS.md
Add a `xcodebuild` command example and `binaryPath` example to the provided configuration example. No reason to have a placeholder if that's an example (and not a template), and the configuration keys are explain immediately after.
In response to this issue: https://github.com/wix/Detox/issues/3107.
=> docs(Introduction.iOS): add `build` and `binaryPath` to the example.

detox/package.json, detox/src/devices/allocation/drivers/android/emulator/EmulatorLauncher.js, detox/src/utils/retry.js, detox/src/utils/retry.test.js, detox/src/utils/sleep.js, detox/src/utils/sleep.test.js, detox/test/package.json
- This pull request resolves #2481
In this pull request, I have:
* added `shouldUnref` option to `sleep` utility
* added `shouldUnref ` option to `retry` utility
* added `shouldUnref: true` to the `retry()` call for Android emulator
* updated unit tests
* checked manually the end result.
To simulate the hanging emulator I monkey-patched `detox/src/devices/common/drivers/android/exec/BinaryExec.js` and forced it to use this script:
```bash title='emulator'
#!/usr/bin/env bash
while read -r line;
do
echo "$line" ;
done
```
=> fix: prevent a retry loop from hanging up the test runners

detox/android/detox/proguard-rules-app.pro, detox/test/android/app/proguard-rules.pro
Missing kotlin.io in proguard is causing a failure of notification tests on release builds
=> Fix kotlin proguard configuration

detox/src/client/Client.test.js, detox/src/client/__snapshots__/Client.test.js.snap, detox/src/client/actions/actions.js, detox/src/errors/DetoxRuntimeError.js
This should allow us to easily distinguish between Detox-generated errors vs something else.
At the moment, we don't – `invoke` errors get wrapped into regular `Error` objects for no good reason.
=> refactor: throw DetoxRuntimeError if an invocation fails

detox/android/detox/src/full/java/com/wix/detox/adapters/server/DetoxActionHandlers.kt, detox/android/detox/src/full/java/com/wix/detox/adapters/server/QueryStatusActionHandler.kt, detox/android/detox/src/full/java/com/wix/detox/reactnative/idlingresources/AnimatedModuleIdlingResource.java, detox/android/detox/src/full/java/com/wix/detox/reactnative/idlingresources/AsyncStorageIdlingResource.kt, detox/android/detox/src/full/java/com/wix/detox/reactnative/idlingresources/BridgeIdlingResource.java, detox/android/detox/src/full/java/com/wix/detox/reactnative/idlingresources/DescriptiveIdlingResource.kt, detox/android/detox/src/full/java/com/wix/detox/reactnative/idlingresources/IdlingResourceConstants.kt, detox/android/detox/src/full/java/com/wix/detox/reactnative/idlingresources/IdlingResourceDescription.kt, detox/android/detox/src/full/java/com/wix/detox/reactnative/idlingresources/NetworkIdlingResource.java, detox/android/detox/src/full/java/com/wix/detox/reactnative/idlingresources/UIModuleIdlingResource.java, detox/android/detox/src/full/java/com/wix/detox/reactnative/idlingresources/timers/TimersIdlingResource.kt, detox/android/detox/src/testFull/java/com/wix/detox/adapters/server/DetoxActionHandlersSpec.kt, detox/android/detox/src/testFull/java/com/wix/detox/adapters/server/QueryStatusActionHandlerSpec.kt, detox/android/detox/src/testFull/java/com/wix/detox/reactnative/idlingresources/AsyncStorageIdlingResourceSpec.kt, detox/android/detox/src/testFull/java/com/wix/detox/reactnative/idlingresources/IdlingResourceDescriptionSpec.kt, detox/android/detox/src/testFull/java/com/wix/detox/reactnative/idlingresources/timers/TimersIdlingResourceSpec.kt, detox/ios/Detox/DetoxManager.swift, detox/src/client/Client.test.js, detox/src/client/actions/SyncStatusSchema.json, detox/src/client/actions/actions.js, detox/src/client/actions/formatters/SyncStatusFormatter.js, detox/src/client/actions/formatters/SyncStatusFormatter.test.js, detox/src/client/actions/formatters/__snapshots__/SyncStatusFormatter.test.js.snap, detox/test/.gitignore, detox/test/e2e/detox.config.js, docs/Troubleshooting.Synchronization.md
This pull request addresses the issue described here: Unify debug-sync logs between platforms #2714
As part of this change:
1. iOS: Update DetoxSync to the latest commit.
2. Android: Replace the old string sync-status with a JSON description
3. Unify debug-sync logs between the platforms, using a JSON formatter.
```
detox[9160] INFO:  [APP_STATUS] The app seems to be idle
```
```
detox[9160] INFO:  [APP_STATUS] The app is busy with the following tasks:
• "LooperIdlingResource-2215-mqt_native_modules" (Native Modules Thread) is executing (native module calls).
• "LooperIdlingResource-2214-mqt_js" (JS Thread) is executing (JavaScript code).
• UI elements are busy:
- Reason: UI rendering activity.
```
```
detox[9733] INFO:  [APP_STATUS] The app is busy with the following tasks:
• Run loop …
```
=> feat(Sync Logs): unify debug-sync logs between platforms.

detox/src/devices/common/drivers/ios/tools/AppleSimUtils.js
This workaround solves the issue described here:
- https://github.com/firebase/firebase-ios-sdk/issues/9083
And some of the crashes that was mentioned here:
- https://github.com/wix/Detox/issues/3000
- https://github.com/wix/Detox/issues/3123
- https://github.com/wix/Detox/issues/2641
- https://github.com/wix/Detox/issues/2802
=> iOS(AppleSimUtils): enable NSZombies on app launch.

detox/test/ios/Podfile
Wrapping RN v0.66 - v0.67 workaround with a check whether the RN version is 0.66 or 0.67, to avoid failures on CI when building Detox with RN v0.64. This workaround will be removed at RN v0.68.
Otherwise, we'll get `undefined method` error on RN v0.64:
```
Generating Pods project
--
| [!] An error occurred while processing the post-install hook of the Podfile.
|  
| undefined method `__apply_Xcode_12_5_M1_post_install_workaround' for #<Pod::Podfile:0x00007f7f5bd58f68>
|  
| /Users/builder/work/detox/test/ios/Podfile:32:in `block (2 levels) in from_ruby'
| /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.2/lib/cocoapods-core/podfile.rb:179:in `post_install!'
| /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/installer.rb:897:in `run_podfile_post_install_hook'
| …
```
=> fix(iOS, Podfile): check RN version before calling workaround.

detox/ios/Detox/Utilities/UIView+DetoxUtils.m
This PR reverts the commit [UIView+DetoxUtils: put thread to sleep before checking view hitability.](https://github.com/wix/Detox/pull/3145/commits/668965dfeb22cffefec125196be91d353b80a7db).
It was added temporally for test purposes, and merged by mistake here: https://github.com/wix/Detox/pull/3145.
=> Revert "UIView+DetoxUtils: put thread to sleep."

detox/test/ios/Podfile
If the React Native version is not defined using the env-arg, we are not overriding the version (currently, we use v0.66).
=> fix(iOS,Podfile): fix workaround condition.

README.md, docs/Introduction.AndroidDevEnv.md
Update documentation to reflect that we now use java11 and that the minimum RN version has changed to 0.64
=> Update support docs to java11 and min version 64

docs/Introduction.AndroidDevEnv.md
In this pull request, I have addresses some markdown linter errors:
```
docs/Introduction.AndroidDevEnv.md:31 MD031/blanks-around-fences Fenced code blocks should be surrounded by blank lines [Context: "```"]
docs/Introduction.AndroidDevEnv.md:33 MD031/blanks-around-fences Fenced code blocks should be surrounded by blank lines [Context: "```sh"]
docs/Introduction.AndroidDevEnv.md:50:157 MD034/no-bare-urls Bare URL used [Context: "https://techoral.com/blog/java..."]
```
---
=> docs: Fix AndroidDevEnv lint errors

detox/src/devices/common/drivers/ios/tools/AppleSimUtils.js
Enable `GULGeneratedClassDisposeDisabled` environment flag to disable GoogleUtilities' Swizzler from disposing generated classes when executing Detox tests. This flag works with [GoogleUtilities v7.7](https://github.com/google/GoogleUtilities/blob/main/CHANGELOG.md#770).
This replaces the `NSZombieEnabled` flag, which was used as a workaround.
See: https://github.com/firebase/firebase-ios-sdk/issues/9083.
=> AppleSimUtils: replace zombie-enabled workaround with designated flag.

detox/android/detox/src/full/java/com/wix/detox/reactnative/idlingresources/uimodule/DispatchCommandOperationReflected.kt, detox/android/detox/src/full/java/com/wix/detox/reactnative/idlingresources/uimodule/RN66Workaround.kt
In the RN66 workaround we assume that viewCommand will return a String, but apparently it can sometimes return an Int and this leads to classCastException. In this fix I've changed it to return Any. Fixes issue #3168
=> Fix classCastException in RN66 workaround

detox/src/configuration/index.js
Unblocks issue ~no. 105 in DWP~ classified. 😎🤣 
As it turned out, we can't mutate `retries` count on CI because it is a CLI tool option, not an option of Detox.
To do that, we need access to `argv` itself. 🤷‍♂️
=> internal: allow to mutate retries count via argv

detox/src/devices/common/drivers/ios/tools/AppleSimUtils.js
Since we have no convenient way to check whether the app is currently running or not, we might execute this command (terminate) even if the app is not currently running, or even installed.
We have encountered some case where the following error is thrown in a case where the app did not run (@burya4ok):
```
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
Application termination failed.
FBSSystemService reported failure without an error, possibly because the app is not currently running.
```
This workaround is done to ignore the error above, as we do not care if the app was running before, we just want to make sure it isn't now.
---
**Note for reviewer:** I also considered the alternative of checking `_isAppRunning` in `RuntimeDevice.js` before …
=> fix(iOS): ignore `simctl terminate` error when app is not running.

detox/runners/jest-circus/listeners/DetoxInitErrorListener.js, detox/src/utils/Timer.js
Previously, if there was an error in the Detox setup phase (e.g. port allocation collision or device not booting), the entire suite with all the tests was marked as skipped. The motivation was to reduce the output for such tests.
But as it seems, it doe not play well with Jest reporters — such tests are considered skipped indeed, nevertheless, and if a suite fails on such an early error — it is not going to be retried via Detox CLI mechanism.
So, the suggested solution is to duplicate the unhandled error to each test and to noop the registered hooks (to prevent their accidental execution — yes, unfortunately, that happens).
=> fix(jest-circus): proper handling of init errors

detox/package.json, detox/src/utils/dateUtils.js, detox/src/utils/dateUtils.test.js, detox/src/utils/logger.js
- This pull request resolves #3157.
In this pull request, I have enabled a custom (short) timestamp prefix to terminal logs. Other log outputs should have remained intact.
Before:
```
detox[35368] INFO:  [test.js] DETOX_CONFIGURATION="android.emu.release" DETOX_LOGLEVEL="verbose" DETOX_REPORT_SPECS=true DETOX_START_TIMESTAMP=1644339539856 DETOX_USE_CUSTOM_LOGGER=true nyc jest --config e2e/config.js --testNamePattern '^((?!:ios:).)*$' e2e/01.sanity.test.js
detox[35370] DEBUG: [WSS_CREATE] Detox server listening on localhost:54581...
detox[35370] DEBUG: [WSS_CONNECTION, #54582] registered a new connection.
detox[35370] DEBUG: [EXEC_CMD, #0] "/Users/amitd/Library/Android/sdk/emulator/emulator" -list-avds --verbose
detox[35370] DEBUG: [EXEC_CMD, #1] …
```
=> Apply time prefix to plain (terminal) logs

detox/package.json, detox/src/Detox.js, detox/src/Detox.test.js, detox/src/configuration/composeSessionConfig.js, detox/src/configuration/composeSessionConfig.test.js, detox/src/errors/DetoxConfigErrorComposer.js, detox/src/errors/DetoxConfigErrorComposer.test.js, detox/src/errors/__snapshots__/DetoxConfigErrorComposer.test.js.snap, detox/src/server/DetoxServer.js, detox/src/server/DetoxServer.test.js
Related to https://github.com/wix/Detox/pull/3174
Hopefully, this is an ultimate fix that will never ever cause the further reproduction of that bug.
Solution: using `port: 0` to make sure `wss` server allocates the port dynamically and setting the resulting value post-factum to the client config.
=> fix: race condition in DetoxServer class

detox/android/detox/src/main/java/org/joor/Reflect.java
Not setting locale for language/country neutral operation may cause bug depending on the default locale.
See https://docs.oracle.com/javase/7/docs/api/java/util/Locale.html#ROOT
Note: I am just searching for `toLowerCase()` and `toUppercase()` in my project's dependencies and send the same PR, in order to potentially raise the awareness. Although I've seen the lack of explicit locale has caused issues for us, I am not sure if wix/Detox is actually affected. 
Example related issue: https://github.com/joltup/rn-fetch-blob/issues/573
=> Use root locale when changing case in java

detox/test/e2e/33.attributes.test.js, detox/test/package.json
Since [accessibilityValue](https://developer.apple.com/documentation/uikit/uiaccessibilityelement/1619583-accessibilityvalue) of checkbox is now exposed (see: https://github.com/react-native-checkbox/react-native-checkbox/releases/tag/v0.5.11), change the relevant e2e test to expect a checkbox `value` when calling `getAttributes`.
=> tests: expect `getAttributes()` to return a checkbox value.

detox/ios/Detox/Policy/DetoxPolicy.h, detox/ios/Detox/Policy/DetoxPolicy.m, detox/ios/Detox/Utilities/UIView+DetoxUtils.m, detox/test/e2e/32.visibility-debug-artifacts.test.js
Fix visibility error message to show a valid percentage description.
Before this fix, `15` percent value was printed as `1,500%`, instead as `15%`, since `NSNumberFormatterPercentStyle` expects the value to be the percent divided by 100.
[From NSNumberFormatterPercentStyle docs](https://developer.apple.com/documentation/foundation/nsnumberformatterstyle/nsnumberformatterpercentstyle):
> For example, in the en_US locale, the number 0.123 is represented as 12%.
Since we are already using a percent value, we don't need a string formatter for the representation.
=> fix(iOS): fix visibility expectation error message.

scripts/ci.android.sh
Following our Buildkite migration, our Android unit tests execution has been rendered missing from the CI scripts.
In this pull request, I have resumed it. I'm not confident that they will indeed run successfully on our agents, but we will get that fixed as well by running, then rinse&repeat-ing.
@igorgn
=> fix: Exec Android UT for RN≥66 on CI

detox/src/artifacts/ArtifactsManager.js, detox/src/artifacts/ArtifactsManager.test.js
Allows for external entities to monitor new artifacts provided a private access to `detoxInstance._artifactsManager`:
```js
detoxInstance._artifactsManager.on('trackArtifact', (artifact) => {
// ...
});
```
Needed to try out an experimental Detox + Allure integration.
=> internal(artifacts): enable external tracking

detox/local-cli/templates/jest.js, detox/local-cli/test.js, detox/local-cli/test.test.js, detox/src/configuration/composeRunnerConfig.js, detox/src/configuration/composeRunnerConfig.test.js
BREAKING CHANGE: Detox won't be appending "e2e" glob to the test runner
if it is not explicitly configured to do so via "specs" property in the
config.
This is a planned deprecation.
The motivation is to fix issues such as:
* https://github.com/wix/Detox/issues/3076
* https://github.com/wix/Detox/issues/2901
=> feat(config): drop default "e2e" value for specs

detox/android/detox/build.gradle, detox/android/detox/src/testFull/java/com/wix/detox/espresso/registry/IRStatusInquirerTest.kt, detox/test/android/build.gradle, docs/Guide.Contributing.md
In this pull request, I have enabled the execution of our Android unit tests locally. It was broken, returning a 501 error for any Robolectric-based test case, as the repository was accessed via `http` rather than `https`. Upgrading to a newer Robolectric fixes that, likely because it is hosted on a different artifactory.
---
=> Make Android unit tests run locally

scripts/utils/releaseDocumentation.js
Check if docs versions JSON file exists before reading it, to avoid error when the version file does not yet exist (no versions exist).
=> releaseDocumentation: fix release when no previous versions exist.

scripts/utils/publishNewVersion.js
Getting the new version from our `package.json` was already implemented as `getVersionSafe()`.
Also, the previous import of `package.json` threw an error ([here](https://buildkite.com/wix-mobile-oss/detox/builds/532#1ae7ca83-1b4f-4fd7-89bc-b0dc8e4f3109/117-519)).
=> build(publishNewVersion): fix get new version.

detox/android/detox/src/full/java/com/wix/detox/Detox.java, detox/android/detox/src/full/java/com/wix/detox/NotificationDataParser.kt
- This pull request is associated with #3285.
In this pull request, I have had the deprecated `DetoxIdlePolicyConfig` class removed from the Android native code.
Also added this as a WIP bullet under #3285.
---
=> Remove deprecated native IdlePolicyConfig

detox/ios/Detox.xcodeproj/project.pbxproj
Resolves this comment: https://github.com/wix/Detox/issues/3319#issuecomment-1094890944
XCode keeps complaining:
> Cycle inside Detox; building could produce unreliable results. This usually can be resolved by moving the target's Headers build phase before Compile Sources.
I've done what XCode asks - the error goes away.
=> fix(iOS): move Headers build phase before Compile Sources.

detox/test/android/settings.gradle, detox/test/package.json, detox/test/src/Screens/StressScreen.js, detox/test/src/helpers/storage.js, examples/demo-react-native-jest/package.json, examples/demo-react-native/android/settings.gradle, examples/demo-react-native/package.json
Running `lerna bootstrap` currently fails dependency resolution.
```
$ lerna bootstrap
info cli using local version of lerna
lerna notice cli v3.22.1
lerna info Bootstrapping 11 packages
lerna info Installing external dependencies
lerna ERR! npm install --no-package-lock exited 1 in 'example'
lerna ERR! npm install --no-package-lock stderr:
2022-04-17T09:32:15.434Z
While resolving: detox-test@19.6.5
Found: react@17.0.2
node_modules/react
react@"17.0.2" from the root project
Could not resolve dependency:
peer react@"^16.8" from @react-native-community/async-storage@1.12.1
node_modules/@react-native-community/async-storage
@react-native-community/async-storage@"^1.12.0" from the root project
Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to …
```
=> Upgrade dependencies to allow lerna bootstrap to succeed

detox/src/ios/expectTwo.js, detox/test/e2e/29.webview.test.js
Fixes the issue:
```
web
^^^ --- trying to access the global variable injected by Detox
```
where previously it has been throwing an error immediately:
```
Detox instance has not been initialized·
HINT: Make sure to call detox.init() before your test begins
```
while the expected behavior would be:
```js
web; // does not throw
web(); // calling the function throws: Detox does not support web(), web.element() on iOS
```
=> fix(ios): inject web() stub function properly

detox/index.d.ts, detox/src/devices/runtime/RuntimeDevice.js, detox/test/types/detox-module-tests.ts, docs/APIRef.DeviceObjectAPI.md
Resolves https://github.com/wix/Detox/issues/3350
In this pull request, I have removed a deprecation notice from `device.relaunchApp` API. From now, it is considered a legit shorthand, e. g.:
```js
await device.launchApp({ newInstance: true, launchArgs: { /* ... */} });
// is the same as:
await device.relaunchApp({ launchArgs: { /* ... */ } });
```
=> feat: undeprecate device.relaunchApp()

detox/src/configuration/composeRunnerConfig.js, detox/src/configuration/composeRunnerConfig.test.js
Resolves https://github.com/wix/Detox/issues/3355
Removes old and **undocumented** global configuration properties: `test-runner` and `runner-config`.
Instead, their camelCase alternatives should be used: `testRunner` and `runnerConfig`.
=> feat(config): remove legacy dash props

detox/src/devices/runtime/drivers/ios/IosDriver.js, detox/src/devices/runtime/drivers/ios/SimulatorDriver.js
The follow-up to #3361 PR code review.
1. Restores the abstract `IosDriver` we used to have, and derives `SimulatorDriver` from it.
2. That's it.
=> code: follow-up fixes to PR #3361

.github/ISSUE_TEMPLATE/BUG_REPORT_ANDROID.yml, .github/ISSUE_TEMPLATE/BUG_REPORT_IOS.yml, .github/ISSUE_TEMPLATE/BUG_REPORT_OTHER.yml, .github/ISSUE_TEMPLATE/HELP_WITH_USING_DETOX.yml, README.md, detox/local-cli/utils/testCommandArgs.js, docs/APIRef.DetoxCLI.md, docs/Guide.ParallelTestExecution.md, docs/Introduction.Android.md, docs/Introduction.GettingStarted.md, website/versioned_docs/version-19.x/APIRef.DetoxCLI.md
Replaces `test-runner` property notice from YAML templates and Markdown docs with an up-to-date information:
1. Jest test runner is the default and it is implied.
2. Instead of undocumented `test-runner` syntax, we now suggest the correct and documented `testRunner` property as a source of truth.
Last but not least, `testRunner` property still remains supported by Detox for custom commands (e.g. `nyc jest`) and (possibly) other runners.
=> docs: test runners clarification

.editorconfig, detox/index.d.ts, detox/local-cli/test.test.js, detox/src/Detox.test.js, detox/src/configuration/__mocks__/configuration/oldschema/package.json, detox/src/configuration/__mocks__/configuration/packagejson/package.json, detox/src/configuration/__mocks__/configuration/priority/.detoxrc.js, detox/src/configuration/__mocks__/configuration/priority/detox-config.json, detox/src/configuration/__mocks__/configuration/priority/package.json, detox/src/configuration/composeAppsConfig.js, detox/src/configuration/composeAppsConfig.test.js, detox/src/configuration/composeArtifactsConfig.js, detox/src/configuration/composeBehaviorConfig.js, detox/src/configuration/composeDeviceConfig.js, detox/src/configuration/composeDeviceConfig.test.js, detox/src/configuration/composeRunnerConfig.js, detox/src/configuration/composeSessionConfig.js, detox/src/configuration/index.js, detox/src/configuration/index.test.js, detox/src/errors/DetoxConfigErrorComposer.js, detox/src/errors/DetoxConfigErrorComposer.test.js, detox/src/errors/__snapshots__/DetoxConfigErrorComposer.test.js.snap, detox/test/e2e/detox.config.js, docs/Guide.ThirdPartyDrivers.md, examples/demo-plugin/package.json
BREAKING: please migrate to the new `{ apps, devices, configurations }` schema that Detox has been already using for more than a year.
1. Enforces the migration to the modern normalized Detox config schema:
<table>
<tr>
<th>Legacy schema</th>
<th>Modern schema</th>
</tr>
<tr>
<td>
```json
{
"configurations": {
"legacy.ios.debug": {
"type": "ios.simulator",
"device": "iPhone 12",
"binaryPath": "/some/path/debug.app"
},
"legacy.ios.release": {
"type": "ios.simulator",
"device": "iPhone 12",
"binaryPath": "/some/path/release.app"
}
}
}
```
</td>
<td>
```json
{
"apps": {
"ios.debug": {
"type": "ios.app",
"binaryPath": "/some/path/debug.app"
},
"ios.release": {
"type": "ios.app",
"binaryPath": "/some/path/release.app"
}
},
"devices": {
"iphone": {
"type": "ios.simulator",
"device": { "type": …
```
=> feat(config): drop support for the all-in-one configuration format

detox/ios/Detox/Invocation/Predicate.swift
Fix crash due to a new `NSPredicate` error.
This new error caused by accessing a computed property by its keypath inside a predicate (`NSExpression` comparison). This raised a mysterious new Signal 6 (only for simulators with iOS version greater than 15.0) from `[_NSPredicateUtilities _predicateSecurityAction]`.
The exception error message was: `NSPredicate: NSFunctionExpression with selector 'dtx_text' is forbidden.` (`dtx_text` is a computed property).
Replacing the expression comparison predicate with a block predicate and calling the computed property `dtx_text` as calling a method on the evaluated object solved this issue.
=> fix(iOS): fix iOS > 15.0 `NSPredicate` error.

detox/test/package.json
- This pull request fixes #2791
In this pull request, I have released the lock on `react-native-webview` in our test project's `package.json`
---
=> Unlock react-native-webview's version locking

detox/src/Detox.js, detox/src/Detox.test.js
When the applications from the same publisher can share the stored credentials with each other, it turns out that in order to delete the credentials from the simulator you have to uninstall ALL the applications before you start installing them back again.
That's why I have to change subtly the strategy of reinstall here.
=> fix: more reliable uninstall for multiple apps

docs/Introduction.Android.md, docs/Troubleshooting.BuildingTheApp.md
When a project is setup through react-native init, the following appcompat dependency is not added. 
implementation 'androidx.appcompat:appcompat:1.1.0'
This later causes the following error when building Detox in release mode:
Execution failed for task ':app:processReleaseAndroidTestResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
> Android resource linking failed
ERROR:: AAPT: error: resource style/Widget.AppCompat.TextView ...
In this pull request I have updated the docs with the solution for this issue.
=> Add appcompat dependency to docs

docs/Guide.Mocking.md
1. I guess react-native-repackager mention is blatantly outdated.
2. Then, it is not clear what patterns are for the following scenarios:
* **Scenario 1**: You have two self-contained implementations: `module.js`  and `module.e2e.js`.
* **Scenario 2**: You need to replace a tiny function in `module.js` – how to reuse the 99% of the shared code.
Related discussions: https://github.com/wix/Detox/discussions/2935
=> docs: rewrite the mocking guide

detox/android/detox/src/full/java/com/wix/detox/adapters/server/WebSocketClient.java, detox/android/detox/src/main/java/com/wix/detox/common/DetoxErrors.java
Replace non-informative error-log with illegal argument exception throwing.
Error is currently logged as:
```
DetoxWSClient: Detox Error: receiveAction decode - org.json.JSONException: No value for params
```
Instead of showing the full stack trace.
=> fix(Android): replace error log with throw.

detox/android/detox/src/full/java/com/facebook/react/ReactInstanceEventListener.java, detox/android/detox/src/full/java/com/wix/detox/reactnative/ReactNativeLoadingMonitor.kt
- This pull request addresses the issue described here: #XXX
In this pull request, I have fixed a crash in registering an RN instance loading listener, in RN≤68 (following the release of the Detox `.aar` based on .68). See this [diff](https://github.com/facebook/react-native/compare/v0.67.4..v0.68.0#diff-2f01f0cd7ff8c9ea58f12ef0eff5fa8250cad144dd5490598d80d8e9e743458aR1009) --
`ReactInstanceManager.java`
The root of the problem is that at runtime, this error is thrown:
```
@Thread detox.primary(242):
java.lang.NoClassDefFoundError: Failed resolution of: Lcom\/facebook\/react\/ReactInstanceEventListener;
at com.wix.detox.reactnative.ReactNativeLoadingMonitor$subscribeToNewRNContextUpdates$1.run(ReactNativeLoadingMonitor.kt:38)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors …
```
=> fix(Android): Make RN instance listener work in RN≤68

.buildkite/jobs/pipeline.android_demo_app_rn_66.yml, .buildkite/pipeline_common.sh, scripts/demo-projects.android.sh, scripts/demo-projects.sh
- This pull request is associated with all post-factum work done in the context of #3492.
In this pull request, I have added a new (Android) CI job in order to regularly verify compatibility with older RN versions, of the `demo` project. An equivalent job already exists for the _main_ `test` app, although - #3492, which had to be reopened due to issues in production, has proven that this isn't enough.
There's a core difference between the `demo` and `test` projects: While the `test` app compiles Detox itself, bundled into the test .apk, the `demo` project precompiles Detox as an `.aar` and uses it. With that, the `demo` is (intentionally) much more similar to real-world users (in and out of Wix), and that can sometimes introduce specific edge-cases.
---
> …
=> ci: Introduce an additional job for RN 66 compat on Android

detox/src/devices/allocation/drivers/android/genycloud/GenyAllocDriver.js, detox/src/devices/allocation/drivers/android/genycloud/GenyAllocDriver.test.js, detox/src/devices/common/drivers/android/exec/ADB.js, detox/src/devices/common/drivers/android/exec/ADB.test.js
In this pull request, I have applied a work-around over a recently introduced (since August 1st) Genymotion-SaaS problem, where instance are launched with their WiFi toggle set to 'off', and thus without a network.
---
=> fix(Genycloud): Force-enable WiFi on instances by default

detox/src/utils/environment.js, detox/src/utils/environment.test.js
In this pull request, I have fixed error messages coming from failed `aapt` resolutions, of the following form:
```
12:05:47.946 detox[12345] ERROR: There was no "aapt" executable file in directory /Users/d4vidi/Library/Android/sdk/Users/d4vidi/Library/Android/sdk/build-tools/32.0.0.
Check integrity of your Android SDK.
```
As one can easily notice - the SDK path is duplicated!
Also, error was not descriptive enough for the (realistic?) case where the are no build-tools effectively installed under `build-tools/` (e.g. under `build-tools/32.0.0/`).
---
=> [post-workshop] Fix and improve error messages in aapt resolution

detox/test/android/settings.gradle
There is some missing configuration in settings.gradle according to the RN upgrade helper, and this leads to an error about `missing react-native-gradle-plugin` when dependencies upgrade to the new architecture. This PR adds the missing line.
Fixes issue #3548
=> fix(Android): Add react-native-gradle-plugin to settings.gradle

detox/src/devices/common/drivers/ios/tools/AppleSimUtils.js
I was having [problems running my detox tests in CI](https://github.com/invertase/react-native-firebase/runs/7816107911?check_suite_focus=true#step:23:19) (but not locally?) that looked exactly like #3518 and it seemed easy enough to patch, so I tried it and it seems to work for me.
Unsure on formatting here but either CI will tell me or you all will :-) - I was hacking it locally via patch-package so don't have devtools for the repo set up + available at the moment sorry
@asafkorem you marked this as assigned to yourself, so perhaps you want to give it a look?
Fixes #3518 (I think - it does for me anyway)
---
=> fix(ios): ignore "nothing to terminate" simctl error

detox/src/devices/common/drivers/android/tools/MonitoredInstrumentation.js, detox/src/devices/common/drivers/android/tools/MonitoredInstrumentation.test.js, detox/src/utils/errorUtils.js, detox/src/utils/errorUtils.test.js, detox/test/e2e/19.crash-handling.test.js, detox/test/e2e/utils/custom-expects.js
- This pull request is related to #3500. Fixes #3471.
Simply put, in this pull request, I have applied some changes to the error-utils such that _native_ stack traces, reported upon instrumentation "crashes", would be fully reported into the Jest summary message.
Namely, from this:
Into this:
---
=> Fix: Log native errors *with* stacktraces (no trimming), on Android

detox/android/detox/src/full/java/com/wix/detox/DetoxCrashHandler.kt, detox/android/detox/src/full/java/com/wix/detox/TestEngineFacade.kt, detox/src/client/Client.js, detox/src/client/Client.test.js, detox/src/devices/runtime/drivers/android/AndroidDriver.js, detox/src/devices/runtime/drivers/android/AndroidDriver.test.js, detox/test/android/app/build.gradle, detox/test/android/app/src/main/java/com/example/DetoxRNHost.java, detox/test/android/settings.gradle, detox/test/e2e/19.crash-handling.test.js, detox/test/index.android.js, detox/test/index.ios.js, detox/test/package.json, detox/test/src/app.js
Resolves #3500.
Adds a 3rd party dependency to read launch arguments (because seemingly we have it implemented only for Android):
```diff
+ "react-native-launch-arguments": "^3.1.0",
```
🤷‍♂️
=> fix(android): crash message handling on client.waitUntilAppIsReady

detox/test/android/app/build.gradle, detox/test/android/app/src/main/java/com/example/DetoxRNHost.java, detox/test/android/settings.gradle, detox/test/index.android.js, detox/test/index.ios.js
- This pull request is associated with #3500.
In this pull request, I have made changes that should stabilize, on Android, the crashing e2e-test that was added in #3498. In particular, I've eliminated usage of `react-native-launch-arguments` on Android, which seems to be unstable (sometimes it returns an empty set of launch arguments), which our very own implementation in the Detox test project's `NativeModule`.
---
=> Stabilize new crash e2e test on Android

detox/src/utils/trace.js, detox/src/utils/trace.test.js
Allow to pass a function that returns a promise as an argument to the `traceCall` function (undo [API](https://wix.github.io/Detox/docs/next/api/detox-object-api/#detoxtracecall) breakage introduced in https://github.com/wix/Detox/commit/450477f2fe2da98d32cacf25dbcc64e1cd991537).
See https://wix.github.io/Detox/docs/next/api/detox-object-api/#detoxtracecall
=> fix(trace): undo `traceCall` breaking change, accept function argument.

detox/runners/jest-circus/listeners/DetoxCoreListener.js
This change has no affect on functionality, as well as this field value, we override this field with the real test status anyway.
=> fix(DetoxCoreListener.js): remove duplicated `status` value.

detox/android/detox/src/main/java/com/wix/detox/common/TextFileReader.kt
In this pull request, I have introduced an attempt to fix the following rogue crash, appearing in one of Wix's internal modules - when integrating Android:
```
09-04 16:26:09.275  8015  8177 D Detox   : class com.wix.detox.Detox, startActivityFromNotification, [/data/local/tmp/detox/notification.json]
09-04 16:26:09.281  8015  8177 I DetoxActionHandlers: Test exception
09-04 16:26:09.281  8015  8177 I DetoxActionHandlers: java.lang.reflect.InvocationTargetException
09-04 16:26:09.281  8015  8177 I DetoxActionHandlers: 	at java.lang.reflect.Method.invoke(Native Method)
09-04 16:26:09.281  8015  8177 I DetoxActionHandlers: 	at org.apache.commons.lang3.reflect.MethodUtils.invokeStaticMethod(MethodUtils.java:443)
09-04 16:26:09.281  8015  8177 I DetoxActionHandlers: 	at …
```
=> Reimplement TextFileReader.read()

detox/index.d.ts, detox/local-cli/init.js, detox/src/configuration/composeAppsConfig.js, detox/src/configuration/composeAppsConfig.test.js, detox/src/devices/runtime/RuntimeDevice.js, detox/src/devices/runtime/RuntimeDevice.test.js, detox/src/errors/DetoxConfigErrorComposer.js, detox/src/errors/DetoxConfigErrorComposer.test.js, detox/src/errors/__snapshots__/DetoxConfigErrorComposer.test.js.snap, detox/test/e2e/detox.config.js, docs/guide/genymotion-cloud.mdx
Resolves #3494.
* Adds `reversePorts: number[]` property to Android app configs.
* Adds `reversePorts: [8081]` to generated template (`android.debug` app config)
* Explains how to use it with Genymotion SaaS.
=> feat(config): add reversePorts to app config

website/docusaurus.config.js
Replace the old App ID and Key given by Algolia DocSearch for Detox website search.
The old app was migrated recently by DocSearch to the new app, see the migration details here: https://docsearch.algolia.com/docs/migrating-from-legacy/.
Worth-noting, the search-only API key is **public and safe to use in production front-end code**, so there is no need to use a GitHub secret for it. From their website:
> [**Search-only API key**](https://www.algolia.com/doc/guides/security/api-keys/#search-only-api-key)
As a convenience, Algolia provides you with a search-only API key that allows you to search your data immediately. It works on all the indices of your application and is safe to use in your production front-end code. Nevertheless, you may want to use this key to create more restricted API …
=> chore(website): replace Algolia DocSearch app ID and app key.

detox/src/devices/allocation/drivers/android/emulator/AVDValidator.js, detox/src/devices/allocation/drivers/android/emulator/AVDValidator.test.js, detox/src/devices/allocation/drivers/android/emulator/EmulatorAllocDriver.js, detox/src/devices/allocation/drivers/android/emulator/EmulatorAllocDriver.test.js
This is a bugfix to address the `headless` config when running tests (invoked as `emulator -version` by the `AVDValidator`s emulator version validator.
- Resolves #3613 
In this pull request, I have forwarded the `headless` config option to the `AVDValidator` so that the existing emulator version query can operate as expected and in accordance to the configuration provided by the user
=> bugfix: avd validator emulator version should obey `headless`

detox/android/build.gradle, examples/demo-native-android/build.gradle, examples/demo-pure-native-android/build.gradle
Replace deprecated JCenter Bintray with Maven Center due to long outage.
Bintray is already deprecated and had its sunset long-ago, see [this blogpost](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter).
=> fix(android gradle): replace jcenter with maven-center.

website/src/components/Showcase/Showcase.module.css
This change affects small screens, where the showcase cards weren't centered in their container.
=> website(showcase): make container left padding same as the right.

detox/test/package.json
Version 0.5.13 is broken, let's follow on this issue: https://github.com/react-native-checkbox/react-native-checkbox/issues/182
We can unlock it again once there will be a proper solution.
=> test(dependencies): lock `react-native-community/checkbox` version.

.buildkite/jobs/pipeline.android_demo_app_rn_68.yml, .buildkite/jobs/pipeline.android_demo_app_rn_69.yml, .buildkite/jobs/pipeline.android_rn_68.yml, .buildkite/jobs/pipeline.android_rn_69.yml, .buildkite/jobs/pipeline.ios_demo_app_rn_68.yml, .buildkite/jobs/pipeline.ios_demo_app_rn_69.yml, .buildkite/jobs/pipeline.ios_rn_68.yml, .buildkite/jobs/pipeline.ios_rn_69.yml, README.md, detox/package.json, detox/test/package.json, examples/demo-react-native/package.json
Bump react-native versions due to test app's android build failures, resolved on the new patch versions.
Read the full incident details here: https://github.com/facebook/react-native/issues/35210.
=> 🚨 chore(deps): bump react-native versions (patch).

detox/package.json
Resolves #3690
The issue is likely caused by `yarn.lock` and `package-lock.json`.
In any case, this fix is legit because it tells us that we can't use `funpermaproxy@1.0.1` as a compromise version resolution anymore.
=> build: bump funpermaproxy@^1.1.0

website/package.json, website/src/components/Showcase/Showcase.js, website/src/components/Showcase/Showcase.module.css
Improved implementation and fixes the issue mentioned on this comment: https://github.com/wix/Detox/pull/3696#issuecomment-1312688280, for shuffling the cards order in the Showcase page.
=> website(showcase): shuffle apps order.

docs/introduction/partials/_getting-started-expo.md, docs/introduction/project-setup.mdx
Update Expo tab under the "Getting Started" doc, with their official documentation guide for Detox integration and rewriting it a bit.
=> docs(getting started): update expo tab.

detox/src/logger/DetoxLogger.js, detox/src/logger/DetoxLogger.test.js, detox/src/logger/__snapshots__/DetoxLogger.test.js.snap, detox/src/logger/utils/CategoryThreadDispatcher.js, detox/src/logger/utils/DetoxLogFinalizer.js, detox/src/logger/utils/MessageStack.js, detox/src/logger/utils/getMainCategory.js, detox/src/logger/utils/streamUtils.js
I noticed that when interrupting the `detox test` with Ctrl+C, I see a weird message `E` (end) event in the logs coming from an unrelated duration event.
This is a regression from my fix to #3639. The regression appeared because my mechanism for inferring logger end messages[^1] relied only on TID (thread ID). That was correct for the implementation generating unique TIDs, but now is not.
The fix to #3639 on purpose changed the invariant. Currently, the unique identifier for an asynchronous lane on the timeline is `${pid}:${mainCategory}:${tid}`, which is post-processed to a globally unique TID in the Chrome Trace Event document with a double-pass algorithm.
My PR adds a new test case demonstrating the issue, and I rewrote the `MessageStack` implementation to pass the new test. Besides, …
=> fix(logger): closing unbalanced duration events

detox/package.json, detox/src/ipc/IPCClient.js, detox/src/ipc/IPCServer.js, detox/src/ipc/SessionState.js, detox/src/ipc/SessionState.test.js, detox/src/ipc/ipc.test.js, detox/src/realms/DetoxSecondaryContext.js
This PR adds integration tests for `IPCServer` and `IPCClient`, along with unit tests for the `SessionState`, which is used by them.
@noomorph
=> test: add tests for IPCClient & IPCServer integration.

detox/src/logger/utils/DetoxLogFinalizer.js, detox/src/logger/utils/DetoxLogFinalizer.test.js
Resolves #3679
Currently, when using `--record-logs failed` and interrupting Detox in the middle, it does not save the logs because it has not received a signalization about failing tests, so the logic is way too straightforward – discard the logs.
I suggest treating Ctrl+C (SIGINT, SIGTERM, etc) as an unsuccessful run so the logs are saved regardless.
That should reduce frustration when you are running into some timeout issues, and you want to interrupt Detox to read some saved logs, but oops – "no error, no logs". The latter rule is too strict, to my taste, in this case.
=> fix(logger): save files on Ctrl+C

website/versioned_docs/version-20.x/introduction/project-setup.mdx
I just went through the website docs on [Project Setup](https://wix.github.io/Detox/docs/introduction/project-setup/) for Android. Everything went smoothly except for the line about the `proguardFile`.
Following the website docs as is, I get an error that says "Project with path ':detox' could not be found in project ':app'". With the proposed change, Gradle is happy. Also, this change brings the website's `proguardFile` docs in line with what I found [here](https://github.com/wix/Detox/blob/master/website/versioned_docs/version-20.x/guide/proguard-configuration.md).
=> [website] Update Android project setup docs on proguardFile

detox/src/logger/utils/DetoxLogFinalizer.test.js, detox/src/logger/utils/streams/ChromeTraceTransformer.js
In this PR, I make it simpler to infer which PID is primary (when creating a Detox trace file).
Instead of making this logic tightly coupled with `process.pid`, I check which PID appears first.
That simplifies unit tests and makes the code more generic and reusable.
=> refactor(trace): simpler primary PID detection

.buildkite/pipeline.release.fast.yml
This fixes the release process, since it was broken with the error:
```
ERROR: JAVA_HOME is set to an invalid directory: /usr/local/opt/openjdk@11/
  |  
  | Please set the JAVA_HOME variable in your environment to match the
  | location of your Java installation.
```
`JAVA_HOME` variable assigning was recently removed from other pipelines except for the release pipeline as part of the mac-mini bare metal migration, this removal was missed in the migration removals PR: https://github.com/wix/Detox/pull/3742 (`pipeline.release.fast.yml` is being used for both fast and non-fast releases)
=> ci: remove invalid `JAVA_HOME` variable setting.

docs/api/device.md, docs/api/webviews.md, docs/introduction/partials/_getting-started-expo.md
Fix broken links and remove warnings by Remark and Markdownlint.
=> docs: fix lint errors

detox/src/devices/lifecycle/GenyGlobalLifecycleHandler.js, detox/src/devices/lifecycle/GenyGlobalLifecycleHandler.test.js, detox/src/logger/DetoxLogger.js, detox/src/utils/ExclusiveLockfile.js
1. Fix chalk typing (use default).
2. Replenish test coverage for a very trivial case (globalInit is an empty function).
=> lint: fix trivial errors

detox/package.json, detox/src/configuration/collectCliConfig.js, detox/src/configuration/index.test.js, detox/src/devices/runtime/RuntimeDevice.test.js, detox/src/utils/argparse.js, detox/src/utils/argparse.test.js
Turns out, we don't need this package anymore since Detox 20 huge refactors in config.
And this is for the good, because earlier we had two different libraries for parsing `process.argv` under the same roof.
This is a refactor PR without intended side effects.
=> refactor: drop minimist package

detox/__tests__/helpers.js, detox/local-cli/__mocks__/executable, detox/local-cli/test.test.js, detox/package.json
This PR prepares ground for the `detox start` PR #3766.
It makes it simple to use the mock `executable` script for integration tests in `local-cli` subpackage when we're testing that the arguments and environment are passed correctly to the child processes.
=> refactor(tests): reusable cli mock

detox/.eslintrc.js, detox/src/artifacts/templates/plugin/ArtifactPlugin.js, detox/src/artifacts/templates/plugin/TwoSnapshotsPerTestPlugin.js, detox/src/artifacts/templates/plugin/WholeTestRecorderPlugin.js, detox/src/client/AsyncWebSocket.js, detox/src/configuration/composeLoggerConfig.js, detox/src/devices/allocation/drivers/AllocationDriverBase.js, detox/src/devices/allocation/factories/base.js, detox/src/devices/runtime/drivers/android/AndroidDriver.js, detox/src/devices/runtime/factories/android.js, detox/src/devices/runtime/factories/base.js
- This pull request addresses the issue described here: #3292
Mostly, I fix this by relaxing ESLint rule for unused function **args** only.
Unfortunately, I can't make it smarter (it does not discern concrete and virtual methods), so this is the most I can come up with.
On the other side, allowing unused variables is a road to hell, so I'm better off with special ESLint comments than with disabling it at all.
=> lint: fix "unused" warnings

detox/src/android/AndroidExpect.test.js, detox/src/android/espressoapi/EspressoDetox.js, detox/src/android/espressoapi/web/WebElement.js, generation/core/type-checks.js
I noticed thanks to the linter that our assertion here was never correct:
```diff
-if (typeof X !== 'object' || !X instanceof Array) {
+if (typeof X !== 'object' || !Array.isArray(X)) {
```
That's because `!X` gets evaluated as a boolean first, and then it is never an instance of an array, for an obvious reason.
=> fix(generation): invalid isArray assertion

detox/src/logger/utils/BunyanLogger.js, detox/src/realms/DetoxPrimaryContext.js, detox/src/realms/DetoxPrimaryContext.test.js, detox/test/integration/utils/simplistic-runner.js
In this pull request, I fix two things at once – unfortunately, it is impossible to split them without making the build red:
1. The `simplistic-runner` integration test:
* now it exits with a non-zero code when it catches an error
* due to a freshly revealed error, I fixed the `!=` typo (and make `!== null` check strict as it was initially intended by me in Detox 20).
2. The logging after calling `detox.cleanup()`. When I started debugging the issues in the integration test, it turned out that `console.error(e)` call was not producing **anything**. So I had to go to the logger and see why, and I found two issues:
* the `BunyanLogger#installDebugStream` fails to **replace** the stream - instead it just adds one more stream
* the `BunyanLogger#closeFileStreams` closes `tty` streams …
=> fix: logger termination and detox init

detox/src/logger/DetoxLogger.js, detox/src/logger/DetoxLogger.test.js, detox/src/logger/__snapshots__/DetoxLogger.test.js.snap, detox/src/utils/isPromise.js, detox/src/utils/isPromise.test.js, detox/test/integration/__snapshots__/timeline-artifact.test.js.snap, detox/test/integration/e2e/flaky.test.js
Consider this code in userbase:
```js
detox.log.trace.complete('Navigating to Sanity', async () => {
detox.log.trace('Reloading app');
await device.reloadReactNative();
detox.log.trace('Tap on Sanity');
await element(by.text('Sanity')).tap();
detox.log.trace('I am on Sanity screen');
});
```
Begin event, instant event x 3, End event
```
|B-- Navigating to Sanity --E|
|---i----------i---------i---|
```
```
|B-- E-----------------------|
|---i----------i---------i---|
```
The **sandboxed** `Promise` constructor fails the previously implemented `isPromise` check:
```
obj = [Promise*]
Promise.resolve(obj) !== obj
```
It is fair enough to expect any Promise-like object in such logger calls, so I switched the implementation to `isPromiseLike` with a duck typing check: if it has `.then` …
=> fix(logger): complete events in sandbox

docs/contributing.md, docs/demo.mdx, website/docusaurus.config.js
Create mdx demo page for internal styleguide related to documentation.
The components presented in the Demo page are:
headings,
headers,
various links,
images,
tables,
admonitions,
tabs,
code fragments,
JS/Java/Shell/JSON highlighting,
code blocks with differing highlights (also include the code blocks where there are lines added or removed (+ or -) like you see in GH PRs
Multi and single-line paragraphs accounting for spacing that could be different between them and different sizes of headers
Attached screencast to show page visually in this PR
cc: @asafkorem
=> [Website]: Documentation MDX Demo Page

detox/package.json
- This pull request addresses the issue described here: #3849 
In this pull request, I have simply increased the minimum `lodash` requirement from `^4.17.5` to `^4.17.11`, since before PR #3851 Detox relied on `merge` behaviour from lodash that was only fixed in `4.17.11`.
---
=> build: increase minimum lodash requirement

detox/src/configuration/composeLoggerConfig.js, detox/src/configuration/composeLoggerConfig.test.js
Turns out, that in older Lodash versions (`<=4.17.10`), `_.merge({ a: function () { /*...*/ } }, { a: { b: 'c' } })` does not overwrite the `a` property.
See: https://github.com/lodash/lodash/wiki/Changelog#v41711
> Ensured _.merge handles function properties consistently regardless of number of sources
- This pull request addresses the issue described here: #3849.
In this pull request, I added a fix and a test for this situation. By adding an initial value (`{}`) to the reducer, I prevent this possibility.
@tyronet-sportsbet, huge thanks to you!
@d4vidi let's reserve an achievement **NPM Detective** for @tyronet-sportsbet in our future "Contributors" section on the website.
=> fix: incorrect session serialization

website/package.json, website/snapshots.yml
In this pull request, I have done the following:
- set up test suite in website project using Percy CLI
- create YAML test pages for homepage, showcase page, blog page and demo page
- light and dark modes
Resolves #3838.
NOTE:
Need to verify Percy.io dashboard functions correctly on image uploading. Some pages are not displaying correctly:
=> [Website] Create a visual regression test suite

detox/android/detox/build.gradle, detox/android/detox/src/full/java/com/wix/detox/espresso/DetoxAction.java, detox/index.d.ts, detox/src/android/AndroidExpect.test.js, detox/src/android/actions/native.js, detox/src/android/core/NativeElement.js, detox/src/android/espressoapi/DetoxAction.js, detox/src/ios/expectTwo.js, detox/src/ios/expectTwo.test.js, detox/src/utils/dateUtils.js, detox/src/utils/dateUtils.test.js, detox/test/android/app/build.gradle, detox/test/android/app/src/main/java/com/example/DetoxRNHost.java, detox/test/android/settings.gradle, detox/test/e2e/17.datePicker.test.js, detox/test/package.json, detox/test/src/Screens/DatePickerScreen.js, detox/test/src/app.js, docs/api/actions.md, examples/demo-pure-native-android/app/build.gradle
- This pull request addresses the issue described here: #3789 
In this pull request, I have extended the setDatePickerDate action to work on android as well.
setDatePickerDate is already working for android in this pr and I also updated one relevant test.
I have yet to investigate whether more tests need changes. 
I also have yet to update the docs.
Feel free to comment on how to improve this implementation.
=> feat(android): support setDatePickerDate

detox/local-cli/run-server.js, detox/src/utils/logger.js
Resolves #3886.
Although the suggested solution is a bit hacky, it is good enough to fix the reported issue.
Among less hackier ways to fix it was to change `run-server` signature to accept `-c ...configuration name` instead of using direct `-p <port>`, but I don't want to introduce breaking changes at the moment.
On the other hand, the `run-server` concept itself might be outdated in the light of the recent architectural shift towards encapsulating such functionality entirely inside drivers, so it's not worth serious investment at the moment anyway.
=> fix(cli): detox-server should consider --loglevel

detox/src/android/AndroidExpect.test.js, detox/src/android/core/NativeWaitFor.js, detox/src/ios/expectTwo.js, detox/src/ios/expectTwoApiCoverage.test.js, detox/test/e2e/05.waitfor.test.js, detox/test/src/Screens/WaitForScreen.js
I've run into this in my tests:
```
TypeError: (0 , _detox.waitFor)(...).toBeFocused is not a function
6 |     await waitFor(element(by.id('email-input')))
>  7 |       .toBeFocused()
|        ^
8 |       .withTimeout(5000);
```
TypeScript suggested it was possible, but the methods were missing
=> fix: missing method waitFor(...).toBeFocused()

detox/src/devices/common/drivers/android/genycloud/exec/GenyCloudExec.js, detox/src/devices/common/drivers/android/genycloud/exec/GenyCloudExec.test.js
In this pull request, I have repeated #3926 by @lilinor with the necessary unit-test fixes.
---
=> [Genymotion SaaS] Update gmsaas start flag to fix wrong device timeout

detox/runners/jest/index.d.ts, detox/runners/jest/testEnvironment/index.js, detox/test/types/detox-integration-tests.ts
- This pull request addresses the issue described here: #3721
In this pull request, I convert `handleTestEvent` to a regular class method that subclasses can override.
=> fix(jest): allow overriding handleTestEvent

detox/ios/Detox.xcodeproj/project.pbxproj, detox/ios/Detox/Actions/UIApplication+DetoxActions.swift, detox/ios/Detox/DetoxManager.swift
- This pull request addresses the issue described here: https://github.com/wix/Detox/issues/3823
In this pull request, I have used the new iOS orientation APIs available from iOS 16 onwards, instead of the UIDevice orientation API's (which no longer work when building using Xcode 14 and running on iOS 16+).
_Note: I need some help/advice on how to verify these changes locally. No matter how I run it doesn't seem to be pulling in my code changes. I've tried intentionally putting compilation errors in the code and the tests still build and run without issue. I've ran `lerna bootstrap`, following by `yarn build:ios` and `yarn e2e:ios`. The tests run but don't seem to be exercising any new code._
---
=> fix: device.setOrientation for iOS 16

detox/ios/Detox/DetoxInit.m, detox/test/e2e/14.network.test.js, docs/api/device.md
- This pull request fixes #3953
In this pull request, I have aligned the usage of the `detoxURLBlacklistRegex` to the docs (and Android).
Apparently, `detoxURLBlacklistRegex` cannot be extracted from `NSUserDefaults` as an `arrayForKey` (`nil` is returned). Therefore, I've switched to `stringForKey` and implemented a simplified means of string-splitting.
I honestly don't know whether this has ever worked before - perhaps in older iOS versions. In any case, it is what it is... Thanks to the added coverage we shouldn't be having this regression in the future.
---
=> Fix detoxURLBlacklistRegex arg for launchApp() on iOS

detox/test/e2e/14.network.test.js
- This pull request addresses the issue described here: #3953.
In this pull request, I have followed up on @asafkorem's comment on #3954, and optimized network testing. I took the extra mile and introduced a subtle driver, to help out with code duplication, etc.
---
=> e2e: Improved network tests styling and robustness

detox/src/android/AndroidExpect.test.js, detox/src/android/core/NativeMatcher.js, detox/src/ios/expectTwo.test.js, detox/test/e2e/04.assertions.test.js, detox/test/src/Screens/AssertionsScreen.js
- This pull request is related the issue described here: #3977
This pull request introduces some preliminaries to #3977: It cleans up some Detox self-tests related to expectations (assertions). That allows, in turn, to introduce further tests related to that issue.
- Eliminated assertion E2E tests that have already been covered on unit-test level (i.e. invalid args detection).
- Improved expect unit-testing:
- Replaced custom `expectToThrow()` with jest's `expect().toThrow()` which does the same thing
- Removed the `by.traits()` test for unsupported traits at unit level, which only make sense on E2E-level because the error should come from native-detox code (todo: add such E2E's)
- Added missing invalid-args assertions in some `expect()` calls which were unit-tested to throw but didn't …
=> Improve quality of testing over Detox assertions (expects etc.)

docs/introduction/project-setup.mdx
This docs-only PR fixes indentation of the changes to `android/build.gradle` in Project Setup.
Currently in 20.x and Next what is shown is:
Note that `google` and `maven` are indented the same amount as `allrepositories`, even though they are nested under it.
I actually made a mistake in setting up Detox in my Android project as a result, because I'm not familiar with native Android development. I thought `google` and `maven` _did_ belong at the same level as `allrepositories` instead of underneath it. When I tried this, my project would not build.
This update makes the indentation more clear so users are less likely to be confused or make the same error as I did. Now it shows:
=> Docs: fix android/build.gradle indentation

detox/src/DetoxWorker.js, detox/src/devices/allocation/DeviceAllocator.js, detox/src/devices/allocation/DeviceAllocator.test.js, detox/src/devices/allocation/drivers/AllocationDriverBase.js, detox/src/devices/allocation/drivers/android/attached/AttachedAndroidAllocDriver.js, detox/src/devices/allocation/drivers/android/attached/AttachedAndroidAllocDriver.test.js, detox/src/devices/allocation/drivers/android/emulator/EmulatorAllocDriver.js, detox/src/devices/allocation/drivers/android/emulator/EmulatorAllocDriver.test.js, detox/src/devices/allocation/drivers/android/genycloud/GenyAllocDriver.js, detox/src/devices/allocation/drivers/android/genycloud/GenyAllocDriver.test.js, detox/src/devices/allocation/drivers/ios/SimulatorAllocDriver.js, detox/test/e2e/detox.config.js, docs/articles/third-party-drivers.md
- This pull request addresses the issue described here: #3655
In this pull request, I have added a new method, `postAllocate` to the device allocation drivers, which is an optional method to handle operations after the device is allocated, such as waiting until the boot animation is finished, configuring the device, etc.
```diff
class MyNewAllocationDriver {
constructor(deps) {
this.emitter = deps.eventEmitter;
}
async allocate(deviceConfig) {
// ...
return new Cookie(id); // This is where a cookie is formed once for the entire process
}
+  async postAllocate(cookie) {
+   // Optional method to handle operations after the device is allocated
+    // like waiting until the boot animation is finished, configuring the device, etc.
+  }
async free(cookie, options) {
// ...
}
}
```
This helps …
=> feat(drivers): add postAllocate() method

detox/src/devices/allocation/drivers/android/genycloud/GenyAllocDriver.js, detox/src/utils/Timer.js, detox/src/utils/Timer.test.js
This pull request should allow users to utilize CI agents better until we come up with a specific recovery logic.
I wonder if using ` gmsaas instances adbdisconnect` + ` gmsaas instances adbconnect` retry loop could help.
According to internal bug reports (see the screenshot above), when Genymotion SaaS instances hang up, the first code to start choking is this sequence:
```js
await this._adb.disableAndroidAnimations(adbName);
await this._adb.setWiFiToggle(adbName, true);
await this._adb.apiLevel(adbName);
```
I added a heuristical timeout to detect this state quicker than wait 180s (or 300s) until Jest Environment times out:
```diff
+    await Timer.run(20000, 'waiting for device to respond', async () => {
await this._adb.disableAndroidAnimations(adbName);
await …
```
=> perf(genymotion): fail-fast when device hangs

docs/api/device.md, website/versioned_docs/version-20.x/api/device.md
Without the backward slash before, `d{4}` will not be handled as a regex pattern.
In this example `\d{4}` is used to match exactly four consecutive digits (which is the port component in this case).
=> docs: fix `detoxURLBlacklistRegex` usage example.

detox/package.json
https://github.com/sindresorhus/find-up/releases/tag/v5.0.0
Only breaking change is it drops node 10 support.
I didn't bump to 6.x now, since that version is rewritten to ESM.
Related to https://github.com/wix/Detox/issues/3994
=> Bump find-up to 5.x

detox/package.json
A new major version has been out for a while for both.
https://github.com/yargs/yargs/blob/main/CHANGELOG.md https://github.com/yargs/yargs-parser/blob/main/CHANGELOG.md
The biggest breaking change in both libraries is that they've dropped node 10 support, which is already dropped by Detox.
Related to https://github.com/wix/Detox/issues/3994
=> Update yargs + yargs-parser dependencies

.editorconfig, docs/demo.mdx, website/package.json, website/percy.mjs, website/src/css/_markdown.scss
- This pull request addresses the issue described here: #4016 
Targeted the issue causing long code line headers overlaying on other elements:
- Remove markdown code added with `white-space: pre` in SCSS markdown file
- Added test case to the _demo page
---
cc: @asafkorem
=> [Website] Fix issue overlay docs code headers

.buildkite/jobs/pipeline.android_rn_68.yml, .buildkite/jobs/pipeline.android_rn_70.yml, .buildkite/jobs/pipeline.ios_rn_68.yml, .buildkite/jobs/pipeline.ios_rn_70.yml, .gitignore, scripts/create_iframe_html.js, scripts/upload_artifact.sh
This pull request should improve UX when visiting Buildkite build artifacts. Instead of having to download, unpack and open the allure reports, we should be able to open straight from UI the html files pointing us to the static hosting on surge.sh, where the reports will be residing from now on.
Ideally, we should create a nightly job to delete old domains with reports.
=> ci: allure reports as html

.github/workflows/surge-purge.yml, scripts/purge_expired_domains.mjs
Adds a cron script to purge old domains allocated on Surge.sh for displaying Allure reports on Buildkite.
=> ci(github): add purge domains cron script

detox/test/android/app/build.gradle, detox/test/android/app/src/main/java/com/example/DetoxRNHost.java, detox/test/android/app/src/main/java/com/example/NativeModule.java, detox/test/android/settings.gradle, detox/test/index.android.js, detox/test/index.ios.js, detox/test/package.json, detox/test/src/Screens/AbstractArgsListScreen.js, detox/test/src/Screens/LaunchArgsScreen.js
- This pull request addresses the issue described here: https://github.com/iamolegga/react-native-launch-arguments/issues/44
In this pull request, I have restored the usage of `react-native-launch-arguments` in Detox's self-test project.
Context: While revisiting https://github.com/iamolegga/react-native-launch-arguments/issues/44, it has occurred to me through the details of the problem that its root could be in a react native bug. This is due to the following circumstances:
- The bug stems from `LaunchArgumentsModule.getConstants()` returning an empty map
- Source code shows this can happen if there is no intent available (unlikely) or otherwise in case there's no activity available (might be?).
- Deduced: because `getConstants()` is a react-native framework-level hook, it doesn't make …
=> Restore usage of launch-args lib

detox/local-cli/startCommand/AppStartCommand.js
After running Detox tests in one of the projects, I noticed that after pressing the `Enter` key, I see this:
```
... detox test finishes ...
my-project> [I'm pressing Enter key and boom!]
node:events:491                                                                                                                                                                                                                                                               
throw er; // Unhandled 'error' event
^
Error: read EIO
at TTY.onStreamRead (node:internal/stream_base_commons:217:20)
Emitted 'error' event on ReadStream instance at:
at emitErrorNT (node:internal/streams/destroy:157:8)
at emitErrorCloseNT (node:internal/streams/destroy:122:3)
at processTicksAndRejections …
```
=> fix(cli): unhandled rejection after tests

detox/android/build.gradle
In this pull request, I have fixed Kotlin compatibility issues arising in internal builds, in the form of this error:
```
[21:04:51][Multi-app build] e: /Users/builder/.gradle/caches/transforms-3/7e1994271b0ac195885b9b3cc4f97c1e/transformed/jetified-detox-20.11.0-api.jar!/META-INF/detox_fullRelease.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
[21:04:52][Multi-app build] 
```
---
=> fix(android): Revert used kotlin ver due to compat. issues

detox/test/ios/Podfile
This PR contains two fixes to be able to build on Xcode 15:
- Add Podfile workaround to be able to build with Xcode 15 (see: https://github.com/facebook/react-native/issues/37748).
- Upgrade LNViewHierarchyDumper with the latest version that supports Xcode 15 with iOS 17 (see: https://github.com/wix/Detox/issues/4149).
=> fix(iOS): ensure compatibility with Xcode 15.

detox/android/rninfo.gradle
this Gradle script assumes that the working directory is always the android working directory. When you run something like fastlane, that runs gradle scripts from your react-native project root, the working directory is NOT the android directory
Use gradle's `project.rootDir` variable instead to ensure that we're always in the right working directory instead of assuming this to be true
=> Ensure correct working directory

detox/src/devices/common/drivers/ios/tools/AppleSimUtils.js
The error message when failing to terminate has changed on a recent simctl version: `The request to terminate "com.wix.detox-example" failed. found nothing to terminate`
=> fix(iOS): adapt to new nothing-to-terminate error.

detox/ios/Detox/DetoxManager.swift, detox/ios/Detox/Invocation/Expectation.swift
Workaround to avoid reporting did-set-orientation prematurely on iOS 16 and above.
This workaround reports the operation as done after a brief delay to ensure it isn't sent too soon.
Recently, we modified the `setOrientation` implementation for iOS 16 and above in response to changes in iOS (https://github.com/wix/Detox/pull/3843, https://developer.apple.com/videos/play/wwdc2022/10068/?time=1400). 
It seems that the Simulator's orientation change is no longer instantaneous. The OS seems to invoke this action after a brief delay, and during this time, nothing runs on the main thread.
This issue will be addressed (without needing a workaround) in Detox v21, by utilizing [`XCUIDevice.orientation`](https://developer.apple.com/documentation/xctest/xcuidevice/1619046-orientation).
=> fix(iOS): resolve flaky set-orientation on iOS ≥ 16.

detox/android/detox/build.gradle
Resolves https://github.com/wix/Detox/issues/4106.
See recommended fixes ([synk.io](https://security.snyk.io/package/maven/org.json:json)):
https://security.snyk.io/vuln/SNYK-JAVA-ORGJSON-5488379
https://security.snyk.io/vuln/SNYK-JAVA-ORGJSON-2841369
=> chore(android): bump `org.json:json` (vulnerable version).

detox/android/detox/src/full/java/com/wix/detox/espresso/DetoxAssertion.java, detox/android/detox/src/full/java/com/wix/detox/espresso/EspressoDetox.java, detox/android/detox/src/full/java/com/wix/detox/espresso/performer/MultipleViewsActionPerformer.kt, detox/android/detox/src/full/java/com/wix/detox/espresso/performer/SingleViewActionPerformer.kt, detox/android/detox/src/full/java/com/wix/detox/espresso/performer/ViewActionPerformer.kt, detox/android/detox/src/full/java/com/wix/invoke/types/Invocation.java, detox/android/detox/src/main/java/com/wix/detox/espresso/MultipleViewsAction.kt, detox/android/detox/src/main/java/com/wix/detox/espresso/UiControllerSpy.kt, detox/android/detox/src/main/java/com/wix/detox/espresso/ViewActionWithResult.kt, detox/android/detox/src/testFull/java/com/wix/detox/espresso/performer/ViewActionPerformerSpec.kt, detox/src/android/core/NativeElement.js, detox/src/android/espressoapi/DetoxAssertion.js, detox/src/android/espressoapi/EspressoDetox.js, detox/src/android/interactions/native.js
This PR enhances Detox's ability to work with actions on multiple matching views on Android. The aim is to provide greater flexibility for actions, allowing them to handle both single and multiple view scenarios declaratively.
As of now, Detox struggles with scenarios where `getAttributes()` is required to operate on several matched elements on Android, even though this is supported on iOS. This PR lays the groundwork to rectify this discrepancy, paving the way for full implementation in a subsequent PR.
See: https://github.com/wix/Detox/issues/3196
- The existing `perform` method in the `EspressoDetox` class relies on `ViewInteraction`, which doesn't naturally cater to multiple matching views.
- To sidestep the challenge posed by `viewInteraction = onView(matcher)`, we transitioned the …
=> feat(android): add support for multiple-views actions.

.editorconfig, .github/workflows/broken-links-scan.yml, .github/workflows/docs.yml, .github/workflows/rapid-test.yml, .github/workflows/surge-purge.yml, .github/workflows/website.yml, .npmrc, .nvmrc, lerna.json
Node 14 has been deprecated for too long already.
While we technically still support Node 14 in Detox 20, let's move to Node 16.x at least for the local development.
=> chore: use node 16 for local development

detox/android/detox/build.gradle, detox/android/detox/src/full/java/com/wix/detox/espresso/action/AdjustSliderToPositionAction.kt, detox/android/detox/src/full/java/com/wix/detox/espresso/action/GetAttributesAction.kt, detox/android/detox/src/full/java/com/wix/detox/espresso/common/MaterialSliderHelper.kt, detox/android/detox/src/full/java/com/wix/detox/espresso/common/ReactSliderHelper.kt, detox/android/detox/src/full/java/com/wix/detox/espresso/matcher/ViewMatchers.kt, detox/android/detox/src/testFull/java/com/wix/detox/espresso/common/MaterialSliderHelperTest.kt, detox/android/detox/src/testFull/java/com/wix/detox/espresso/common/ReactSliderHelperTest.kt
This fixes a `ClassNotFoundException` error that is thrown when the Slider class from the `com.google.android.material.slider` package is not found at runtime.
The solution is to use reflection instead of importing the Slider class, which may not necessarily exist in the app.
Also, I made a light refactoring for get-attributes related code.
=> fix(android): extract material slider value attribute with reflection.

detox/test/index.android.js, detox/test/index.ios.js, detox/test/registerEarlyCrashIfNeeded.js
This resolves a flakiness in tests where the early-crash invoked too early on iOS and a timeout is thrown instead of error being catch using the same resolution from the Android test app
=> test(fix, ios): use common register-early-crash method.

detox/android/detox/src/full/java/com/wix/detox/ActivityLaunchHelper.kt, detox/android/detox/src/full/java/com/wix/detox/Detox.java, detox/android/detox/src/full/java/com/wix/detox/DetoxMain.kt, detox/android/detox/src/full/java/com/wix/detox/LaunchIntentsFactory.kt, detox/android/detox/src/full/java/com/wix/detox/adapters/server/DetoxActionHandlers.kt, detox/android/detox/src/full/java/com/wix/detox/adapters/server/DetoxServerInfo.kt, detox/android/detox/src/full/java/com/wix/detox/reactnative/ReactMarkersLogger.kt, detox/android/detox/src/full/java/com/wix/detox/reactnative/ReactNativeExtension.kt, detox/android/detox/src/main/java/com/wix/detox/espresso/UiControllerSpy.kt, detox/package.json, detox/src/android/espressoapi/Detox.js, detox/test/e2e/19.crash-handling.test.js, detox/test/package.json, examples/demo-native-android/package.json, examples/demo-native-ios/package.json, examples/demo-plugin/package.json, examples/demo-react-native-detox-instruments/package.json, examples/demo-react-native/package.json, lerna.json, package.json
In this pull request, I have made adjustments to the way the app's activity is launched by Detox, making it in a more supervised way and thus more debuggable. That includes the following:
1. React markers, noting important things such as Javascript loading, bundle downloading, native package initialization, etc. - are now logged by Detox. To avoid log spamming, only major "root" events are logged.
1. Before this change, the app's activity used to be launched in the very beginning of Detox (i.e. the beginning of the Detox native test, namely, in `Detox.java`). This means that things such as app crashes / ANR's were not reported to the test runner, if happening at a very early stage. This PR introduces a fundamental change where …
=> (Android) Make activity launch more supervised, debuggable

docs/guide/android-dev-env.md
Added documentation on how to list all available device specs - for convenience when setting up a new emulator.
=> docs(android-dev-env): document how to list available device specs

detox/android/detox/src/main/java/com/wix/detox/espresso/action/common/MotionEvents.kt
- This pull request addresses the issue 3762 described here: https://github.com/wix/Detox/issues/3762
In this pull request, I have updated `obtainUpEvent` in `com.wix.detox.espresso.action.common.MotionEvent` to match more closely the implementation of `obtainUpEvent` in `androidx.test.espresso.action.MotionEvents`.
=> fix(android): tap event on android API>31

generation/package.json
* Updates Jest in `generation` project to 27.x.x
* Dogfooding allure reporter alpha there as well
=> chore: bump generation deps

detox/src/devices/common/drivers/android/tools/instrumentationArgs.js, detox/src/devices/common/drivers/android/tools/instrumentationArgs.test.js, detox/test/e2e/15.urls.test.js
- This pull request addresses the issue described here: #4196 
In this pull request, I have added POSIX escaping for arguments passed to `adb shell ...` in one forgotten place.
=> fix(android): escape instrumentation args

detox/android/detox/build.gradle
I may be wrong, but I believe this is necessary for android gradle plugin 8 compatibility, which is what react-native 0.73 will ship with. I'm working through compat issues right now as I bump into them, testing release candidates
> fix(android): add namespace to build.gradle for android gradle plugin 8 compatibility
Related: https://github.com/invertase/react-native-firebase/commit/19ae9b8cb66d16fa20c7ff00d6da1a81438c7030
=> fix(android): add namespace to build.gradle for android gradle plugin 8 compatibility

detox/detox.d.ts, detox/internals.d.ts, detox/local-cli/test.test.js, detox/local-cli/testCommand/TestRunnerCommand.js, detox/local-cli/utils/interruptListeners.js, detox/runners/jest/testEnvironment/index.js, detox/src/configuration/composeRunnerConfig.js, detox/src/configuration/composeRunnerConfig.test.js, detox/src/ipc/IPCClient.js, detox/src/ipc/IPCServer.js, detox/src/ipc/ipc.test.js, detox/src/realms/DetoxContext.js, detox/src/realms/DetoxPrimaryContext.js, detox/src/realms/DetoxSecondaryContext.js, detox/test/e2e/detox.config.js, detox/test/integration/jest.config.js, docs/config/testRunner.mdx
In this pull request, I have added a new feature, **detached mode** for test runners.
Default: `false`.
When true, tells `detox test` to spawn the test runner in a detached mode.
This is useful in CI environments, where you want to intercept SIGINT and SIGTERM signals to gracefully shut down the test runner and the device.
Instead of passing the kill signal to the child process (the test runner), Detox will send an emergency shutdown request to all the workers, and then it will wait for them to finish.
```diff
args: {
$0: 'jest',
config: 'e2e/jest.config.js',
+      forceExit: process.env.CI ? true : undefined,
_: ['e2e/'],
},
+    detached: !!process.env.CI,
retries: process.env.CI ? 1 : undefined,
```
Detox will exit indirectly through Jest using the same mechanism as in our `--bail` …
=> feat(cli): detached runner

detox/package.json, detox/test/package.json, generation/package.json
Version 2.0.0-alpha.8 brings broken/failed tests distinction, basic docblocks support, and syntax highlighting to the test descriptions.
=> chore: bump jest-allure2-reporter

docs/guide/launch-args.md
The existing docs describe how to grab the launchArgs natively on Android, but not on iOS, so after doing some research, I wanted to add this here so iOS is also described. 
Very simple change to explain what is meant by "normal means", which required a bit of research on my end. Since this is a very small docs change, I hope you don't mind that I didn't flesh out the entire PR checklist.
=> docs: update Launch Args guide

.github/workflows/rapid-test.yml, detox/package.json, detox/test/package.json, generation/package.json
This pull request brings the new version of Allure reporter [with basic support for the "Executor Info" widget](https://github.com/wix-incubator/jest-allure2-reporter/pull/18) (contains links to the CI build, info about the build agent, etc).
That's why I added also an upload step to our Github Actions pipelines so that we can see how well it works.
=> chore: bump jest-allure-reporter@2.0.0-alpha.11

detox/src/utils/childProcess/spawn.js
This is a very minor internal issue. When releasing Detox 20.0.0, I missed this place, and it distorts a bit our logs in non-sanitized mode.
We never noticed `pid → pid` overwrite only because I implemented sanitization and it gets written as `pid$` in our logs.
Nevertheless, my original intent was to keep this as `cpid`. I have `cpid` (child process id) name in other places, and this one was just accidentally left.
=> fix: stop pid override in logs

detox/jest.config.js, detox/src/DetoxWorker.js, detox/src/DetoxWorker.test.js, detox/src/ipc/IPCClient.js, detox/src/ipc/IPCServer.js, detox/src/ipc/ipc.test.js, detox/src/realms/DetoxContext.js, detox/src/realms/DetoxPrimaryContext.js, detox/src/realms/DetoxPrimaryContext.test.js, detox/src/realms/DetoxSecondaryContext.js, detox/src/realms/__snapshots__/DetoxPrimaryContext.test.js.snap
This is an internal pull request to enable driver-less initialization in the primary context unless it is really needed (when a worker allocates a device).
As an implementation choice, I allow the creation of multiple device allocators simultaneously in the primary context in a lazy fashion. To map device allocator implementation to a specific cookie, we host a small map of {cookie.id}-{deviceAllocator instance}. On the cleanup, they are all destroyed as expected, in a resilient `for-of` loop...
In theory, this pull request should allow picking a device type dynamically right from the test (e.g., via test environment pragmas), but this is not a public API anyway, and we don't recommend such adventures unless you have no other choice. Full-fledged multi-device support will come …
=> refactor: dynamic device allocation

detox/src/devices/common/drivers/android/tools/ApkValidator.js, detox/src/devices/common/drivers/android/tools/ApkValidator.test.js, detox/src/devices/common/drivers/android/tools/__snapshots__/ApkValidator.test.js.snap, detox/src/devices/runtime/drivers/android/AndroidDriver.js, detox/src/devices/runtime/drivers/android/__snapshots__/AndroidDriver.test.js.snap, docs/introduction/partials/_project-setup-apps-android.mdx, examples/demo-react-native/detox.config.js
- This pull request stems from this discussion: https://github.com/wix/Detox/discussions/4307
In this pull request, I have fixed inline code-refs to the Android setup guide, in places where the usage of `testBinaryPath` was not clear.
---
=> Fix refs and docs involving testBinaryPath

.github/workflows/rapid-test.yml, docs/contributing/code/setting-up-the-dev-environment.md, lerna.json, package.json, scripts/ci.android-release.js, scripts/install.sh
Maintenance PR. Updates Lerna to 6.5.0 (the latest is 8.x.x, but it has significant breaking changes).
=> chore: update lerna to latest legacy version

detox/android/detox/src/full/java/com/wix/detox/espresso/DetoxAction.java, detox/android/detox/src/main/java/com/wix/detox/espresso/scroll/ScrollHelper.java, detox/detox.d.ts, detox/ios/Detox/Actions/UIScrollView+DetoxActions.h, detox/ios/Detox/Actions/UIScrollView+DetoxActions.m, detox/ios/Detox/Invocation/Action.swift, detox/ios/Detox/Invocation/Element.swift, detox/src/android/actions/native.js, detox/src/android/core/NativeElement.js, detox/src/android/espressoapi/DetoxAction.js, detox/src/ios/expectTwo.js, detox/src/ios/expectTwoApiCoverage.test.js, detox/src/utils/invocationTraceDescriptions.js, detox/test/e2e/03.actions-scroll.test.js, docs/api/actions.md
- This pull request addresses the issue described here: #3512 
---
=> Add start position as an optional parameter to scrollTo action

detox/src/configuration/__mocks__/configuration/cjs/.detoxrc.cjs, detox/src/configuration/loadExternalConfig.js, detox/src/configuration/loadExternalConfig.test.js
- This pull request addresses the issue described here: #4352
In this pull request, I have added `.cjs` to the list of extensions of possible Detox configs.
=> fix: find *.cjs configs

detox/runners/jest/testEnvironment/index.js
This PR should fix a race condition between Detox and Allure integration, where Detox moves the artifacts before the runtime finishes flushing.
Example of a race condition can be seen here:
https://buildkite.com/wix-mobile-oss/detox/builds/3287#018d9774-bbde-42bf-9877-1efe5c77cde7
```
01:46:30.916 detox[61279] i (node:61279) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 33)
(Use `node --trace-warnings ...` to show where the warning was created)
FAIL  e2e/32.visibility-debug-artifacts.test.js (12.563 s)
● Test suite failed to run
ENOENT: no such file or directory, rename '/Users/builder/build_tmp/detox-allure2-filtered-7688c9a12dc5de47.log' -> '/Users/builder/work/detox/test/allure-results/attachments/b0217737-5296-4f48-9f62-905e6df0b7d4.log'
● …
```
=> fix: stabilize artifacts flushing

detox/src/artifacts/uiHierarchy/IosUIHierarchyPlugin.js, detox/src/artifacts/uiHierarchy/IosUIHierarchyPlugin.test.js
This pull request addresses absent UI hierarchy artifacts in our Allure reports.
It should be helpful for anyone who's using: https://github.com/wix-incubator/detox-allure2-adapter
=> fix(ios): track hierarchy artifacts

detox/test/src/Screens/ActionsScreen.js, detox/test/src/Screens/AttributesScreen.js
- This pull request addresses the issue described here: Legacy slider error in debug builds
---
=> test(e2e): fixed legacy Slider in debug mode

detox/package.json, detox/test/package.json, generation/package.json
Internal PR. Testing the new `beta.9` version
=> chore: upgrade jest-allure2-reporter

detox/src/client/Client.js, detox/src/client/Client.test.js, detox/src/client/__snapshots__/Client.test.js.snap, detox/test/e2e/19.crash-handling.test.js
- This pull request addresses recurring internal support tickets where our users seem to use the following pattern:
```js
try {
await tapOnSomething();
} finally {
await tapOnSomethingElse();
}
```
If `await tapOnSomething()` makes the application crash, the consequent action, `await tapOnSomethingElse()` executes when no app is running. This flow results into misleading errors like this:
```
Detox can't seem to connect to the test app(s)!
HINT: 
Have you forgotten to call 'device.launchApp()' in the beginning of your test?
Refer to our troubleshooting guide, for full details: https://wix.github.io/Detox/docs/troubleshooting/running-tests#tests-execution-hangs
---
The following package could not be delivered:
{
type: 'invoke',
params: [Object],
messageId: 5
}
```
So, this PR improves …
=> fix: communicate crash errors more clearly

detox/src/android/core/WebElement.js, detox/test/e2e/29.webview.test.js
In this PR, I:
- Add missing tests for `runScript` with non-string function as param.
- Replace thrown `Error` with `DetoxRuntimeError` on `WebElement.js`.
=> fix(webviews): apply suggested changes from #4394.

detox/test/package.json
This should fix a compilation error in `detox/test` on Xcode 15.3.
I confirmed that it works on Xcode 15.2 locally as well.
=> chore: upgrade @react-native-community/datetimepicker

detox/package.json
- This pull request addresses the issue described here:
In this pull request, I have reverted the unintended breaking change.
=> fix: revert accidental Node 18.x bump

detox/ios/Detox/Invocation/WebCodeBuilder+createMoveCursorToEndAction.swift, detox/test/e2e/29.webview.test.js, detox/test/src/Screens/WebViewScreen.js
Resolves https://github.com/wix/Detox/issues/4426
See: https://w3.org/Bugs/Public/show_bug.cgi?id=24796
=> fix(ios, webviews): workaround selection on non-text input types.

detox/ios/Detox/Invocation/WKWebViewConfiguration+Detox.m, detox/ios/Detox/Invocation/WebCodeBuilder+createSelector.swift, detox/test/e2e/29.webview.test.js, docs/api/device.md, docs/guide/testing-webviews.md
Adds a new feature toggle, `detoxDisableWebKitSecurity`, controlled through a launch argument, initially set to `false`.
This feature is particularly useful for testing scenarios involving web views and iframes that have CORS-protected content. 
However, turning off web security might result in some pages not loading as expected, for example PCI DSS-compliant pages.
Given the possibility of encountering errors on pages with rigorous security measures, I've tweaked the default setting for this bypass technique and added the feature-flag to enable the bypass.
=> fix(iOS): add launch-argument to disable WebKit security.

detox/ios/Detox/Invocation/WebCodeBuilder+createMoveCursorToEndAction.swift
Fixes: https://github.com/wix/Detox/issues/4437
Based on the list of input-types that support (and don't support) `setSelectionRange`: https://html.spec.whatwg.org/multipage/input.html#:~:text=%C2%B7-,setSelectionRange(),-%C2%B7
=> fix(iOS): avoid `setSelectionRange` on elements that don't support it

detox/ios/Detox/Invocation/WebCodeBuilder+createTypeAction.swift
Hopefully fixes: https://github.com/wix/Detox/issues/4437
TODO:
=> fix(iOS): dispatch input event when changing web inner-element's value.

detox/android/detox/src/full/java/com/wix/detox/reactnative/ReactMarkersLogger.kt
Following issue [#4445](https://github.com/wix/Detox/issues/4445) I added a condition that limits react logger for not supported versions as @d4vidi recommend it
=> Added condition wrapper for only R.N vs supported

docs/troubleshooting/running-tests.md
[This page](https://wix.github.io/Detox/docs/troubleshooting/running-tests#if-you-do-not-see-your-app-running-on-the-device) provides a _very_ helpful list of reasons why a Detox app might not load.
**However, I managed to run into a new one!** 😨
-------------------
Thanks to an errant `git` command, I mistakenly removed [my `network_security_config.xml` file](https://wix.github.io/Detox/docs/introduction/project-setup#43-enabling-unencrypted-traffic-for-detox) and the reference to it in `AndroidManifest.xml`. In the process, the app I was testing stopped loading on my physical Android device.
> I confirmed this was the root cause by:
> 1) trying lots of other things that didn't work 🙃
> 2) restoring my Network Security Config
> 3) confirming that my app launched as expected 🎉 
I thought …
=> docs(troubleshooting): suggest double-checking NetworkSecurityConfig if app won't load

detox/ios/Detox/Utilities/String+LocalizedError.swift
Our `String` extension declares a conformance to the protocols `LocalizedError` and `Error`. 
This will not behave correctly if Swift introduces this conformance in the future. Xcode 16 started to warn when not using this new syntax.
See original Swift proposal: 
https://github.com/swiftlang/swift-evolution/blob/main/proposals/0364-retroactive-conformance-warning.md
=> fix(iOS): add `@retroactive` for protocol conformance (Xcode 16 compliance).

detox/detox.d.ts, detox/internals.d.ts, detox/local-cli/build.js, detox/local-cli/build.test.js, detox/local-cli/start.js, detox/local-cli/start.test.js, detox/local-cli/testCommand/TestRunnerCommand.js, detox/src/configuration/composeCommandsConfig.js, detox/src/configuration/composeCommandsConfig.test.js, detox/src/configuration/index.js, docs/config/apps.mdx
In this pull request, I have extended Detox config resolution so that it can take `build` and `start` scripts not only from every app, but it can take configuration-scoped overrides, where a single command does all the building or app server running.
=> feat(config): multi-app build and start scripts

detox/src/devices/allocation/DeviceAllocator.js, detox/src/devices/allocation/drivers/android/genycloud/GenyAllocDriver.js, detox/src/devices/common/drivers/android/exec/ADB.js, detox/src/devices/common/drivers/android/exec/ADB.test.js, detox/src/realms/DetoxPrimaryContext.js
In this pull request, I have introduced a preliminary `adb start-server` command to the Genymotion-cloud case.
This comes as a potential workaround for some instabilities that we've seen which seem to stem from the daemon being down during initial `gmsaas adbconnect` command.
---
=> Daemon: Add preliminary ADB server-start in Genycloud

detox/src/devices/allocation/drivers/android/genycloud/exec/GenyCloudExec.js, detox/src/devices/allocation/drivers/android/genycloud/exec/GenyCloudExec.test.js, detox/src/devices/allocation/drivers/android/genycloud/services/GenyInstanceLifecycleService.js, detox/src/devices/allocation/drivers/android/genycloud/services/GenyInstanceLifecycleService.test.js, detox/src/devices/allocation/factories/android.js, detox/src/devices/common/drivers/android/exec/ADB.js, detox/src/devices/common/drivers/android/exec/ADB.test.js
In this pull request, I have injected an `adb device` output logging for whenever an `adbconnect` fails. This is meant to help debug recently occurring issues associated with `gmsaas adbconnect`.
---
=> Genycloud debug: ADB devices dump before each adbconnect retry

detox/src/devices/allocation/DeviceAllocator.js, detox/src/devices/allocation/DeviceAllocator.test.js, detox/src/devices/allocation/drivers/AllocationDriverBase.d.ts, detox/src/devices/allocation/drivers/android/genycloud/GenyAllocDriver.js, detox/src/realms/DetoxPrimaryContext.js, detox/src/realms/DetoxPrimaryContext.test.js
=> fix(Android): Added retry for Genymotion device allocation

detox/local-cli/build.js, detox/local-cli/build.test.js
Makes `detox build` respect `--if-missing` flag for missing `testBinaryPath`'s, and also for multi-app build commands.
=> fix(local-cli): respect detox build --if-missing for multi-app builds

detox/scripts/build_xcuitest.ios.sh
`env -i bash -c <command>` runs the specified command in an isolated environment with no inherited environment variables.
- **`env -i`**: Starts a command with an empty environment, ignoring all inherited environment variables.
- **`bash -c`**: Executes a given command string in a new `bash` shell instance.
I've tested this locally on our xcodebuild with @igorgn 👑
=> build: run xcodebuild in isolated env.

detox/scripts/build_xcuitest.ios.sh
Implemented a more secure and efficient method for generating temporary build artifacts, ensuring only essential files are copied to the XCUITest build directory. Adhering to the principle of least privilege (PoLP).
- Reduced the XCUITest build artifact size from `73.6 MB` to `6.6 MB`.
- Use `mktemp` and `trap` to remove all unnecessary artifacts even if the script fails.
=> build(ios): new XCUITest runner build.

docs/api/system.md
=> docs: fix `system` expectations usage examples.

docs/contributing/code/building-and-testing.md, package.json
=> docs: Update contribution docs

detox/android/detox/src/full/java/com/wix/detox/espresso/hierarchy/ViewHierarchyGenerator.kt, detox/ios/Detox/Utilities/ViewHierarchyGenerator.swift, detox/test/e2e/06.device.view-hierarchy.test.js
Fixing a JS error when injecting JS to webviews to generate XML view hierarchy.
The declarations are now made inside the injected JS function and not on the higher scope.
=> fix: avoid duplicated declaration error on xml generation.

detox/ios/Detox/Utilities/ViewHierarchyGenerator.swift
After investigation, I discovered that when `UIDatePicker` is set to `UIDatePickerStyle.wheels` (Spinner mode), it assigns unusual coordinate values for off-screen wheel cells (falling below `Int.min` and above `Int.max`). This leads to a conversion error in `ViewHierarchyGenerator` when attempting to cast these `Double` values to `Int`, resulting in:
```
Double value cannot be converted to Int because the result would be less than Int.min
```
To address this, I kept the `Int` conversion but applied clamping (instead of representing it as a `Double` in the string) for the following reasons:
- Double values can be excessively long, adding unnecessary complexity to the view hierarchy.
- On 32-bit systems, `Int` ranges from -2,147,483,648 to 2,147,483,647, and on 64-bit systems, from …
=> fix(iOS): clamp Double values before converting to Integer.

detox/android/rninfo.gradle, detox/android/settings.gradle, detox/test/android/settings.gradle, examples/demo-react-native/android/settings.gradle
In this pull request, I have improved the android build script in order to be sure it could work in any project structure
---
=> Improved android build scripts

scripts/ci.release.js
Git repo is now being cloned with SSH instead of HTTPS.
=> build(fix): avoid overriding the git remote url.

detox/src/devices/allocation/drivers/android/genycloud/exec/GenyCloudExec.js, detox/src/devices/allocation/drivers/android/genycloud/exec/GenyCloudExec.test.js, detox/src/devices/validation/android/GenycloudEnvValidator.js, detox/src/devices/validation/android/GenycloudEnvValidator.test.js, detox/src/devices/validation/android/__snapshots__/GenycloudEnvValidator.test.js.snap
- This pull request fixes #4417
In this pull request, I have closed the loop on replacing the decommissioned `gmsaas auth whoami` command with the `gmsaas doctor` command.
cc @lilinor
---
=> Starting using 'gmsaas doctor' command

detox/src/client/actions/SyncStatusSchema.json, detox/src/client/actions/formatters/SyncStatusFormatter.js, detox/src/client/actions/formatters/SyncStatusFormatter.test.js, detox/src/client/actions/formatters/__snapshots__/SyncStatusFormatter.test.js.snap, detox/src/client/actions/formatters/sync-resources/AnimationUpdateResourceFormatter.js, detox/src/client/actions/formatters/sync-resources/JavaScriptTimersFormatter.js, detox/test/e2e/12.animations.test.js, detox/test/e2e/14.network.test.js
- Introduces a new synchronization approach to handle JS delays in `Animated.timing` on iOS and new-arch tests.
(See the enabled test in the PR changes). Fixes: https://github.com/wix/Detox/issues/4706
- Fixes a flaky test involving long network requests, originally merged from #4716.
(See the enabled test in the PR changes.)
- Implements branching of the synchronization resource for new-arch vs. old-arch, addressing architectural differences in the synchronization logic. Fixes: #4710 
See: https://github.com/wix-incubator/DetoxSync/pull/83, https://github.com/wix-incubator/DetoxSync/pull/84, https://github.com/wix-incubator/DetoxSync/pull/85
=> fix(ios): JS animation sync resource issues with RN old & new archs.

.gitmodules
Excessive logging from DetoxSync affected the performance significantly (the difference could be observed during our stress tests). I removed the logs from DetoxSync and updated its version.
=> perf(ios): optimize performance by removing excessive logging (DetoxSync).

detox/package.json, detox/src/devices/common/drivers/android/exec/ADB.js, detox/src/devices/common/drivers/android/exec/ADB.test.js, detox/src/devices/runtime/drivers/android/genycloud/GenyCloudDriver.js, detox/src/devices/runtime/drivers/android/genycloud/GenyCloudDriver.test.js, detox/src/utils/childProcess/exec.js, detox/src/utils/childProcess/exec.test.js, detox/src/utils/childProcess/spawn.js, detox/src/utils/childProcess/spawn.test.js, detox/test/package.json, examples/demo-native-android/package.json, examples/demo-native-ios/package.json, examples/demo-plugin/package.json, examples/demo-react-native-detox-instruments/package.json, examples/demo-react-native/package.json, lerna.json, package.json
In this pull request, I have introduced a work-around for recurring issues with Genymotion tunnel connections. Empirically, the connection shows hiccups from time to time, which makes ADB disconnect the device altogether. This PR tackles that by setting longer timeouts and more retries, so as to allow for the gmsaas tunnel to reconnect automatically.
---
=> Alleviate geny-cloud failures due to network hiccups

detox/local-cli/utils/frameworkUtils.js, detox/package.json, detox/src/android/AndroidExpect.test.js, detox/src/devices/allocation/drivers/android/emulator/launchEmulatorProcess.js, detox/src/devices/common/drivers/android/exec/ADB.js, detox/src/devices/common/drivers/android/exec/ADB.test.js, detox/src/devices/common/drivers/android/exec/BinaryExec.js, detox/src/devices/common/drivers/android/exec/BinaryExec.test.js, detox/src/devices/runtime/drivers/ios/SimulatorDriver.js, detox/src/ios/XCUITestRunner.js, detox/src/ios/XCUITestRunner.test.js, detox/src/utils/__snapshots__/assertArgument.test.js.snap, detox/src/utils/assertArgument.js, detox/src/utils/childProcess/exec.js, detox/src/utils/childProcess/exec.test.js, detox/src/utils/childProcess/spawn.js, detox/src/utils/childProcess/spawn.test.js, detox/src/utils/environment.js
**Thanks to the co-author, @matinzd for the initial implementation.**
Detox is using a vulnerable package described in [CVE-2024-21538](https://github.com/advisories/GHSA-3xgq-45jj-v275/dependabot).
- This pull request addresses the issue described here: #4657 and #4640
In this pull request, I have migrated away from unmaintained `child-promise-process` to `promisify-child-process` to fix the transitive vulnerability on `cross-spawn` package.
=> fix: CVE-2024-21538 by migrating to promisify-child-process #4658

detox/src/DetoxWorker.js, detox/test/e2e/pilot/01.pilot.sanity.test.js
* Fixes destructuring access: `const { copilot } = require('detox');`.
* Adds an extra test for this special case.
=> fix: copilot legacy access

detox/src/configuration/composeRunnerConfig.js
Resolves issue when you need to run Detox with `--inspect-brk` but your Jest installation is not in `./node_modules` but, for example, in `../../node-modules/`.
In this pull request, I have changed strategy from hard-coded if-else to `resolveFrom(cwd, 'jest/bin/jest')`.
=> fix(cli): support monorepos with --inspect-brk

detox/detox.d.ts, detox/local-cli/test.test.js, detox/local-cli/testCommand/TestRunnerCommand.js, detox/src/configuration/composeRunnerConfig.js, detox/src/configuration/composeRunnerConfig.test.js, docs/config/testRunner.mdx
Resolves #4764
This pull request introduces functionality to handle specific command-line arguments during test retries in Detox. The key changes include adding support for a `noRetryArgs` configuration to exclude certain arguments (like `shard`) during retries, updating the test runner logic to implement this behavior, and enhancing documentation to explain the new feature.
=> feat(config): noRetryArgs option

detox/__tests__/helpers.js, detox/local-cli/build.test.js, detox/local-cli/test.test.js, detox/package.json, detox/src/android/AndroidExpect.test.js, detox/src/android/core/NativeElement.js, detox/src/artifacts/log/ios/SimulatorLogPlugin.test.js, detox/src/artifacts/templates/artifact/FileArtifact.js, detox/src/artifacts/templates/artifact/FileArtifact.test.js, detox/src/artifacts/utils/temporaryPath.js, detox/src/artifacts/utils/temporaryPath.test.js, detox/src/client/Client.test.js, detox/src/devices/allocation/DeviceRegistry.test.js, detox/src/ios/expectTwo.js, detox/src/ios/expectTwo.test.js, detox/src/logger/DetoxLogger.test.js, detox/src/logger/utils/DetoxLogFinalizer.test.js, detox/src/logger/utils/streams/BunyanTransformer.test.js, detox/src/utils/ExclusiveLockfile.test.js, detox/src/utils/appendFile.test.js, detox/src/utils/environment.test.js, detox/src/utils/fsext.test.js, detox/src/utils/tempfile.js, detox/src/utils/tempfile.test.js, detox/test/integration/stub/StubRuntimeDriver.js, detox/test/integration/timeline-artifact.test.js
- This pull request fixes #4418
(WIP) I've replaced `tempfile` with an internal util which uses `tmp` internally
---
=> Replace node-module 'tempfile' seamlessly with 'tmp'

detox/src/devices/allocation/drivers/android/genycloud/GenyAllocDriver.js, detox/src/devices/allocation/drivers/android/genycloud/GenyRecipeQuerying.js, detox/src/devices/allocation/drivers/android/genycloud/services/GenyRecipesService.js, detox/src/devices/allocation/drivers/android/genycloud/services/GenyRecipesService.test.js, detox/src/devices/allocation/drivers/android/genycloud/services/__snapshots__/GenyRecipesService.test.js.snap
- Fixes #4784
In this pull request, I have addressed the issue of Genymotion recipe disambiguation. Added the following:
- Throw an error when more than one recipe matches a query
- Aligned flow of 0 recipe matches: Throw an error instead of returning null. This is a better approach because the recipes service knows the error details best and therefore should be the one raising the problem.
---
=> Fix handling of ambiguous genymotion recipe matching

detox/android/detox/src/full/java/com/wix/detox/reactnative/idlingresources/ReactNativeIdlingResources.kt
Kotlin 2.x appears to require an opt-in for the use of `.entries`, this has been logged for some time, this PR will fix it:
- Fixes #4678
There was an existing PR that also fixed this - and was in fact used by react-native-firebase's e2e project via patch-package but it had [unaddressed feedback](https://github.com/wix/Detox/pull/4698#discussion_r1944642470) from @gosha212 and was closed stale:
> I don't want to optin for the project. Please optin the specific file instead. You will need to use something like @OptIn(ExperimentalStdlibApi::class)
That's a good point. So I tried that locally and it seemed to work, and now I propose it here.
=> fix(android): enable kotlin 2.x compatibility w/opt-in for `.entries` usage
